### ISSUE TITLE
reflect.Value call Interface() will panic because ”state“,"sizeCache","unknownFields" start with lowercase letter.

### ISSUE THREAD

**Issue by funkol2007** [golang/protobuf#1044] opened 2020-02-26 10:16 UTC
jsonpb version 1.4.0-rc.1 chang XXX_xx to ”state“,"sizeCache","unknownFields" cause panic when we call reflect.Value Interface() function.

**Comment by neild** [comment] 2020-02-26 16:01
These fields are internal state, and aren't intended to be directly accessed.

Can you explain what you're trying to do in more detail?

**Comment by funkol2007** [comment] 2020-02-29 12:28
here are the codes below 👍 
``` go
func funA(v proto.Message) error {
	// do something
	s := reflect.ValueOf(v).Elem()
	for i := 0; i < s.NumField(); i++ {
		value := s.Field(i)
		enumStr := value.Interface().(fmt.Stringer).String()  //will panic here
		// do other thing
	}
	return nil
}
```
So I have to filter these  internal fields generated automatically by protobuf... 
Is this a problem?   @neild

**Comment by dsnet** [comment] 2020-02-29 20:37
Use of Go reflection is problematic because it needs to make assumptions about the structure of a protobuf message that may change in the future. It may work today, but is unlikely to work tomorrow and into the future. One of the flagship features of the new API is first-class support for protobuf reflection. The code you posted could be rewritten as:

```go
import (
    protoV1 "github.com/golang/protobuf/proto"
)

func funA(v proto.Message) error {
    m := protoV1.MessageReflect()
    fds := m.Descriptor().Fields() // list of fields in the message
    for i := 0; i < fds.Len(); i++ { // iterate over all fields
        fd := fds.Get(i) // ith field descriptor

        // Only handle singular enum fields.
        if fd.Cardinality() != protoreflect.Repeated && fd.Kind() == protoreflect.EnumKind {
            num := m.Get(fd).Enum()
            ed := fd.Enum().ByNumber(num) 
            if ed == nil {
                fmt.Sprintf("%d\n", num) // print the enum value by number (since name is unknown) 
            } else {
                fmt.Sprintf("%v\n", ed.Name()) // print the enum value by name
            }
        }
    }
    return nil
}
```

**Comment by dsnet** [comment] 2020-02-29 20:45
Closing this issue as working as intended.

**Closed by dsnet** 2020-02-29 20:45 UTC
Labels: waiting-for-info

**Comment by puellanivis** [comment] 2020-02-29 20:57
Additionally, it is a known matter that while iterating over fields via Go’s standard library `reflect` that you need to skip over unexported fields. This holds for protobuf messages as well as any other struct type.

You can do so by checking the `PkgPath` of the `reflect.StructField`. If it is not empty, then it is an unexported value.
