### ISSUE TITLE
jsonpb: No way for types with UnmarshalJSONPB to unmarshal to nil

### ISSUE THREAD

**Issue by Calebjh** [golang/protobuf#621] opened 2018-05-29 21:10 UTC
Any message type that implements the UnmarshalJSONPB function will be initialized during object unmarshal with no apparent workaround.
For example, consider a special type that must contain a valid UUID string:
```
message UUIDValue {
    string value = 1;
}
```
When unmarshalling, we'll just check that it matches some accepted UUID format.
```
func (m * UUIDValue) UnmarshalJSONPB(_ *jsonpb.Unmarshaler, data []byte) error {
    if !validateUUID(data) {
        return fmt.Errorf(`invalid uuid '%s' does not match accepted format`, string(data))
    }
    m.Value = strings.Trim(string(data), `"`)
    return nil
}
```
But now when unmarshaling any object with a UUIDValue in it, providing a JSON value of `null` will cause the UUIDValue field to be initialized (and error) instead of being set to `nil` like any standard message or WKT. I don't see anything that can be done in the UnmarshalJSONPB method that can cause the field to be `nil`ed either.
Note that providing no JSON value at all will result in the field becoming `nil`, which feels inconsistent and unintuitive.

**Comment by dsnet** [comment] 2018-06-06 02:55
`UnmarshalJSONPB` and `MarshalJSONPB` were not really well-thought out and will probably be deprecated in the future. It's interacted poorly in the past with regard to the JSON<->PB specification and we probably want to diminish rather than increase support for it

**Comment by dsnet** [comment] 2018-08-18 06:43
`UnmarshalJSONPB` and `MarshalJSONPB` were added so that custom protobuf types can support the JSON<->PB specification. However, the root of the issue is the lack of protobuf reflection support. If we had that, the `jsonpb` would not care whether a message was a "custom" type as long it properly implemented the reflection API. Since we are moving to a world with first-class support for reflection, we're going to decline more changes to those interfaces. They will be deprecated in the near future.

See #364.

**Closed by dsnet** 2018-08-18 06:43 UTC
Labels: api-v2, jsonpb
