### ISSUE TITLE
jsonpb: document determinism of output

### ISSUE THREAD

**Issue by lupino3** [golang/protobuf#514] opened 2018-02-12 16:40 UTC
By looking at the code, it looks like jsonpb output is deterministic. However, I could not determine it from reading the docs. It might be oversight on my side, but I think it's not spelled anywhere.

Would it be ok to mention this in the godoc? I can send a pull request if there is interest.

**Comment by dsnet** [comment] 2018-02-12 17:27
Deterministic marshaling is not a stated property in the ProtoBuf<->JSON specification. As such, we shouldn't provide this as a documented hard guarantee in the Go implementation. We don't know if something will change in the specification in the future that causes deterministic serialization difficult.

**Comment by dsnet** [comment] 2018-02-22 01:26
Closing this as intended behavior. We'll keep the wording intentionally vague, unless something in the upstream specification suggests behavior in one direction or the other.

**Closed by dsnet** 2018-02-22 01:26 UTC
Labels: documentation
