### ISSUE TITLE
Support fetching values of custom extension for enum fields loaded using dynamicpb

### ISSUE THREAD

**Issue by ah-edg** [golang/protobuf#1352] opened 2021-08-11 07:59 UTC
**Is your feature request related to a problem? Please describe.**

I am building a protoc plugin based on a descriptor that is unknown at compile time. In my current target proto file, there are enum fields with custom extensions I want to generate code for.

After some failed attempts, I stumbled over https://github.com/golang/protobuf/issues/1065#issuecomment-605324493 and found out that this is apparently a currently unsupported feature.

**Describe the solution you'd like**

I'd like for the library to be able to resolve custom extensions for enum fields loaded using dynamicpb.

**Describe alternatives you've considered**

No alternatives come to mind.

**Additional context**

**Comment by neild** [comment] 2021-08-11 16:41
I don't entirely follow what you're trying to do, but `dynamicpb` does support creating enum types:
https://pkg.go.dev/google.golang.org/protobuf/types/dynamicpb#NewEnumType

If that's not what you're looking for, some more detail would be helpful.

**Comment by ah-edg** [comment] 2021-08-12 13:18
Maybe dynamicpb is wrong - I'm not sure.
I want something that can take any unknown FileDescriptorSet and access the extension value of contained enum fiellds.

Say at Something.Value.FOO -> db_info for a proto like
```
import "google/protobuf/descriptor.proto";

extend google.protobuf.EnumValueOptions {
  DBInfo db_info = 2000;
}

message DBInfo {
  // identifier in database
  uint32 db_id = 1;
  // enum name in database
  string db_name = 2;
  // short description
  string desc = 3;
}

message Something {
  enum Value {
    UNSET = 0;
    FOO = 1 [(db_info) = {
      db_id: 123
      db_name: "fooble"
      desc: "some short descriptive text"
    }];
  }
}
```
and push that through an also unknown go template.

I did not find a way to do so using the api. If I missed it, I'm eager to learn of the right way.

I do see that everything I want is available in the descriptor when running it through `protoc --decode_raw`, though.

**Comment by neild** [comment] 2021-09-23 16:49
If you have a [`protoreflect.EnumValueDescriptor`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect#EnumValueDescriptor) (or any other type of `protoreflect.Descriptor`), you can access the options with the `Options` method. Something like this should work:

```
var vd protoreflect.EnumValueDescriptor // acquired from somewhere
opts := vd.Options().(*descriptorpb.EnumValueOptions)
dbInfo := proto.GetExtension(opts, mypb.E_DbInfo)
```

If you're using the protogen package (you say you're writing a protoc plugin), [`protogen.EnumValue`](https://pkg.go.dev/google.golang.org/protobuf/compiler/protogen#EnumValue) contains the `EnumValueDescriptor`.

**Comment by ah-edg** [comment] 2021-10-01 16:38
@neild that's also super helpful, but not quite. I lack `mypb.E_DbInfo`, that part should also be dynamic.

I need to get [reflect/protoreflect ExtensionType](https://pkg.go.dev/google.golang.org/protobuf@v1.27.1/reflect/protoreflect#ExtensionType) starting from [types/descriptorpb FileDescriptorProto.GetExtension](https://pkg.go.dev/google.golang.org/protobuf@v1.27.1/types/descriptorpb#FileDescriptorProto.GetExtension) - or optionally starting from a CodeGenerationRequest.

Then, I'm in the area you are talking about.

Thanks for getting back to me and sorry for being late with my response.

**Comment by neild** [comment] 2021-10-01 16:56
> I need to get reflect/protoreflect ExtensionType starting from types/descriptorpb FileDescriptorProto.GetExtension - or optionally starting from a CodeGenerationRequest.

Starting with a `FileDescriptorProto`, use [`protodesc.NewFile`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protodesc#NewFile) to get a `protoreflect.FileDescriptor`.

Then look up the `protoreflect.ExtensionDescriptor` in that descriptor, and use [`dynamicpb.NewExtensionType`](https://pkg.go.dev/google.golang.org/protobuf/types/dynamicpb#NewExtensionType) to create a `protoreflect.ExtensionType`.

You'll probably then want to register this type in an [`protoregistery.Types`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoregistry#Types) and provide that registry to `proto.Unmarshal` or other functions that need to look it up. You can either create your own `protoregistry.Types` for this purpose and pass it in [`UnmarshalOptions.Resolver`](https://pkg.go.dev/google.golang.org/protobuf/proto#UnmarshalOptions), or register the descriptor in the `protoregistry.GlobalTypes` global registry.

**Comment by phye** [comment] 2021-12-09 14:13
I'm just running into similar situations here. 

I have the following .proto:
```protobuf
package hello;

extend google.protobuf.EnumValueOptions {
   string msg = 50001;
}

enum MyEnum {
    Invalid = 0;
    Hello = 1 [(msg)="HelloWorld!"];
}
```

And want to extract the msg part from .proto at runtime (i.e. without generating .pb.go files)

Here's my attempt:
```go
fds, err := parser.ParseFiles("hello.proto")
if err != nil {
	fmt.Printf("Failed to parse file. Error: %s", err)
	os.Exit(-1)
}
f := fds[0]
fd_v2, _ := protodesc.NewFile(f.AsProto().(*dpb.FileDescriptorProto), protoregistry.GlobalFiles)
v := fd_v2.Enums().Get(0).Values().Get(1)
o := v.Options()
fmt.Printf("EnumOption is %+v\n", o)

ed := fd_v2.Extensions().Get(0)
et := dynamicpb.NewExtensionType(ed)
expect := proto_v2.GetExtension(o, et)
fmt.Printf("Expect is: %+v\n", expect)
// Expect to get "HelloWorld!" but I have no idea why I just got empty string
```

So, my question is:
1) Am I using protoreflect's APIs correctly? If yes, why can't I get expected result?
2) Given some .proto files, How can I get `protoreflect.FileDescriptor` correctly? I didnot find any API generating `protoreflect.FileDescriptor`.
3) Are there any tutorials on using custom options?

B
[main.go.txt](https://github.com/golang/protobuf/files/7685725/main.go.txt)
TW, I've filed another issue in [jhump/protoreflect](https://github.com/jhump/protoreflect/issues/467)

**Comment by neild** [comment] 2021-12-09 16:50
You need to prefix the option name with the package in which it was defined (`package hello`):

```
Hello = 1 [(hello.msg)="HelloWorld!"];
```

I believe you also need to register the extension type with the registry passed to `protodesc.NewFile` (`protoregistry.GlobalFiles`) before fetching the options:

```
protoregistry.GlobalFiles.RegisterFile(fd_v2) // call this right after NewFile
```

> Given some .proto files, How can I get protoreflect.FileDescriptor correctly? 

The protocol buffer compiler (`protoc`) is the only officially supported way to parse a `.proto` file. `protoc --descriptor_set_out=FILE x.proto` will write a `FileDescriptorSet` for `x.proto` to `FILE`.

You can also use the `github.com/jhump/protoreflect/desc/protoparse` package. That package is not supported by the protocol buffer team, so you'll need to address questions about it to its maintainers.

**Comment by phye** [comment] 2021-12-10 00:18
Just updated my code per your comment:

1) change (msg) to (hello.msg)
2) Add this line right after protodesc.NewFile
```
protoregistry.GlobalFiles.RegisterFile(fd_v2) // call this right after NewFile
```

Still, without any luck...

I believe descriptor.FileDescriptorProto should be compatible between protobuf v1 and v2 API?

**Comment by phye** [comment] 2021-12-10 02:30
BTW, per [golang language guide](https://developers.google.com/protocol-buffers/docs/proto#customoptions)

I do not need to prefix option name with the package?
```
extend google.protobuf.EnumValueOptions {
  optional uint32 my_enum_value_option = 50005;
}
enum MyEnum {
  option (my_enum_option) = true;

  FOO = 1 [(my_enum_value_option) = 321];
  BAR = 2;
}
```

**Comment by neild** [comment] 2021-12-10 02:49
> BTW, per golang language guide

From that page:

> Note that if you want to use a custom option in a package other than the one in which it was defined, you must prefix the option name with the package name, just as you would for type names.

I was mistaken about the need to register the `FileDescriptor`. The problem is that `protodesc.NewFile` creates descriptors that use the options in the `FileDescriptorProto` it was passed. The `EnumValueOptions` provided by `github.com/jhump/protoreflect/desc/protoparse` does not have the `hello.msg` extension set on it. It does, however, have the extension in the `EnumValueOptions`'s unknown fields section.

So this is rather roundabout, but you can get at the extension value by marshaling and unmarshaling the `EnumValueOptions`--marshaling it will preserve the `hello.msg` value from the unknown fields, and the unmarshal will have access to the extension type.

Perhaps `protodesc` should do this automatically when it notices an options message has unknown fields.

**Comment by phye** [comment] 2021-12-10 03:34
> > BTW, per golang language guide
> 
> From that page:
> 
> > Note that if you want to use a custom option in a package other than the one in which it was defined, you must prefix the option name with the package name, just as you would for type names.
I got this, but in my case, I am not refering to a custom option defined in another package. Anyway, it's a minor issue that can be ignored.
> 
> I was mistaken about the need to register the `FileDescriptor`. The problem is that `protodesc.NewFile` creates descriptors that use the options in the `FileDescriptorProto` it was passed. The `EnumValueOptions` provided by `github.com/jhump/protoreflect/desc/protoparse` does not have the `hello.msg` extension set on it. It does, however, have the extension in the `EnumValueOptions`'s unknown fields section.
Thanks for the findings! This brings me closer to my target :)
> 
> So this is rather roundabout, but you can get at the extension value by marshaling and unmarshaling the `EnumValueOptions`--marshaling it will preserve the `hello.msg` value from the unknown fields, and the unmarshal will have access to the extension type.
Can you be more specific on the details of getting the extension type? 
> 
> Perhaps `protodesc` should do this automatically when it notices an options message has unknown fields.

**Comment by phye** [comment] 2021-12-10 04:10
Also, maybe I can go in another direction: give up using jhump's protoparse package, using official protobuf reflect packages only. In this case, if I were to achieve what I described above, can you tell me how to do that?

IMHO, the main blocker is how to get protoreflect.FileDescriptorProto, I know I can use protoc to get FileDescriptorSet file, but what's the next?

**Comment by neild** [comment] 2021-12-10 18:20
What you're trying to do here is difficult because you've effectively got a circular dependency: You're parsing a `.proto` file to create a `descriptorpb.EnumValueOptions` message with an extension, where the extension is defined in the same `.proto` file.

Extensions are keyed by a `protoreflect.ExtensionType`.

So right now, you:

* Parse the `.proto` file with `protoparse`. The `ExtensionType` does not exist yet. `protoparse` returns an `EnumValueOptions` with no extension set (but with the extension data in the unknown fields section).
* Create a `protoreflect.EnumValueDescriptor` with `protodesc`. This just copies the `EnumValueOptions` returned by `protoparse`.
* Create a `protoreflect.ExtensionType` with `dynamicpb`. This works, but it's too late--the `EnumValueOptions` was created before this `ExtensionType`.

You will encounter the same circularity if you use `protoc` to parse the `.proto` file.

Taking a step back, this will become much easier if you define the extension before working with any files that use that extension. Then you can create the `ExtensionType` before parsing any files that refer to the extension.

**Comment by phye** [comment] 2021-12-11 02:14
Thanks for the detailed explanation! However, I still have some concerns:

you just mentioned following point:
> You will encounter the same circularity if you use protoc to parse the .proto file.

If this is true, you mean that the original hello.proto I attached will not be compiled by protoc, however I confirmed that protoc can handle it correctly, as is attached via `protoc --go_out=. hello.proto`

[hello.pb.go.txt](https://github.com/golang/protobuf/files/7696277/hello.pb.go.txt)

**Comment by ah-edg** [comment] 2022-01-28 12:05
@neild after an eternity I was able to get back to this and got it running. The problem is resolved from my point of view, thank you so much!

If you have a sensible space for it, I can contribute a protoc-plugin as an example (`protoc-gen-json`) that dumps the CodeGenerationRequest as `request.json` and also resolves extensions and options while doing so. It might still have some errors, but generally works quite well.
IMO that's something that's sorely missing in protoc to get a better impression of how that thing really works :-)

As @phye piggybacked on the issue, I'll still leave it open.

**Comment by phye** [comment] 2022-02-06 09:45
@ah-edg Thanks for the explanation above(not sure if you can paste your code snippet somewhere accessible by the public). 
Please go ahead to close the issue above.

P.S. I've found some alternative method to solve my problem (found out that I donot need to parse .proto at runtime hence I can just import that .pb.go generated by protoc) and iterate over extentions by walking through FileDescriptor.

**Closed** 2022-02-07 08:20 UTC

**Comment by peachestao** [comment] 2022-09-28 14:19
@ah-edg Can you tell me how to solve it? I happen to have the same problem。
