### ISSUE TITLE
optional fields with empty value omitted

### ISSUE THREAD

**Issue by snowwolf007cn** [golang/protobuf#983] opened 2019-11-05 07:09 UTC
**What version of protobuf and what language are you using?**
Version:v3

**What did you do?**
empty values make related message fields omitted.

**What did you expect to see?**
empty values display empty value, unset optional field omitted

**What did you see instead?**
both omitted

**Comment by neild** [comment] 2019-11-05 19:05
Omitted from what?

If you're using `proto3`, there's no concept of an optional field and a field set to its zero value will generally not appear in the marshaled form of a message (text, wire, etc.). If that's what you're seeing, it's expected behavior.

**Comment by andreasph** [comment] 2019-12-19 18:31
https://github.com/golang/protobuf/blob/4c88cc3f1a34ffade77b79abc53335d1e511f25b/jsonpb/jsonpb.go#L68, if talking about jsonpb

**Comment by dsnet** [comment] 2019-12-19 23:43
Closing due to lack of information.

**Closed by dsnet** 2019-12-19 23:43 UTC
Labels: waiting-for-info
