### ISSUE TITLE
jsonpb: google.protobuf.Any with google.protobuf.Empty payload not marshaled correctly

### ISSUE THREAD

**Issue by jhump** [golang/protobuf#759] opened 2018-11-21 18:26 UTC
I know this is a minor issue and a contrived case -- after all, what value would someone have in embedding an empty message inside of an any message, right? However, I happen to use this particular combo when testing things (libraries, tools that handle protos, etc) and want to do some smoke tests of handling of any messages. While doing exactly that, I found that the Go runtime treats any messages with a well-known empty payload incorrectly.

According to the spec for how [protos are represented as JSON](https://developers.google.com/protocol-buffers/docs/proto3#json), there is nothing special about `google.protobuf.Empty` messages.

Other runtimes, such as Java, treat it as a normal message when embedding it in a `google.protobuf.Any`.

However, the Go runtime produces a special JSON format, with a `value` key. It looks like this is caused by the use in `jsonpb` of the generated `XXX_WellKnownType` method. However, just because it is a well-known type does not mean it necessarily needs special treatment in its JSON format.

**What version of protobuf and what language are you using?**

protoc 3.5.1, Go (version 9f81198da99b79e14d70ca2c3cc1bbe44c6e69b6 of this repo, but the issue repros with latest master)

**What did you do?**

Created an `any.Any` instance whose payload was an encoded `empty.Empty`. Serialized the any message to JSON.

**What did you expect to see?**

```
{
  "@type": "type.googleapis.com/google.protobuf.Empty"
}
```

**What did you see instead?**

```
{
  "@type": "type.googleapis.com/google.protobuf.Empty",
  "value": {}
}
```

**Comment by cybrcodr** [comment] 2018-11-21 19:53
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Any

> If the embedded message type is well-known and has a custom JSON representation, that representation will be embedded adding a field value which holds the custom JSON in addition to the @type field.

`google.protobuf.Empty` is one of the well-known types and does have a custom JSON representation as stated in https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#empty

> The JSON representation for Empty is empty JSON object {}

**Comment by jhump** [comment] 2018-11-21 20:13
I think we're interpreting this differently. I don't interpret `{}` to be a custom JSON representation. (That is how it is serialized without any custom handling.)

And, as mentioned in the initial description, the other runtimes, such as [Java](https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L698) and [C/C++](https://github.com/protocolbuffers/protobuf/blob/46a48e49aa8357bbeee8040819a35e59880e329a/src/google/protobuf/util/internal/protostream_objectwriter.cc#L1174), do not consider it special either. Are they wrong?

I'll open an issue with the main protobuf project to ask for clarification. At minimum, the spec should be made explicitly clear. But all language implementations really should behave the same way -- otherwise, they are not correctly interoperable.

**Comment by cybrcodr** [comment] 2018-11-21 20:53
I agree that it would be nice for all language implementations to behave the same way.  I do think that it should be based on specifications.  And it does seem like the spec is not fully clear on this as we differ in our interpretations.

Thanks for posting an issue on the protobuf project for this.

**Comment by dsnet** [comment] 2018-11-27 08:45
I believe this is a bug. My [re-implementation of `jsonpb`](https://go-review.googlesource.com/c/protobuf/+/134495/1/encoding/jsonpb/known.go#22) does the expected behavior since "Empty" is not part of the map of special well-known types.

Not worth fixing in v1.

**Comment by dsnet** [comment] 2020-03-03 06:42
The new [`protojson`](import "google.golang.org/protobuf/encoding/protojson") package addresses this issue and has been released as part of [`google.golang.org/protobuf@v1.20.0`](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0).

**Closed by dsnet** 2020-03-03 06:42 UTC
Labels: bug, pending-v2
