### ISSUE TITLE
compiler/protogen: relax enforcement of valid import paths

### ISSUE THREAD

**Issue by marwan-at-work** [golang/protobuf#1316] opened 2021-05-04 02:53 UTC
**What version of protobuf and what language are you using?**

v1.26.0 of the v2 go protobuf module.

**What did you do?**
Ran `go mod init hello` and create a .proto file at the root of the module. 

```
syntax = "proto3";
package hello;
option go_package = "hello;hello";

message Hello { string hello = 1; }
```

**What did you expect to see?**
protoc-gen-go to succeed because "hello" is valid module and import path name in Go.

**What did you see instead?**
An error saying that at least 1 slash is required in the import path.

**Comment by dsnet** [comment] 2021-05-04 03:08
The reason for the check is because we were observing that many users were treating `go_package` as if it were simply specifying just a package name, rather than the full import path. This leads to other problems since `protoc-gen-go` can't correctly figure out it's dependencies as it needs the full import path, not just the package name. While a module may in theory not have any slashes, in practice it almost always has a slash.

Can you explain the rationale for allow import paths without slashes?

**Comment by marwan-at-work** [comment] 2021-05-04 03:59
Hi @dsnet 

That's definitely understandable. 

Though I gave a trivial module name like "hello", the rationale behind import paths without slashes is that there are modules that use vanity names as the root of their modules without needing a slash. 

I ran into this issue myself as I have a private module whose root is `src.example.com` and that's where I defined my protobufs as well. 

For an open source example, the Upspin project's root module is simply upspin.io as seen [here](https://github.com/upspin/upspin/blob/5ddde7b8e6fff64b46165b1db0231a67a545aac4/go.mod#L1). Though Upspin doesn't define its protos at the root repo, it could be very surprising to find that that's disallowed.

Thanks,

**Comment by dsnet** [comment] 2021-05-04 04:04
What are your thoughts of on permitting any import path that has at least either a slash or a dot? In both your examples, the module path is at least a valid domain name, which always has a dot.

Ideally, we relax the restriction such that valid and reasonable import paths are possible, but still prevent common mistakes.

**Comment by marwan-at-work** [comment] 2021-05-04 04:32
@dsnet I think that sounds great.

**Comment by nicks** [comment] 2021-05-07 17:24
I'm running into what I suspect is the same issue:

```
protoc-gen-go: invalid Go import path "runtime" for "k8s.io/apimachinery/pkg/runtime/generated.proto"

The import path must contain at least one forward slash ('/') character.
```

Unfrotunately, this is a very widely used protobuf that we depend on, and don't really have the power to change (https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/generated.proto#L25)

would it be possible to add a flag to silence this error, at least to give upstream projects time to fix this?

(Apologies if this is an unrelated issue - I'm trying to trace back through several layers of protobuf abstraction and dependent projects to try to figure out what changed and why we're hitting this now)

**Comment by dsnet** [comment] 2021-05-07 17:27
I don't believe this is the same issue, but rather a manifestation of what the check was trying to prevent.

According to the repo's [go.mod](https://github.com/kubernetes/apimachinery/blob/master/go.mod) file, the module path is `k8s.io/apimachinery`. Thus, the correct `go_package` option for that `.proto` file seems to have supposed to been `k8s.io/apimachinery/pkg/runtime`, which matches the [existing package path](https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime).

Thus, I would say that the check is working as intended in that case.

**Comment by nicks** [comment] 2021-05-07 18:37
thanks! do you know when/where this check was introduced into the toolchain? I can file bugs upstream against projects that have this problem, and it would help out a lot if I have detailed info on what versions of protoc-gen-go this affects.

**Comment by dsnet** [comment] 2021-05-08 08:34
The check was supposed to have been added in v1.20.0, but there may have been a bug in the check where it wasn't quite triggering as expected until v1.26.0.

**Comment by dsnet** [comment] 2021-05-25 03:00
Fixed with https://golang.org/cl/316949

**Closed** 2021-05-25 03:01 UTC
