### ISSUE TITLE
allow being called for multiple packages

### ISSUE THREAD

**Issue by nhooyr** [golang/protobuf#674] opened 2018-08-05 00:25 UTC
See https://github.com/square/goprotowrap

> Unlike other language plugins, the Go protobuf plugin expects to be called separately for each package, and given all files in that package.

In order to be consistent with other language plugins, the Go protobuf plugin should be able to handle being called for multiple packages at the same time.

**Comment by dsnet** [comment] 2018-08-05 07:28
This is a duplicate of #39. @neild and I have discussed wanting to fix this (as you noticed) to be consistent with other languages. However, it is a low priority item for us at this time.

**Closed by dsnet** 2018-08-05 07:28 UTC
