### ISSUE TITLE
protoreflect: setting a map / repeated field

### ISSUE THREAD

**Issue by dave** [golang/protobuf#1245] opened 2020-11-20 13:06 UTC
I need to set an arbitrary field of a proto message. Unfortunately, for repeated fields and maps this is not straightforward. The code below:

```go
message.Set(field, protoreflect.ValueOf(value))
```

... panics [here](https://github.com/protocolbuffers/protobuf-go/blob/master/reflect/protoreflect/value_union.go#L91) with the message: `invalid type: []string`.

It seems that [Converter](https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/internal/impl#Converter) allows conversion between `reflect.Value` and `protoreflect.Value` for all values including maps and lists, but it's in an internal package... Would this be a good candidate for exposing as public?

Or perhaps there's an easy way to accomplish this that I've missed?

@dsnet

**Comment by neild** [comment] 2020-11-20 17:33
For composite types (repeated fields, map fields, message fields), there's no way to construct a `protoreflect.Value` that can be used universally for every field of a type.

This might make more sense with a concrete example: Let's say you've got a generated message type `somepb.T`, and a dynamic `dynamicpb.Message` with the same protobuf type.

```go
// m is a value of a generated message type.
m := &somepb.T{
  StringField: "foo",
  RepeatedStringField: []string{"a", "b", "c"},
}

messageDesc := m.ProtoReflect().Descriptor()
stringField := messageDesc.Fields().ByName("string_field")
repeatedStringField := messageDesc.Fields().ByName("string_field")

// d is a dynamically constructed message, with the same protobuf message type as m.
d := dynamicpb.NewMessage(messageDesc)

// This is fine: A scalar string protoreflect.Value can be used with either m or d.
m.Set(stringField, protoreflect.ValueOfString("bar"))
d.Set(stringField, protoreflect.ValueOfString("bar"))
d.Set(stringField, m.Get(stringField)) // copy from m to d

// This will panic: The concrete implementations of protoreflect.List are different for m and d.
d.Set(repeatedStringField, m.Get(repeatedStringField))
```

To set the contents of a composite field, you can either get the current value of the field and modify it (`m.Mutable(fieldDesc)`) or you can create a new value of the field type (`m.NewField(fieldDesc)`), populate it, and assign it.

**Comment by dsnet** [comment] 2020-11-20 23:06
The purpose of protobuf reflection is to abstract away the concrete implementation and provide an API that is agnostic towards the underlying API. Fundamentally, use of `[]string` assumes that the target message represents a `repeated string` field as a `[]string`. While this may commonly be the case for the generated API for `protoc-gen-go`, protobuf reflection cannot assume that this is universally true.

**Comment by dsnet** [comment] 2020-12-01 21:06
Closing as working as intended.

**Closed by dsnet** 2020-12-01 21:06 UTC
