### ISSUE TITLE
proto: repeated imported enum cause panic

### ISSUE THREAD

**Issue by purefire** [golang/protobuf#1135] opened 2020-05-24 02:00 UTC
**What version of protobuf and what language are you using?**
Version:  	github.com/golang/protobuf v1.4.2 (seems to be the same with google.golang.org/protobuf/proto lastest version)

**What did you do?**
have a proto defined a enum like
enum OSType {
UNKNOWN_OSTYPE = 0;
MACOS = 1;
IOS = 2;
ANDROID = 3;
WINDOWS = 4;
}
in fileA, then import it and use it in a object in fileB:
import fileA
...
message SomeObj {
...
repeated OSType platforms = 10;
...
}
then generate into some go files. When I use it as a return value of, I find the panic, whatever I put a nil, empty array, or an array of several OSTypes(non-duplicated).

Debug into the code and find it's related to this enum array - in this object I have several other enums but none of them cause any problem. What's more, if I move this enum array out of FileA, the panic disappeared immediately.

**What did you expect to see?**
Everything works fine with or without import fileA

**What did you see instead?**
The panic reads like:
[2020-05-22T21:03:55+08:00] catch panic!!! panic location: google.golang.org/protobuf/internal/filedesc.(*EnumValues).Get:66
stacktrace:
goroutine 4447 [running]:
runtime/debug.Stack(0xc001836528, 0x31e87a0, 0xc000456c30)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
git.purefire.org/package/common.Recover(0x3267540, 0xc001d580c0, 0xc000c6c9c8)
/Users/purefire/go/pkg/mod/git.purefire.org/package/common@v1.0.322/common.go:213 +0x16e
panic(0x2b9ec00, 0xc0008ab7c0)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
google.golang.org/protobuf/internal/filedesc.(*EnumValues).Get(0xc0000f01c0, 0x0, 0xc0000f01c0, 0x101008b) /Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/filedesc/desc_list_gen.go:66 +0x4b
google.golang.org/protobuf/internal/impl.newEnumConverter(0x32859e0, 0x2a2c6a0, 0x32858c0, 0xc000264d60, 0x29bb7c0, 0xc0018993e0) /Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/convert.go:379 +0x85
google.golang.org/protobuf/internal/impl.newSingularConverter(0x32859e0, 0x2a2c6a0, 0x32858c0, 0xc000264d60, 0xc000c6bb60, 0x116987b) /Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/convert.go:138 +0xefa
google.golang.org/protobuf/internal/impl.newListConverter(0x32859e0, 0xc0001e8ac0, 0x32858c0, 0xc000264d60, 0xe0, 0x2b12f60) /Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/convert_list.go:17 +0xae
google.golang.org/protobuf/internal/impl.NewConverter(0x32859e0, 0xc0001e8ac0, 0x32858c0, 0xc000264d60, 0xc000c6bc18, 0x1016587)
/Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/convert.go:56 +0x123
google.golang.org/protobuf/internal/impl.fieldInfoForList(0x32858c0, 0xc000264d60, 0x29f3e60, 0x9, 0x0, 0x0, 0x32859e0, 0x290fa00, 0x29f3e6b, 0x4e, ...)
/Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/message_reflect_field.go:172 +0xe1
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc000d9a140, 0xffffffffffffffff, 0xffffffffffffffff, 0x80, 0xffffffffffffffff, 0xc001fb7ad0, 0xc001fb7b00, 0xc001fb7b30, 0xc001fb7b60) /Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/message_reflect.go:61 +0x673
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs(0xc000d9a140, 0x32859e0, 0x2d16600, 0xffffffffffffffff, 0xffffffffffffffff, 0x80, 0xffffffffffffffff, 0xc001fb7ad0, 0xc001fb7b00, 0xc001fb7b30, ...) /Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/message_reflect.go:36 +0x63
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc000d9a140)
/Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/message.go:90 +0x19c
google.golang.org/protobuf/internal/impl.(*MessageInfo).init(0xc000d9a140)
/Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/message.go:72 +0x3c
google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).ProtoMethods(0xc0004563d0, 0x120804b) /Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/message_reflect_gen.go:150 +0x2f
google.golang.org/protobuf/proto.protoMethods(...) /Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/proto/proto_methods.go:18
google.golang.org/protobuf/proto.sizeMessage(0x327da60, 0xc0004563d0, 0xc0004563d0)
/Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/proto/size.go:30 +0x35
google.golang.org/protobuf/proto.MarshalOptions.Size(0x2000000, 0x31e9c80, 0xc0004563d0, 0x31e9c80)
/Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/proto/size.go:26 +0x4e
google.golang.org/protobuf/proto.Size(...)
/Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/proto/size.go:16
google.golang.org/protobuf/internal/impl.sizeMessageSlice(0xc001fb7a70, 0x32859e0, 0x2cbdf40, 0x1, 0x2d43700, 0x2ad9e00) /Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/codec_field.go:526 +0xbb
google.golang.org/protobuf/internal/impl.makeMessageSliceFieldCoder.func1(0xc001fb7a70, 0xc00191ac60, 0x2e4800, 0x2ad9e00) /Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/codec_field.go:452 +0x54
google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointerSlow(0xc000d9a3c0, 0xc001fb7a70, 0x5054d00, 0x0)
/Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/encode.go:79 +0xbe
google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointer(0xc000d9a3c0, 0xc001fb7a70, 0x2ad9e00, 0xc001fb7a70)
/Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/encode.go:56 +0x7
google.golang.org/protobuf/internal/impl.(*MessageInfo).size(0xc000d9a3c0, 0x327da60, 0xc000456380, 0x1208100, 0xc000d9a3c0)
/Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/encode.go:40 +0x55
google.golang.org/protobuf/proto.MarshalOptions.marshal(0xc000000001, 0x0, 0x0, 0x0, 0x327da60, 0xc000456380, 0xc000456380, 0x327da60, 0xc000456380, 0x2ad9e00, ...)
/Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/proto/encode.go:153 +0x2f6
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend(0x2000001, 0x0, 0x0, 0x0, 0x31e9c80, 0xc000456380, 0x29dfa40, 0x300db40, 0x2a934e0, 0xc0023eb260, ...)
/Users/purefire/go/pkg/mod/google.golang.org/protobuf@v1.23.0/proto/encode.go:125 +0x98
github.com/golang/protobuf/proto.marshalAppend(0x0, 0x0, 0x0, 0x324fa80, 0xc001fb7a70, 0x324fa00, 0xc001fb7a70, 0x0, 0x0, 0x0, ...)
/Users/purefire/go/pkg/mod/github.com/golang/protobuf@v1.4.2/proto/wire.go:40 +0xbe
github.com/golang/protobuf/proto.Marshal(...)
/Users/purefire/go/pkg/mod/github.com/golang/protobuf@v1.4.2/proto/wire.go:23 

**Anything else we should know about your project / environment?**
I am using Kite framework, not sure if it's related.

I am not sure if this is a mis-use or bug? Though I've got a workaround, looking forwards some insight and best-practice. Thanks.

**Comment by dsnet** [comment] 2020-05-24 02:21
Thanks for the report, but without actual code to run as a reproduction, there isn't much we can do.

**Comment by dsnet** [comment] 2020-06-05 20:29
Closing as inactionable; no reproduction given.

**Comment by jamiehannaford** [comment] 2021-01-15 14:05
@dsnet We also just ran into this, so I think the issue should be reopened. I'll try to summarise the problem below.

---

If you have two proto files:

```
// services.proto

import "common.proto";

message ListServicesRequest {
    repeated Status filter_statuses = 1;
}
```

```
// common.proto

enum Status {
    NOT_SET = 0;
    DISABLED = 1;
    ENABLED = 2;
}
```

whenever you call a RPC method that uses `ListServicesRequest`, the following error is returned:

```
2021/01/15 12:19:32 http: panic serving 10.125.39.64:32176: runtime error: index out of range [0] with length 0
goroutine 159 [running]:
net/http.(*conn).serve.func1(0xc00056e640)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0xfdeac0, 0xc0004b6a60)
        /usr/local/go/src/runtime/panic.go:975 +0x3e9
google.golang.org/protobuf/internal/filedesc.(*EnumValues).Get(0xc0000eaa80, 0x0, 0xc0000eaa80, 0xc0003e19a0)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/filedesc/desc_list_gen.go:66 +0x4c
google.golang.org/protobuf/internal/impl.newEnumConverter(0x11d5240, 0xef5060, 0x11d5120, 0xc0002be380, 0xc00000e758, 0xd68861a761eb97d8)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/convert.go:379 +0x8b
google.golang.org/protobuf/internal/impl.newSingularConverter(0x11d5240, 0xef5060, 0x11d5120, 0xc0002be380, 0xc0003e19e8, 0x8de86b)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/convert.go:138 +0xdfb
google.golang.org/protobuf/internal/impl.newListConverter(0x11d5240, 0xc00043a680, 0x11d5120, 0xc0002be380, 0xe6b320, 0x0)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/convert_list.go:17 +0x1f4
google.golang.org/protobuf/internal/impl.NewConverter(0x11d5240, 0xc00043a680, 0x11d5120, 0xc0002be380, 0x11ccc00, 0xc0004076b0)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/convert.go:56 +0x126
google.golang.org/protobuf/internal/impl.fieldInfoForList(0x11d5120, 0xc0002be380, 0xfa7953, 0xe, 0x0, 0x0, 0x11d5240, 0xe74d80, 0xfa7963, 0xa0, ...)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect_field.go:172 +0xe5
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc0005f4140, 0x58, 0xffffffffffffffff, 0x40, 0xffffffffffffffff, 0xc0004072f0, 0xc000407320, 0xc000407350, 0xc000407380)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect.go:61 +0x69d
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs(0xc0005f4140, 0x11d5240, 0x1004600, 0x58, 0xffffffffffffffff, 0x40, 0xffffffffffffffff, 0xc0004072f0, 0xc000407320, 0xc000407350, ...)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect.go:36 +0x65
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc0005f4140)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message.go:90 +0x192
google.golang.org/protobuf/internal/impl.(*MessageInfo).init(...)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message.go:72
google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).ProtoMethods(0xc0004b4a10, 0xc0003e2158)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect_gen.go:150 +0x53
google.golang.org/protobuf/proto.protoMethods(...)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/proto_methods.go:18
google.golang.org/protobuf/proto.MarshalOptions.marshal(0xc000000001, 0x0, 0x0, 0x0, 0x11d2de0, 0xc0004b4a10, 0xc0004b4a10, 0x11d2de0, 0xc0004b4a10, 0x1027a20, ...)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/encode.go:143 +0x49
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend(0x1000001, 0x0, 0x0, 0x0, 0x11afde0, 0xc0004b4a10, 0x203000, 0x7f0c1b3effff, 0xc00, 0x8, ...)
        /go/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/encode.go:125 +0x98
github.com/golang/protobuf/proto.marshalAppend(0x0, 0x0, 0x0, 0x11c38e0, 0xc00011a5a0, 0xc00043a500, 0x40, 0x40, 0xfd1700, 0x418745, ...)
        /go/pkg/mod/github.com/golang/protobuf@v1.4.2/proto/wire.go:40 +0xc7
github.com/golang/protobuf/proto.Marshal(...)
        /go/pkg/mod/github.com/golang/protobuf@v1.4.2/proto/wire.go:23
```

This only occurs if the RPC method uses a request struct, which contains a `repeated` field that references an Enum _in a different file_. So if your proto file imports that enum, it will cause an error.

Downgrading to `v1.3.5` fixed this, so I think it's a regression from `v1.4` onwards.

**Comment by jamiehannaford** [comment] 2021-01-15 14:06
https://github.com/mesg-foundation/engine/issues/1805 also reports the same bug after upgrading to v1.4+

**Comment by puellanivis** [comment] 2021-01-15 16:03
I’ve setup a gRPC service with the given proto files, and… it doesn’t crash. It just works, as expected.

**Comment by neild** [comment] 2021-01-15 18:15
If you can give us actual code with a reproduction we can look into it, but without a way to reproduce the problem I'm afraid there's not much we can do.

**Comment by cristaloleg** [comment] 2021-02-03 12:33
We've encountered same problem too, have fixed via downgrade to `google.golang.org/grpc v1.33.2` (from `google.golang.org/grpc v1.34.0`)

```
// svc.proto
message Request {
    repeated model.Status statuses = 1;
}

// model.proto
enum LeadStatus {
    // 7 enums, nothing interesting
}
```

Looking at the stacktrace (our or from OP's message) problem lies here, 'cause `Values()` is empty but we're still trying to get item 0. https://github.com/protocolbuffers/protobuf-go/blob/master/internal/impl/convert.go#L379

**Comment by puellanivis** [comment] 2021-02-03 13:05
We need to repeat, we are not able to reproduce this issue in any way shape or form.

We require a reproducible case before we can figure out anything that is going wrong here. All our attempts at including an enum from a separate package work fine.

Any further “me, too!” is not going to help us without some sort of actual reproduction that we can look at.

**Comment by jamiehannaford** [comment] 2021-02-03 13:37
@puellanivis Perhaps you could provide some info on your set-up? What versions of protobuf and Go were you running when you couldn't recreate?

**Comment by cristaloleg** [comment] 2021-02-03 13:40
@puellanivis see https://github.com/cristaloleg/public-bugs/tree/main/protobuf1135

**Comment by dsnet** [comment] 2021-02-03 16:40
Thank you @cristaloleg for the reproduction. I am able to reproduce the error.

**Comment by neild** [comment] 2021-02-03 19:06
I believe this is because the `model.pb.go` is calling the `github.com/gogo/protobuf/proto` package's versions of `proto.RegisterEnum` and `proto.RegisterFile`.

**Comment by dsnet** [comment] 2021-02-03 20:26
@neild is right that the issue is that `gogo/protobuf` is being used. The new implementation requires that full protobuf type information be available so that it can initialize the table-driven serializers the in the correct way. Since this file is generated by `gogo/protobuf`, there is no way to [look up the enum value information here](https://github.com/protocolbuffers/protobuf-go/blob/f1ac97a4c3faf8af729ff8db5f7b57ca2c7be5d1/internal/filedesc/desc_lazy.go#L95-L111).

Theoretically, we can modify this code to more gracefully handle when certain pieces of protobuf type information is missing, but it gets really complicated quickly. If property A depends on B, and B depends on C, and C depends on D, and property D is somehow broken, how can we reason about the soundness of A, B, and C? In some cases we can, in others we can't. This specific example seems to be calling `proto.Marshal` which theoretically should not need enum type information, while other cases definitely will (such as any any text-based serialization). It is not possible to cleanly separate the descriptor logic here from whether enum information is truly needed or not. This logic (in `internal/filedesc`) is designed to provide a type-complete representation to the layer above without caring whether the layer above needs all that information.

**Comment by puellanivis** [comment] 2021-02-03 20:30
Hm… I wonder if we could at least panic with some sort of “is one of your pb.go files importing gogo/protobuf or some other non-standard protobuf package instead?” message?

At the very least it would point people to problem scope that they could at least investigate and have a chance at resolving.

**Comment by dsnet** [comment] 2021-02-03 20:43
@puellanivis, panicking with a more obvious message that the protobuf type system is incomplete is probably situation than the current status quo.

If I locally modify the provided example with the following patch, then `go run .` succeeds:
```patch
diff --git a/protobuf1135/go.mod b/protobuf1135/go.mod
--- a/protobuf1135/go.mod
+++ b/protobuf1135/go.mod
@@ -4,5 +4,6 @@ go 1.15
 
 require (
 	github.com/gogo/protobuf v1.3.2
+	github.com/golang/protobuf v1.4.2
 	google.golang.org/grpc v1.35.0
 )
diff --git a/protobuf1135/main.go b/protobuf1135/main.go
--- a/protobuf1135/main.go
+++ b/protobuf1135/main.go
@@ -55,5 +55,5 @@ type Server struct {
 }
 
 func (*Server) GetStatues(context.Context, *svc.Request) (*svc.Response, error) {
-	return nil, nil
+	return &svc.Response{}, nil // cannot serialize nil svc.Response
 }
diff --git a/protobuf1135/model/model.pb.go b/protobuf1135/model/model.pb.go
--- a/protobuf1135/model/model.pb.go
+++ b/protobuf1135/model/model.pb.go
@@ -6,6 +6,7 @@ package model
 import (
 	fmt "fmt"
 	proto "github.com/gogo/protobuf/proto"
+	golangproto "github.com/golang/protobuf/proto"
 	math "math"
 	strconv "strconv"
 )
@@ -47,9 +48,13 @@ func (Status) EnumDescriptor() ([]byte, []int) {
 
 func init() {
 	proto.RegisterEnum("model.Status", Status_name, Status_value)
+	golangproto.RegisterEnum("model.Status", Status_name, Status_value)
 }
 
-func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }
+func init() {
+	proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8)
+	golangproto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8)
+}
 
diff --git a/protobuf1135/svc/svc.pb.go b/protobuf1135/svc/svc.pb.go
--- a/protobuf1135/svc/svc.pb.go
+++ b/protobuf1135/svc/svc.pb.go
@@ -8,6 +8,7 @@ import (
 	fmt "fmt"
 	model "github.com/cristaloleg/public-bugs/protobuf1135/model"
 	proto "github.com/gogo/protobuf/proto"
+	golangproto "github.com/golang/protobuf/proto"
 	grpc "google.golang.org/grpc"
 	codes "google.golang.org/grpc/codes"
 	status "google.golang.org/grpc/status"
@@ -118,9 +119,14 @@ func (m *Response) GetActualStatuses() []model.Status {
 func init() {
 	proto.RegisterType((*Request)(nil), "svc.Request")
 	proto.RegisterType((*Response)(nil), "svc.Response")
+	golangproto.RegisterType((*Request)(nil), "svc.Request")
+	golangproto.RegisterType((*Response)(nil), "svc.Response")
 }
 
-func init() { proto.RegisterFile("svc.proto", fileDescriptor_e5747b2e02f0c537) }
+func init() {
+	proto.RegisterFile("svc.proto", fileDescriptor_e5747b2e02f0c537)
+	golangproto.RegisterFile("svc.proto", fileDescriptor_e5747b2e02f0c537)
+}
 ```

Essentially, I'm forking all of the type registration calls that go to `gogo/protobuf` also to `golang/protobuf`. There is a minor bug fix in the demo where we need to return `&svc.Response{}` instead of `(*svc.Response)(nil)`.

There's fundamentally no way to fix this in the `google.golang.org` module since type information is fundamentally missing from the perspective of that module. The best we can do is make our implementation handle incomplete type systems by subbing in fake values and types, which are likely to cause issues in other situations.

The best "fix" is either to:
* Locally patch all generated `.pb.go` files emitted by `gogo/protobuf` to also register their protobuf type information with the `github.com/golang/protobuf` module, OR
* Use a `go.mod` replace directive to use a patched version of `gogo/protobuf` where the `Register` functions forward the type information to the `github.com/golang/protobuf` module.

**Comment by dsnet** [comment] 2021-02-03 20:44
It seems that `gogo/protobuf` has an option for this: see https://github.com/gogo/protobuf/blob/master/extensions.md#goprotobuf-compatibility

You'll want to enable the `goproto_registration` flag.

**Comment by puellanivis** [comment] 2021-02-03 21:05
> panicking with a more obvious message that the protobuf type system is incomplete is probably situation than the current status quo.

I think you’re missing a word in “probably better/worse situation” and I don’t think there’s enough context to be absolutely sure. 😆

**Comment by dsnet** [comment] 2021-02-03 21:13
Meant to say "probably better" if we can cleanly identify such cases.

**Comment by cristaloleg** [comment] 2021-02-03 21:38
Thank you @dsnet fix with `goproto_registration` confirmed. However we probably will migrate from `gogo/protobuf` but it's not in stone.

**Comment by dsnet** [comment] 2021-03-29 20:54
Closing as the issue is due to protobuf type information missing since the generated `.pb.go` registers with the gogo/protobuf module, but not this module.

**Closed by dsnet** 2021-03-29 20:54 UTC
Labels: needs-investigation
