### ISSUE TITLE
jsonpb: support ignoring un-resolvable Any messages

### ISSUE THREAD

**Issue by vishalkuo** [golang/protobuf#747] opened 2018-11-09 02:20 UTC
We have a service running with `grpc-gateway` and we've run into an issue with marshaling responses with unknown `google.protobuf.Any` messages. Essentially, we've linked in _most_ of the message types that our `any` field may contain but not all of them. We'd rather skip marshaling those outstanding messages and log a warning or replace the message with a placeholder and some raw output instead of failing to marshal entirely. 

I've seen https://github.com/golang/protobuf/issues/723 which is related in that it wishes to get some sort of JSON output from these unknown messages. I decided not to tack onto that issue as simply skipping these messages could be something that can be dealt with now without waiting for upstream changes.

**Comment by dsnet** [comment] 2018-11-09 09:15
Can you confirm that you are operating on JSON? or did you just mention #723 as being a related issue, but you're actually dealing with a different serialization format.

**Comment by vishalkuo** [comment] 2018-11-09 14:21
We’re operating on JSON

**Comment by vishalkuo** [comment] 2018-11-09 18:35
Almost. This is a problem we have with the `jsonpb.Marshaler` which have a `AllowUnknownFields as far as I can tell. That being said, I think the `AnyResolver` steps might still apply _if_ we can access `defaultResolveAny`.

1. Configure `jsonpb.Marshaler.AllowUnknownFields` to `true`
2. On any marshal if the resolution of an `Any` field fails, fall back to an `emptypb`

**Comment by dsnet** [comment] 2018-11-09 19:08
I'm not sure what you mean. The `Marshaler` has no `AllowUnknownFields` option (as it ignores unknown fields by default). That being said, step 2 should work as well for marshaling as well.

The logic for `defaultResolveAny` is not particularly complicated. I recommend just copying it:
https://github.com/golang/protobuf/blob/951a149f90371fb8858c6c979d03bb2583611052/jsonpb/jsonpb.go#L92-L103

**Comment by dsnet** [comment] 2018-11-09 19:13
If the above works, I'll close this out since there is an available workaround.

**Comment by vishalkuo** [comment] 2018-11-09 19:29
I think your workaround will be sufficient; however I do think it's possible for resolving unknown any types to fail if using the default resolver. I may be misunderstanding.

https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L403-L411

**Comment by dsnet** [comment] 2018-11-09 19:33
> it's possible for resolving unknown any types to fail if using the default resolver

I argue that is intended behavior. The ability to override the default resolver gives you more flexibility. Furthermore, it is generally better to fail loudly, than to fail silently; which is what the default behavior does.

Since the workaround will be sufficient. I'll close this. Comment again on this thread if it doesn't solve the problem.

**Closed by dsnet** 2018-11-09 19:33 UTC
Labels: jsonpb, waiting-for-info

**Comment by i9** [comment] 2019-11-01 18:22
/shameless plug
https://github.com/i9/bar BetterAnyResolver
minimal code to support unknown Any marshal/unmarshal
