### ISSUE TITLE
[Question] Setup in Mac OSX

### ISSUE THREAD

**Issue by scheung38** [golang/protobuf#1251] opened 2020-12-02 11:36 UTC
Getting

.zshrc file:

export GOPATH=$HOME/golib
export PATH=$PATH:$GOPATH/bin
export GOPATH=$GOPATH:$HOME/go

which go:
/usr/local/bin/go

go version:
go version go1.15.5 darwin/amd64

Mac OSX:
Big Sur
11.0.1

```
messages.proto:

syntax = "proto3";

option go_package = "github.com/ps/hellogrpc/messages";

message HelloRequest {
    string Name = 1;
}

message HelloResponse {
    string Message = 1;
}

service HelloService {
    rpc SayHello (HelloRequest) returns (HelloResponse) {}
}
```

protoc pb/messages.proto --go_out=plugins=grpc:go/src 

--go_out: protoc-gen-go: Plugin failed with status code 1.

so tried:

go get -u github.com/golang/protobuf/protoc-gen-go

Tried again:
➜  code protoc pb/messages.proto --go_out=plugins=grpc:go/src   

go/src/: No such file or directory

this is my folder structure:

![Screenshot 2020-12-02 at 11 40 33](https://user-images.githubusercontent.com/1273014/100868329-61c3f080-3493-11eb-86da-a53b635019bc.png)

**Comment by puellanivis** [comment] 2020-12-03 11:02
It looks like you’re trying to generate grpc code, which is no longer managed as a plugin to the `protoc-gen-go` binary, but rather is handled by a standalone `google.golang.org/grpc/cmd/protoc-gen-go-grpc` binary.

**Comment by dsnet** [comment] 2020-12-27 05:21
Closing as working as intended. The `google.golang.org/protobuf` module no longer maintains the `grpc` plugin. See https://github.com/grpc/grpc-go/tree/master/cmd/protoc-gen-go-grpc

**Closed by dsnet** 2020-12-27 05:21 UTC
