### ISSUE TITLE
Generated code with the new https://github.com/protocolbuffers/protobuf-go depends on the old packages

### ISSUE THREAD

**Issue by bogdandrutu** [golang/protobuf#1189] opened 2020-08-18 19:27 UTC
When I generate code using the new protoc-gen-go I get the following generated code. It seems strange to depend on the old "github.com/golang/protobuf/proto" just for the "ProtoPackageIsVersion4" constant:

```golang

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: proto/zipkin_proto3/zipkin.proto

import (
	proto "github.com/golang/protobuf/proto"
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4
```

Am I missing something?

**Comment by dsnet** [comment] 2020-08-18 19:36
Duplicate of #1077

**Closed by dsnet** 2020-08-18 19:36 UTC
