### ISSUE TITLE
protoc-gen-go can't produce embeddable code

### ISSUE THREAD

**Issue by haski** [golang/protobuf#1176] opened 2020-07-26 11:47 UTC
using protoc version 3.11.4 protoc-gen-go version 1.25.0

I have the following situation:
in a proto repo I have two proto files a.proto & b.proto. a.proto depends on b.proto .
a and b resides on different folders pkg1 & pkg2 respectively and both have a go_package directive respective of their folder,
so:
- a.proto has option go_package github.com/userX/proto-repo/pkg1;
- b.proto has option go_package github.com/userX/proto-repo/pkg2;

on a different repo (module name github.com/userX/serviceA) I'm trying compile the set of proto files mentioned above and embed them within serviceA. 
since they have a go_package pointing to a module with a different name there is no way to generate the files and make them compile within serviceA. 

I've tried with or without paths=source_relative and also tried the module argument as well as the -M argument per file but non of them succeeded in producing code that compiles. 
in-fact even without a specified go_package in the .proto files the protoc compiler is unable to produce code that compiles.

the main failure is in the import statements of the a.pb.go trying to import b.pb.go but using a wrong full package name. 
it seems that the code generator has no idea where the code will resides or what is the name of the module within it should be contained.
it would make sense to either derive the target module name(reading the go.mod of the module the go_out is pointing to) or to pass another argument specifying the target module name and fix the import statements accordingly.

in java(and other languages as well) we can easily embed generated code within another project since there is no inferred module name but in go this is not the case.

I consider it to be a bug and not a feature requires since it actually prohibit me from using protobuf with go.

**Comment by dsnet** [comment] 2020-07-27 18:42
> I'm trying compile the set of proto files mentioned above and embed them within serviceA.

Can you clarify what you mean by "embed"? Do you mean that you expect the `.pb.go` to be generated into some directory within the `github.com/userX/serviceA` module? If so, what not specify some package path that is rooted within the `github.com/userX/serviceA` module for the `go_package` option in `a.proto` and `b.proto`?

**Comment by haski** [comment] 2020-07-27 19:09
yes, embedding means generating the .pb.go files into some directory within some module like github.com.userX/serviceA.
specify that path using the go_package is not a viable option since I have multiple consumers using the same proto files, each resides in a different module.
in at some cases I don't even own the proto files, I might get them from a vendor (like google) so specifying the go_package on the proto files forces me to create a client lib separate from my code-base.
client lib can be very problematic since it becomes the source of truth instead of the .proto files and it also forces the client to import a specific version of the protobuf library so, for example, if I'm publishing a client lib using the old go protobuf lib my clients can't use the new one.
so, specifically in go, we have to have a way to choose the target module when compiling the code.

**Comment by neild** [comment] 2020-07-27 19:13
You can specify the import path when running `protoc` with `--go_opt=Mpath/to/foo.proto=example.com/import/path/of/package`, although note that you will get registration conflicts if you include two versions of the same source `.proto` file in the same binary.

**Comment by haski** [comment] 2020-07-27 19:26
doesn't work. if you're just using the M option you'll get a folder name github.com/userX/serviceA/... inside your project that already have a module name github.com/userX/serviceA so obviously the import of the dependent type fails completely.
if you try to use the paths=source_relative it simple puts the files in a wrong folder and the imports still fails.
there is no way to make it compile.

**Comment by neild** [comment] 2020-07-27 20:26
The `paths=source_relative` option controls the output filenames, not the import paths.

The proto compiler associates an import path with each `.proto` file. When `a.proto` imports `b.proto`, the import path is used to determine what (if any) `import` statement to put in `a.pb.go`. You can set the import paths with `go_package` options in the `.proto` files, or with `--go_opt=M<filename>=<import_path>` on the command line.

The proto compiler generates a `.pb.go` file for each `.proto` file. There are several ways in which the output directory may be determined. For example, if `source/a.proto` has an import path of `example.com/m/foo`:

1. `--go_opt=paths=import`: Import path; e.g., `example.com/m/foo/a.pb.go`
2. `--go_opt=paths=source_relative`: Source path; e.g., `source/a.pb.go`
3. `--go_opt=module=example.com/m`: Path relative to the `module` flag; e.g., `foo/a.pb.go`

In the worst case, if none of these suit your needs, you can always generate into a temporary directory and copy the file into the desired location. Neither the `paths` nor `module` flags have any effect on the contents of the generated files.

If you're still having difficulty, I'll need a concrete and complete example of what you're doing.

**Comment by haski** [comment] 2020-07-29 09:59
again - all of the above options doesn't work.
to demonstrate I've created two repos:

1. [https://github.com/haski/proto-repo ](url) a proto repository containing two proto files with inner dependency
2. [https://github.com/haski/ServiceX](url) a hosting repo meant to contain the compiled code from the proto-repo

the desired code is committed as well with a .nogo prefix for comparison purposes as well as a small sanity check inside main which is commented out.
if you can somehow produce these files using protoc I would be more than happy to close this issue, if not I think we're looking at a bug. deal ? ;)

**Comment by dsnet** [comment] 2020-08-01 21:00
I'm not sure I understand. The generated code is expected to end up in `github.com/haski/ServiceX`, but the `go_package` option specifies `github.com/haski/proto-repo/generated/base`. Why not specify `github.com/haski/ServiceX/generated/base` if that's where you want the generated `.pb.go` files to end up?

**Comment by haski** [comment] 2020-08-02 09:46
I have one proto repo (like this one: [](https://github.com/googleapis/googleapis) for example) and many consumer modules that need to use the compiled code. I can't specify the target module since I have many of those and I can't drop it all together since it's recommended to specify one and wither way the result is code that doesn't compile.

what I need is a way to specify to protoc a target module name that would be used to calculate the final package name.
in my case --module_name=github.com/haski/serviceX would cause the target package of the service.proto to become github.com/haski/ServiceX/generated/product and the base.proto package would become github.com/haski/ServiceX/generated/base

make sense ?

**Comment by dsnet** [comment] 2020-08-03 18:29
> I can't specify the target module since I have many of those and I can't drop it all together since it's recommended to specify one and either way the result is code that doesn't compile.

Why not? You should be able to specify the location of dependencies using the `-I` flags. The `.proto` files in `googleapias/googleapias` has the information for `protoc-gen-go` to know where to find the Go packages for these dependencies ([example](https://github.com/googleapis/googleapis/blob/868615a5c1c1059c636bb3d82a555edb1d5a251e/google/appengine/logging/v1/request_log.proto#L23)).

**Comment by dsnet** [comment] 2020-08-03 18:32
On a different note, our issue tracker is intended to track work that needs to be done. For questions that are better resolved through a series of back-and-forth questions and responses, this is [probably best asked on Slack](https://invite.slack.golangbridge.org/). There's a protobuf channel where similar questions are usually asked.

**Comment by haski** [comment] 2020-08-04 07:31
the -I flag is there to specify a proto root source directory. 
again - if you think there is ANY WAY in which I can use protoc to generate compilable code that can reside within the ServiceX module, do share!, if there isn't let's make it work.
I'm not asking a question, I'm pointing out a major conceptual bug that prevents my and my company to use protobuf. 
that's why I'm writing here and not in slack.

**Comment by dsnet** [comment] 2020-08-04 08:43
> The -I flag is there to specify a proto root source directory.

That is incorrect. The `-I` exist to tell `protoc` where to find dependencies. The proto root source directory is sometimes specified if you depend on well-known types.

> generate compilable code that can reside within the ServiceX module, do share!, if there isn't let's make it work.

If you want code to reside within the ServiceX module, then the `go_package` option should specify a Go package path that is within the ServiceX module. If you're trying to have a single .proto file generate to multiple identical Go packages in different places, then that is fundamentally a use-case not supported by the protobuf language.

>  I'm pointing out a major conceptual bug that prevents my and my company to use protobuf

Prototocol buffers are used by many companies for at least a decade. All the major use-cases are supported. If it isn't working then it's suggestive of either incorrect usage by the user or a use-case that does not fit within the protobuf language.

**Comment by haski** [comment] 2020-08-04 09:38
> If you're trying to have a single .proto file generate to multiple identical Go packages in different places, then that is fundamentally a use-case not supported by the protobuf language.

completely not true. I can do it in java, I compile the code and embed it within any java project inside its source code tree, no problem what so ever. the problem exists only in go since a single go module has a single module name that is the implicit root prefix of all packages within that module.  

that's why the protoc go plugin should behave a little different and allow to specify a target module name when compiling the proto files **for a specific module**

**Comment by dsnet** [comment] 2020-08-04 18:20
> completely not true. I can do it in java, ...

If so, then this is an artifact of the Java generator, and is not something that was intended to be a supported use case in the protocol buffer language. Much of protocol buffers assumes that a single (or concrete set of) .proto file(s) correlates to exactly to exactly one generated package in that language (whatever the equivalent of a Go package is in the target language). A one-to-many relationship causes problems with dependency resolution.

I'm going to close this is inactionable as it's not a use case that is in line with the overall vision of protocol buffers.

**Closed by dsnet** 2020-08-04 18:20 UTC
Labels: question
