### ISSUE TITLE
protoc - Go: Generated files still refer to `"github.com/golang/protobuf/proto"`

### ISSUE THREAD

**Issue by echarrod** [golang/protobuf#1170] opened 2020-07-14 09:46 UTC
I used protoc-3.12.3-win64.zip to generate files using the following command:
```bash
protoc --proto_path=proto/package_v1 -Iproto --go_out=build proto/package_v1/*
```

The generated files still have
```go
	proto "github.com/golang/protobuf/proto"
```
as an import in them.

I have removed all other references to `github.com/golang/protobuf/proto` in my repo after the deprecation notice, but these references mean my module still needs this import. Should the generator be updated to no longer require this?

I wouldn't have thought I should be having both `github.com/golang/protobuf/proto` and `google.golang.org/protobuf` as references in my `go.mod` file

**Comment by dsnet** [comment] 2020-07-14 17:06
Duplicate of #1077

**Closed by dsnet** 2020-07-14 17:06 UTC
