### ISSUE TITLE
Generated enum mapping to name should use enum type as key

### ISSUE THREAD

**Issue by tebeka** [golang/protobuf#756] opened 2018-11-18 09:41 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
`protoc` provides a maps to convert to/from string/enum value. However the map key are not the enum type but `int32`. This forces users to case the enum to `int32`.

In code:
```go
	dt := pb.DType_TIME

	// name := pb.DType_name[dt] // What I'd like to have
	name := pb.DType_name[int32(dt)] // What I need to do
	fmt.Println(name)
```
See full example [here](https://github.com/tebeka/protobuf-enum-go)

**Describe the solution you'd like**
The generated maps should be of type `map[<enum>]string` and not `map[int32]string`.

e.g instead of
```go
type DType int32
var DType_name = map[int32]string{
	0: "INTEGER",
	1: "FLOAT",
	2: "STRING",
	3: "TIME",
	4: "BOOLEAN",
}
```

It should be
```go
type DType int32
var DType_name = map[DType]string{
	0: "INTEGER",
	1: "FLOAT",
	2: "STRING",
	3: "TIME",
	4: "BOOLEAN",
}
```

**Describe alternatives you've considered**

None :) (other than casting every time)

**Additional context**

**Comment by dsnet** [comment] 2018-11-18 10:56
Closing as "working as intended" for the following reasons:
* Changing the type will break existing usages.
  * Code already depends on being able to retrieve an `int32` from the map
  * Also `map[MyEnum]string` and `map[int32]string` are invariant (not a sub-type other each other), so you would not be able to write a generic function handled all `map[E]string` types.
* The `map[int32]string` and `map[string]int32` variables exist because protobuf reflection does not. In v2, protobuf reflection is a first-class feature such that introspection into an enum can be done programatically. Ideally, these maps would eventually go away since they contain redundant information.

**Closed by dsnet** 2018-11-18 10:56 UTC

**Comment by dsnet** [comment] 2018-11-18 11:03
Also, why not just use the String method?

**Comment by tebeka** [comment] 2018-11-18 12:38
OK, understood. Thanks - will have a look at `String()`
