### ISSUE TITLE
protoc-gen-go: packages named 'type' induce a malformed warnings

### ISSUE THREAD

**Issue by anzboi** [golang/protobuf#1188] opened 2020-08-18 06:10 UTC
**What version of protobuf and what language are you using?**
Version: `v1.4.2`

**What did you do?**
Create a proto file with package `*.type` and go option `import/path/type`, then run protoc with `--go_out`

eg: 
```proto
// type.proto
syntax = 'proto3';

package my_package.type;

option go_package = "github.com/anzboi/my_package/type";

message Foo {
    string bar = 1;
}
```

Generate go code:
```sh
protoc -I . type.proto --go_out=.
```

**What did you expect to see?**

Successful code generation

**What did you see instead?**

Code is generated successfully but generates a warning repeated 3 times

```sh
$ protoc -I proto proto/type.proto --go_out=proto/gen
2020/08/18 16:04:44 WARNING: Malformed 'go_package' option in "type.proto", please specify:
        option go_package = "github.com/anzboi/my_package/type;_type";
A future release of protoc-gen-go will reject this.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2020/08/18 16:04:44 WARNING: Malformed 'go_package' option in "type.proto", please specify:
        option go_package = "github.com/anzboi/my_package/type;_type";
A future release of protoc-gen-go will reject this.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2020/08/18 16:04:44 WARNING: Malformed 'go_package' option in "type.proto", please specify:
        option go_package = "github.com/anzboi/my_package/type;_type";
A future release of protoc-gen-go will reject this.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
```

The warning tells you to add `;_type` to the option. Doing so results in more warnings, asking to add another underscore.

```sh
2020/08/18 16:06:54 WARNING: Malformed 'go_package' option in "type.proto", please specify:
        option go_package = "github.com/anzboi/my_package/type;__type";
A future release of protoc-gen-go will reject this.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2020/08/18 16:06:54 WARNING: Malformed 'go_package' option in "type.proto", please specify:
        option go_package = "github.com/anzboi/my_package/type;__type";
A future release of protoc-gen-go will reject this.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

2020/08/18 16:06:54 WARNING: Malformed 'go_package' option in "type.proto", please specify:
        option go_package = "github.com/anzboi/my_package/type;__type";
A future release of protoc-gen-go will reject this.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
```

**Anything else we should know about your project / environment?**

```sh
$ protoc --version
libprotoc 3.12.3
```

**Comment by tz70s** [comment] 2020-09-04 11:50
Hi I raised a CL trying to address this: https://go-review.googlesource.com/c/protobuf/+/252957

**Comment by Bobgy** [comment] 2020-12-24 12:12
I'm getting the same error. Is there any workaround before the CL is released?

Should I downgrade `protoc` or `protoc-gen-go`?
```
$ protoc --version
libprotoc 3.14.0
$ protoc-gen-go --version
protoc-gen-go v1.23.0
```

**Comment by puellanivis** [comment] 2020-12-26 14:53
Hm, it looks like the real problem is at: https://github.com/protocolbuffers/protobuf-go/blob/v1.25.0/internal/strs/strings.go#L84 where it checks if the first character is not a unicode letter, rather than “is neither a letter nor underscore”.

The Go specification specifically states underscore is to be considered a [`letter`](https://golang.org/ref/spec#letter) in the grammar of the language:
```
letter        = unicode_letter | "_" .
```

I’m not sure entirely sure what fixing this for package names would do to variable names, though.

**Comment by Bobgy** [comment] 2021-01-14 11:18
I later realized that, although this is annoying, it's not a blocking. I can still import the generated package via path and just ignore the package name.

**Comment by dsnet** [comment] 2021-03-16 18:59
Duplicate of #1276.

**Closed by dsnet** 2021-03-16 18:59 UTC
Labels: bug
