### ISSUE TITLE
Implement TextUnmarshaler for enum type defs

### ISSUE THREAD

**Issue by philikon** [golang/protobuf#947] opened 2019-09-16 19:08 UTC
Currently, the way to translate an enum value from string to the corresponding numeric value seems to be something like this:

```golang
	var enumval MyProtoEnum
	err := enumval.UnmarshalJSON([]byte(`"` + strval + `"`))
```

This is pretty cumbersome.

golang packages like [enumer](https://github.com/alvaroloes/enumer) provide the ability to convert enum values from string to numeric values by implementing the standard [TextUnmarshaler](https://golang.org/pkg/encoding/#TextUnmarshaler) interface. In fact, the JSON encoder/decoder will fall back to this interface if the [json.Unmarshaler](https://golang.org/pkg/encoding/json/#Unmarshaler) interface isn't implemented.

Is there any reason *not* to implement this interface for proto enums? I'd be happy to provide a PR.

**Comment by dsnet** [comment] 2019-09-16 19:15
Duplicate of #866

**Closed by dsnet** 2019-09-16 19:15 UTC
