### ISSUE TITLE
Deserializing nils for repeated oneof message

### ISSUE THREAD

**Issue by buckhx** [golang/protobuf#237] opened 2016-10-05 22:34 UTC
Deserialization from a different language with a repeated oneof renders nil objects

I have verified that this properly decodes in python, protoc, and using gogoproto.
I have not verified that serializing and deserializing using only golang/protobuf is broken.

Serializing the object renders nils instead of sections.

```
content:<sections:<> sections:<> sections:<> sections:<> >
```

Example proto definition follows:

```
syntax = "proto3";

package mypkg;
option go_package = "pbf";

import "google/protobuf/timestamp.proto";

message Post {
    uint32 id = 1;
    string title = 2;
    Content content = 3;
    google.protobuf.Timestamp created = 4;
}

message  Content {
    string description = 1;
    uint32 revision = 2;
    repeated Section sections  = 3;

    message Section {
        oneof block {
            Text text = 1;
            Image image = 2;
            Quote quote = 3;
        }
    }

    message Text {
        string body = 1;
    }

    message Image {
        string url = 1;
        string title = 2;
    }

    message Quote {
        string body = 1;
        string citation = 2;
    }
}
```

These aren't actual production definitions, but represent the issue at hand.

**Comment by hsaliak** [comment] 2017-05-17 23:12
@neild would you be able to help look into this?

**Comment by dsnet** [comment] 2017-05-18 23:48
I am confused by this bug report. What is the issue:
* Are we talking about text serialization or binary serialization? Without clarifying, the assumption is that you're talking about binary serialization, but the example you show is a text-serialized proto.
* You give this example: `content:<sections:<> sections:<> sections:<> sections:<> >`. Is this the output you get? What was the input?

**Comment by dsnet** [comment] 2017-05-18 23:59
This was my test case:
```go
	p := &Post{
		Content: &Content{
			Sections: []*Content_Section{
				{Block: &Content_Section_Text{Text: &Content_Text{Body: "body"}}},
				{Block: &Content_Section_Image{Image: &Content_Image{Title: "body"}}},
			},
		},
	}

	s := proto.MarshalTextString(p)
	fmt.Println(s)

	p2 := new(Post)
	if err := proto.UnmarshalText(s, p2); err != nil {
		panic(err)
	}
	fmt.Println(proto.MarshalTextString(p2))
```

It properly round-trips the one-of fields in text-serialization format. The output being:
```
content: <
  sections: <
    text: <
      body: "body"
    >
  >
  sections: <
    image: <
      title: "body"
    >
  >
>

content: <
  sections: <
    text: <
      body: "body"
    >
  >
  sections: <
    image: <
      title: "body"
    >
  >
>
```

I am unsure what the issue is. Please provide a reproduction in actual Go code.

**Comment by dsnet** [comment] 2018-02-14 00:25
Closing due to lack of traffic. Feel free to re-file with a reproduction.

**Closed by dsnet** 2018-02-14 00:25 UTC
Labels: WaitingForInfo
