### ISSUE TITLE
[perf]: Marshal and Unmarshal performance issues

### ISSUE THREAD

**Issue by songzhibin97** [golang/protobuf#1453] opened 2022-05-30 10:40 UTC
```go
package order

import (
	"encoding/json"
	"testing"
	"time"

	"github.com/golang/protobuf/proto"
	"google.golang.org/protobuf/encoding/protojson"
)

var (
	// MarshalOptions is a configurable JSON format marshaler.
	MarshalOptions = protojson.MarshalOptions{
		EmitUnpopulated: true,
	}
	// UnmarshalOptions is a configurable JSON format parser.
	UnmarshalOptions = protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}
)

var order = &Order{
	Id:        "101",
	Status:    "Created",
	CreatedOn: time.Now().Unix(),
	OrderItems: []*Order_OrderItem{
		&Order_OrderItem{
			Code:      "knd100",
			Name:      "Kindle Voyage",
			UnitPrice: 220,
			Quantity:  1,
		},
		&Order_OrderItem{

			Code:      "kc101",
			Name:      "Kindle Voyage SmartShell Case",
			UnitPrice: 10,
			Quantity:  2,
		},
	},
}

// Benchmark Proto3 Marshal
func BenchmarkOrderProto3Marshal(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_, err := proto.Marshal(order)
		if err != nil {
			b.Fatal("Marshaling error:", err)
		}
	}
}

// Benchmark JSON Marshal
func BenchmarkOrderJSONMarshal(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_, err := json.Marshal(order)
		if err != nil {
			b.Fatal("Marshaling error:", err)
		}
	}
}

// Benchmark JSON Marshal
func BenchmarkOrderJSONPBMarshal(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_, err := MarshalOptions.Marshal(order)
		if err != nil {
			b.Fatal("Marshaling error:", err)
		}
	}
}

// Benchmark Proto3 Unmarshal
func BenchmarkOrderProto3Unmarshal(b *testing.B) {
	data, err := proto.Marshal(order)
	if err != nil {
		b.Fatal("Marshaling error:", err)
	}
	for i := 0; i < b.N; i++ {
		var order Order
		err := proto.Unmarshal(data, &order)
		if err != nil {
			b.Fatal("Unmarshaling error:", err)
		}
	}
}

// Benchmark JSON Unmarshal
func BenchmarkOrderJSONUnmarshal(b *testing.B) {
	data, err := json.Marshal(order)
	if err != nil {
		b.Fatal("Marshaling error:", err)
	}
	for i := 0; i < b.N; i++ {
		var order Order
		err := json.Unmarshal(data, &order)
		if err != nil {
			b.Fatal("Unmarshaling error:", err)
		}
	}
}

func BenchmarkOrderJSONPBUnmarshal(b *testing.B) {
	data, err := MarshalOptions.Marshal(order)
	if err != nil {
		b.Fatal("Marshaling error:", err)
	}
	for i := 0; i < b.N; i++ {
		var order Order
		err := UnmarshalOptions.Unmarshal(data, &order)
		if err != nil {
			b.Fatal("Unmarshaling error:", err)
		}
	}
}
```

![image](https://user-images.githubusercontent.com/49082129/170974842-b07523db-97e7-450a-88b6-af5a52a95cbe.png)

The performance of using `protojson` is very low. In each message, you need to nest for, for, for for sorting and append. Is there an optimization plan?

**Comment by puellanivis** [comment] 2022-05-30 10:45
Duplicate of #1285

**Comment by songzhibin97** [comment] 2022-05-31 02:23
oh,It's a little different.
I'm using the latest version.
```
	github.com/golang/protobuf v1.5.0
	google.golang.org/protobuf v1.28.0
```
![image](https://user-images.githubusercontent.com/49082129/171079985-dfb8bf0c-b271-45f8-b93c-9aa854fd2e15.png)

**Comment by dsnet** [comment] 2022-05-31 02:39
I'd still say it's a duplicate of #1285.

**Closed by dsnet** 2022-05-31 02:39 UTC
