### ISSUE TITLE
Only Messages can be encoded or decoded from json

### ISSUE THREAD

**Issue by Zemnmez** [golang/protobuf#949] opened 2019-09-17 15:00 UTC
**What version of protobuf and what language are you using?**
Version: 822fe56

**What did you do?**
Tried to encode an enum value as json

**What did you expect to see?**
The value encoded as string, [as per the spec](https://developers.google.com/protocol-buffers/docs/proto3#json)

**What did you see instead?**

An error. [jsonpb only accepts *proto.Message](https://godoc.org/github.com/golang/protobuf/jsonpb#Marshaler.Marshal)

**Comment by dsnet** [comment] 2019-09-17 16:09
How did you get an error? An enum doesn't satisfy the `Message` interface, so I'm not sure how you were able to call `jsonpb.Marshaler.Marshal` with it.

Steeping back a bit, the protobuf language is only really designed around messages as a first-class types. Enums are just types that are only useful when used within a message. Thus, there is no support for directly marshaling/unmarshaling enums. This is a property of protobuf language, which we are not responsible for. Closing this as "working as intended".

**Closed by dsnet** 2019-09-17 16:09 UTC

**Comment by Zemnmez** [comment] 2019-10-04 23:44
@dsnet This is a compiler error, not a runtime error. Also, this is **not** "working as intended". I linked the actual specification, which disagrees with this. Doesn't seem like I can re-open so I guess I'll make a new ticket if this isn't re-opened in a few days

**Comment by dsnet** [comment] 2019-10-04 23:47
It is a compilation error precisely because the type system won't let you do something that the protobuf language does not permit. This is working as intended.

**Comment by Zemnmez** [comment] 2019-10-06 01:14
![image](https://user-images.githubusercontent.com/4625198/66262724-1d5b9880-e79b-11e9-9263-c1fa736bd0a0.png)

Perhaps this is just an issue with the way this page is written, but I can't find anything indicating that jsonpb representations are only valid for `Message`s. The document itself says the encoding is described on a "type-by-type basis".

**Comment by puellanivis** [comment] 2019-10-06 20:46
This is kind of an in-built semantic of protobufs themselves. Nothing in protobufs really makes any sense outside of a message. You cannot really encode a single field of a protobuf in wire format without encapsulating it within a message. As a result, this semantic follows through to JSON encoding, even though various fields could be encoded in JSON independently.

In the end, the semantic must remain isolated to those of protobufs, and not broadened overwidely into generic JSON formatting.

**Comment by Zemnmez** [comment] 2019-10-06 20:49
I see. I guess I misunderstood from the spec I linked which seemed to read to me that individual types have their own representations, even if they don't in the same way as a Message.
