### ISSUE TITLE
protoc-gen-go --version

### ISSUE THREAD

**Issue by stevenroose** [golang/protobuf#598] opened 2018-05-10 16:19 UTC
For a lot of projects, especially open-source ones, you want all contributors to use the same version of all the protobuf (and grpc) tools. Otherwise pull requests for small changes in proto files could potentially have huge changes in generated code if the contributor has a different version.

A good solution for this, is to provide a generation script within the project that contributors should use to generate the code. In this script, the version of the tools can be checked.

Currently, `protoc --version` gives you the version of protoc. It would be nice if `protoc-gen-go` could also somehow expose its version through a command. Preferably the same as protoc.

**Comment by dsnet** [comment] 2018-05-10 17:59
Closing as duplicate of #524.

**Closed by dsnet** 2018-05-10 17:59 UTC
