### ISSUE TITLE
Timestamp proper use with timestamp postgres

### ISSUE THREAD

**Issue by Kiura** [golang/protobuf#301] opened 2017-03-06 22:41 UTC
Hello!
There is no documentation regarding usage of Timestamp WKT (at least I couldn't find any after 4-5 hours of searching). 

Here is my proto file (part of it):

```proto
syntax = "proto3";
option go_package = "models";
import "google/protobuf/timestamp.proto";

message User {
	...
	google.protobuf.Timestamp created_at = 9;
}
```

I believe I can use `github.com/golang/protobuf/ptypes/timestamp` to create `Timestamp`, but how do I actually save it to the database and how to retrieve `timestampz` from database? 

when I try to retrieve `timestampz` I get this error: `invalid character '-' after top-level value` (json package)

only solutions I can think of: 
1) use temp struct to decode from database and convert it to the one created from proto and vice versa
2) use epoch time in struct as int64 or string? and select from DB 
```sql
SELECT EXTRACT(epoch FROM created_at) AS created_at FROM users WHERE id=1;
```

using `pg.v5` as a driver for postgres (any driver could be used, but this one is preferred).

P.S. have been trying to use protobuf for projects for a long time, but every time I try to set up a project I face some unsolvable problems.

**Comment by shilov** [comment] 2017-03-07 04:50
Is `gogo` an option for you? gogoproto has an extension to use standard time. My proto definition looks like this:

    google.protobuf.Timestamp updated = 4 [(gogoproto.stdtime) = true];

**Comment by Kiura** [comment] 2017-03-07 11:11
@shilov, thx for quick reply )
Gonna give it a try (however, personally I like to use official packages and its a shame that it is not supported officially).

**Comment by Xopherus** [comment] 2017-03-17 01:49
i'm not sure this a problem with protobuf. if you need a timestamp in a particular format for your database schema then it's on you to write that conversion. 

converting `google.protobuf.Timestamp` to epoch seconds is fairly easy though: https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto#L101

**Comment by cybrcodr** [comment] 2017-05-18 23:04
I'm not clear whether the issue is on how to convert between Timestamp proto and time.Time or how to store in database.  For the latter, it really depends on whether you want to serialize the proto or simply just store time directly in a particular database field type.  I'd imagine if time is the only value for that field, then it doesn't make sense to serialize/deserialize into/from proto.

As for converting between Timestamp proto and time.Time, check out package [github.com/golang/protobuf/ptypes](https://godoc.org/github.com/golang/protobuf/ptypes), there's ptype.TimeStamp and ptype.TimeStampProto.

Closing this issue, but feel free to reopen if not resolved.

**Closed by cybrcodr** 2017-05-18 23:04 UTC
