### ISSUE TITLE
Unable to unmarshal a nested struct: Unexpected EOF

### ISSUE THREAD

**Issue by thatjames** [golang/protobuf#1047] opened 2020-02-27 13:03 UTC
**What version of protobuf and what language are you using?**
Version: proto3 revision d23c5127 on golang

**What did you do?**
Attempted to unmarshal provided bytes

**What did you expect to see?**
Successful unmarshal

**What did you see instead?**
Unexpected EOF

Simple POC
```
syntax = "proto3";
package agic;
message AgicBase {
    string Memloc = 1;
    string SystemSerialNumber = 2;
    string AuditEntry = 3;
    string AuditTrailReference = 4;
    bytes OriginalData = 5;
}
message FormatCBase {
    AgicBase AgicBase = 1;
    string DateTime = 2;
    string UserIndex = 3;
}
message FormatC {
    FormatCBase FormatCBase = 1;
    string TellerIndex = 2;
    string MenuIndex = 3; //Menu Index
    string SystemSerialNumber = 4;
    string TransactionNumber = 5;
}

dat := []byte{10, 81, 10, 6, 48, 50, 48, 49, 67, 48, 18, 8, 57, 56, 52, 51, 48, 51, 55, 53, 26, 2, 57, 48, 34, 2, 69, 53, 42, 53, 48, 50, 48, 49, 67, 48, 57, 56, 52, 51, 48, 51, 55, 53, 69, 53, 57, 48, 48, 50, 49, 53, 51, 49, 52, 53, 69, 54, 48, 48, 48, 51, 48, 49, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 51, 52, 48, 57, 55, 65, 13, 18, 19, 50, 48, 49, 57, 45, 48, 56, 45, 48, 50, 32, 49, 53, 58, 51, 56, 58, 48, 56, 26, 2, 69, 54, 34, 2, 48, 48, 42, 2, 48, 51, 50, 2, 48, 49, 58, 2, 48, 48}
var msg agic.FormatC
    if err := proto.Unmarshal(dat, &msg); err != nil { //Error: Unexpected EOF
        fmt.Println(err.Error())
    return
}

```

Working example with a different message type and less nesting
```
syntax = "proto3";
package agic;


message AgicBase {
    string Memloc = 1;
    string SystemSerialNumber = 2;
    string AuditEntry = 3;
    string AuditTrailReference = 4;
    bytes OriginalData = 5;
}
message FormatD {
    AgicBase AgicBase = 1;
    string DateTime = 2;
    string UserIndex = 3;
    string TelliIndex = 4;
    string MenuIndex = 5;
    string MenuOptionNumber = 6;
    string UserTellerLockNumberModified = 7;
}


dat := []byte{10, 81, 10, 6, 48, 50, 48, 48, 50, 48, 18, 8, 57, 56, 52, 51, 48, 51, 55, 53, 26, 2, 56, 69, 34, 2, 69, 53, 42, 53, 48, 50, 48, 48, 50, 48, 57, 56, 52, 51, 48, 51, 55, 53, 69, 53, 56, 69, 48, 50, 49, 53, 51, 56, 48, 56, 70, 57, 48, 48, 48, 48, 48, 48, 48, 69, 52, 53, 54, 55, 56, 48, 48, 48, 53, 50, 55, 54, 48, 57, 48, 65, 13, 18, 19, 50, 48, 49, 57, 45, 48, 56, 45, 48, 50, 32, 49, 53, 58, 51, 56, 58, 48, 56, 26, 2, 70, 57, 34, 2, 48, 48, 42, 2, 48, 48, 69, 14, 0, 0, 0, 74, 10, 13, 4, 0, 0, 0, 21, 10, 0, 0, 0, 74, 10, 13, 5, 0, 0, 0, 21, 20, 0, 0, 0, 74, 10, 13, 6, 0, 0, 0, 21, 50, 0, 0, 0, 74, 10, 13, 7, 0, 0, 0, 21, 100, 0, 0, 0, 74, 10, 13, 8, 0, 0, 0, 21, 200, 0, 0, 0, 74, 0, 74, 0, 74, 0, 82, 2, 53, 50}
var msg agic.FormatD
    if err := proto.Unmarshal(dat, &msg); err != nil {
        fmt.Println(err.Error())
        return
    }
fmt.Printf("%+v\n", msg)
```

**Anything else we should know about your project / environment?**
Flattening the struct to not be nested resolves the problem, but to me this breaks the composition support of Protobuf, unless I've misunderstood that

**Comment by dsnet** [comment] 2020-02-27 16:58
Hi @thatjames, thanks for the bug report and succinct reproduction.

The [v2 pre-release has a `pbdump` tool](https://pkg.go.dev/google.golang.org/protobuf/internal/cmd/pbdump) that is useful for diagnosing issues with the binary format. Using the tool produces a syntax tree for the wire format that looks something like: 
```
$ echo 0a510a06303230314330120839383433303337351a023930220245352a35303230314330393834333033373545353930303231353331343545363030303330313030303030303030303030303334303937410d1213323031392d30382d30322031353a33383a30381a024536220230302a023033320230313a023030 | xxd -r -p | pbdump -messages 1.1
Message{
	Tag{1, Bytes}, LengthPrefix(Message{
		Tag{1, Bytes}, LengthPrefix(Message{
			Tag{6, Varint}, Uvarint(50),
			Tag{6, Varint}, Uvarint(49),
			Tag{8, StartGroup},
			Message{
				Tag{6, Varint},
				Raw(""),
			},
		}),
		Tag{2, Bytes}, Bytes("98430375"),
		Tag{3, Bytes}, Bytes("90"),
		Tag{4, Bytes}, Bytes("E5"),
		Tag{5, Bytes}, Bytes("0201C098430375E59002153145E600030100000000000034097A\r"),
	}),
	Tag{2, Bytes}, Bytes("2019-08-02 15:38:08"),
	Tag{3, Bytes}, Bytes("E6"),
	Tag{4, Bytes}, Bytes("00"),
	Tag{5, Bytes}, Bytes("03"),
	Tag{6, Bytes}, Bytes("01"),
	Tag{7, Bytes}, Bytes("00"),
}
```
You'll notice within the nested message, there is a `Tag{8, StartGroup}`, followed by a `Message{..., Raw("")}`. The existence of `Raw` token is emitted by `pbdump` when the input the lexicographically unparsable. It seems that this binary data has a start-group without an end-group marker. As such, encountering an `io.ErrUnexpectedEOF` is an entirely expected outcome. 

How was this data produced?

**Comment by neild** [comment] 2020-02-27 16:59
Where are you getting the input data from? It's invalid for the message you're decoding it into.

```shell
$ pbdump -messages=1 < /tmp/data
Message{
        Tag{1, Bytes}, LengthPrefix(Message{
                Tag{1, Bytes}, Bytes("0201C0"),
                Tag{2, Bytes}, Bytes("98430375"),
                Tag{3, Bytes}, Bytes("90"),
                Tag{4, Bytes}, Bytes("E5"),
                Tag{5, Bytes}, Bytes("0201C098430375E59002153145E600030100000000000034097A\r"),
        }),
        Tag{2, Bytes}, Bytes("2019-08-02 15:38:08"),
        Tag{3, Bytes}, Bytes("E6"),
        Tag{4, Bytes}, Bytes("00"),
        Tag{5, Bytes}, Bytes("03"),
        Tag{6, Bytes}, Bytes("01"),
        Tag{7, Bytes}, Bytes("00"),
}
```

The data contains fields with numbers 1-7, with field 1 looking like it's probably a message. If field 1 is a message, it contains fields with numbers 1-5, none of them something that can be interpreted as a message.

This fails to decode because your message definitions say that field 1.1 should be a message, but the data in it can't be interpreted as one. It has various other differences from the definition.

It looks to me like your input data is for some entirely different message type than you're decoding it into.

**Comment by thatjames** [comment] 2020-02-27 21:37
Hi @dsnet.

The message is dumped raw from the transport layer (nats.io in this case). They come from an ARM processor, also golang. Generated via proto.Marshal on the client end.

I tried my damndest to replicate this with a simple test case that marshalled and unmarshalled the struct, but no dice. 

These messages are marshalled into a final envelope and sent as bytes (also protobuf) upstream where they are decoded. We've been using this approach for a while with no pain, but noticed we struggled on messages with that many layers of wrapping, so given your explanation I can see how unwrapping these messages from each other resolved the issue.

Where I'm lost is how this happened. I'm a little green with debugging protobuf so forgive my naive questions, but could this be caused by a truncation issue of the raw bytes passed through?

It's nearly midnight this side of the world for me, but I'll provide the message structure for the envelope we use and a more useful layout of the topology soon as I can

**Comment by dsnet** [comment] 2020-02-27 21:39
> could this be caused by a truncation issue of the raw bytes passed through?

It seems unlikely. What seems more likely is that the sender is serializing a protobuf message of one specific message type, while the receiver is deserializing the message into another message of a different type. The protobuf wire format has no magic numbers to check that the wire data is being unmarshaled into a message of the right type.

**Comment by thatjames** [comment] 2020-02-27 21:48
@dsnet hmm, so potentially a PICNIC issue then 🙄 I'll have a comb through the client again and have a look at what's cracking. I could've potentially grabbed the wrong data dump here, but given your points and what @neild said, I wonder if the act of unraveling the messages stuck the right message in the right place.

Happy to park this and re-open if I can replicate it (whilst also being 100% certain of the message types)

**Comment by dsnet** [comment] 2020-02-27 21:49
> I wonder if the act of unraveling the messages stuck the right message in the right place.

Certainly seems suspect. I hope our responses helped.

I'll close this for now. Feel free to re-open or create a new issue if evidence points to a problem in the protobuf module.

**Closed by dsnet** 2020-02-27 21:49 UTC
Labels: waiting-for-info

**Comment by neild** [comment] 2020-02-27 22:13
Note that because the protobuf wire format contains very little internal validation, it's incredibly easy to marshal one message type to binary data, unmarshal that data into a completely different message type, and have no errors turn up. (The unmarshaled message will contain garbage, of course.)
