### ISSUE TITLE
encoding/protojson: Well-Known Type parser not used if MarshalOptions.Resolver is set

### ISSUE THREAD

**Issue by bufdev** [golang/protobuf#1196] opened 2020-09-01 17:22 UTC
I am not sure if this may be expected behaviour, but roughly, here's the issue:

- Set a custom `protojson.MarshalOptions.Resolver` that was created using dynamically-created `FileDescriptorProtos` that does not include the Well-Known Types. This means that `protoregistry.GlobalTypes` is no longer used.
- Try to Unmarshal a `google.protobuf.Any` object that has a well-known type URL, i.e. `google.protobuf.BoolValue`, `anything/path/to/google.protobuf.BoolValue`, etc (I believe that anything except the last part of the path doesn't matter for WKTs with golang/protobuf)

This will fail with a `NotFound` error.

The answer might be that this is expected, as if you override the `Resolver`, you should be expected to include the Well-Known Types, however since the WKT type URLs aren't actually valid per the https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/any.proto spec (they are just "well-known type URLs as https://developers.google.com/protocol-buffers/docs/proto3#json references), I'd argue that the marshaler/unmarshaler should handle them regardless.

The situation gets weird if you have a custom `google.protobuf.Any` option, for example:

```proto
syntax = "proto2";

package foo.v1;

import "google/protobuf/descriptor.proto";
import "google/protobuf/any.proto";

extend google.protobuf.FieldOptions {
  optional google.protobuf.Any any = 65515;
}
```

And then you try to set this:

```proto
syntax = "proto3";

package bar.v1;

import "foo/v1/opt.proto";

message Asset {
  string name = 1 [
    (foo.v1.any) = { type_url: "google.protobuf.Duration", value: "2s" }
  ];
}
```

And you try to use json Marshal using the `FileDescriptorSet` created from these two files + descriptor.proto and any.proto, it will fail with a `NotFound` error, however, if you add the import:

```proto
syntax = "proto3";

package bar.v1;

import "foo/v1/opt.proto";
import "google/protobuf/duration.proto";

message Asset {
  string name = 1 [
    (foo.v1.any) = { type_url: "google.protobuf.Duration", value: "2s" }
  ];
}
```

Then it will not fail, although this then results in an unused import error with `protoc` as `google/protobuf/duration.proto` is not actually used.

Given that the WKT type URLs are quasi-type-URLs, it might be good to have the json marshaler/unmarshaler fall back specifically for WKT type URLs if a custom `Resolver` returns a `NotFound` error.

**Comment by neild** [comment] 2020-09-01 21:13
One point to consider is that `protojson` currently doesn't have a dependency on any message types. Making this change would introduce one. We wouldn't be able to make the equivalent change to `proto.Unmarshal` without creating an import cycle.

**Comment by cybrcodr** [comment] 2020-09-01 21:16
It is by design that if user sets `protojson.MarshalOptions.Resolver`, the custom resolver should handle all type resolution.  The custom resolver can by itself fallback to using `protoregistry.GlobalTypes`.  This allows for better flexibility.  This is not just for well-known types but true for all types.

**Comment by bufdev** [comment] 2020-09-01 21:33
The issue is that `GlobalTypes` doesn't just include the Well-Known Types, it may include other items, and that the Well-Known Types are special with regards to JSON, as the Protobuf JSON specification says they need be handled differently, otherwise an encoding of a Protobuf message is not valid. So it's possible for JSON marshal to produce an invalid marshalling of a message depending on the value of a `Resolver`

**Comment by cybrcodr** [comment] 2020-09-01 21:56
If the custom resolver returns the `protoreflect.MessageType` for a well-known type, `protojson` will do the proper encoding for that well-known type based on the proto JSON spec.  The custom resolver is meant to produce a `MessageType` that may not typically be registered in the global registry, and these can include well-known types if those are not imported.

If you know that well-known types (or specific ones) are imported and registered in the global registry, you can have your custom resolver use the global registry for those and should be able to special case such fallback to only ones that you want based on their `protoreflect.FullName`.

**Comment by bufdev** [comment] 2020-09-01 21:58
We can handle this of course, this just did seem like it could be an issue for all users of custom resolvers with golang/protobuf, and if the API allows invalid behavior, it would be good to provide this to the user of the API (or perhaps at least document it). Even better would be this "fallback WKT Resolver" being provided by golang/protobuf itself, for reuse. Understood either way.

**Comment by cybrcodr** [comment] 2020-09-01 22:29
The v1 version `github.com/golang/protobuf/jsonpb.Marshaler.AnyResolver` has similar logic.

I can understand your request, but it's a trade-off that we made in favor of flexibility in resolving all message types including well-known types and hence also not relying on the global registry to always contain all well-known types unnecessarily.

**Comment by dsnet** [comment] 2020-09-01 23:00
I think the issue the relationship between a global resolver and a custom resolver to be somewhat of a red herring.

[After all this code](https://play.golang.org/p/6c293mdIWso):
```go
m := &anypb.Any{
	TypeUrl: "type.googleapis.com/google.protobuf.Timestamp",
	Value: protopack.Message{
		protopack.Tag{1, protopack.VarintType}, protopack.Varint(1599000711),
		protopack.Tag{2, protopack.VarintType}, protopack.Varint(166067539),
	}.Marshal(),
}
b, err := protojson.Marshal(m)
fmt.Println(string(b), err)
```
fails with:
```
 proto: google.protobuf.Any: unable to resolve "type.googleapis.com/google.protobuf.Timestamp": not found
```
assuming that `timestamppb` is not linked in.

The question at hand is whether `protojson` should have implicit knowledge of the WKTs for dynamic purposes or not. Either:
1) `protojson` has a dependency on every WKT as @neild alluded to (and the associated import-cycle problems), or
2) `protojson` has a local copy the descriptor of every WKT and uses it with `dynamicpb` to create a dynamic version of every WKT.

Neither approach seems particularly palatable for this edge-case.

**Comment by dsnet** [comment] 2021-03-16 19:13
I'm thinking of closing this as inactionable. In my last comment, I presented two options:

1. `protojson` has a dependency on every WKT as @neild alluded to (and the associated import-cycle problems), or
2. `protojson` has a local copy the descriptor of every WKT and uses it with dynamicpb to create a dynamic version of every WKT (if it isn't found by the resolver).

Unless there is an option I'm missing, both cases don't seem particularly appetizing. We'll probably leave the current behavior as is.

**Comment by dsnet** [comment] 2021-03-29 21:06
Closing as inactionable (and unfortunate).

**Closed by dsnet** 2021-03-29 21:06 UTC
