### ISSUE TITLE
jsonpb: allows bytes-valued map values to be nil

### ISSUE THREAD

**Issue by shahms** [golang/protobuf#1006] opened 2020-01-06 17:11 UTC
**What version of protobuf and what language are you using?**
Version: v1.3.2

**What did you do?**
Given the protobuf definition:
```
message MapTest {
  map<string, bytes> byte_map = 1;
  map<string, string> string_map = 2;
}
```
And the code snippet:
```
func main() {
	marshaler := jsonpb.Marshaler{}
	text, err := marshaler.MarshalToString(&MapTest{
		ByteMap:   map[string][]byte{"nil": nil, "empty": []byte{}},
		StringMap: map[string]string{"key": ""},
	})
	if err != nil {
		panic(err)
	}
	fmt.Println(text)
}
```

**What did you expect to see?**
`{"byteMap":{"empty":"","nil":""},"stringMap":{"key":""}}`

**What did you see instead?**
`{"byteMap":{"empty":"","nil":null},"stringMap":{"key":""}}`

(Note in particular the nil-valued byte slice is mapped to JSON `null`, which is invalid in maps).

**Comment by dsnet** [comment] 2020-01-06 17:22
This is a bug, and I believe is fixed in the v2 implementation. \cc @cybrcodr to verify.

**Comment by cybrcodr** [comment] 2020-01-07 05:39
Yes, V2 will produce the posted expected value `{"byteMap":{"empty":"","nil":""},"stringMap":{"key":""}}`.

Do we close this as fixed in V2 as I don't think we have plans to fix V1?

**Comment by puellanivis** [comment] 2020-01-07 13:36
I think that is the working mode for things for now. Unless this is clearly a critical bug issue.

**Comment by dsnet** [comment] 2020-01-07 16:51
Since this isn't a regression nor a critical bug. I'm inclined to say that we avoid investing time on v1 and instead do what's necessary to get v2 out the door.

**Comment by dsnet** [comment] 2020-03-03 06:41
The new [`protojson`](import "google.golang.org/protobuf/encoding/protojson") package addresses this issue and has been released as part of [`google.golang.org/protobuf@v1.20.0`](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0).

**Closed by dsnet** 2020-03-03 06:41 UTC
Labels: bug, pending-v2
