### ISSUE TITLE
How to serialize only picked fields in golang?

### ISSUE THREAD

**Issue by piratf** [golang/protobuf#1304] opened 2021-03-24 07:39 UTC
Example message:
``` protobuf
message Example{
  int32 ID = 1; // Want
  int32 SplitKey = 2; // Want
  string Data = 3;
  BigStruct OtherData = 4;
}
```

Fields 1 and 2 are the keys to locate this message, I need the serialized data of only these two fields.

Knowing plan in C++:
I can use `WireFormat::SerializeFieldWithCachedSizes` to serialize only the fields I need, then put them together.

Questing: How to get serialized data only including fields 1 and 2 in golang?

**Comment by piratf** [comment] 2021-03-24 08:00
The method currently in mind:
1. Use `protoreflect New()` to create a new empty message `Key`.
2. Use `protoreflect Range()` to traversal all fields in the old one, if it's the field I want, copy to `Key`.
3. use `proto Marshal()` to marshal the new message `Key`.

Looks a bit wasteful, any better suggestions?

**Comment by puellanivis** [comment] 2021-03-24 09:47
There is not any intentional way to serialize only a single field. I believe the semantic here is intended to be covered by [FieldMask](https://pkg.go.dev/google.golang.org/protobuf/types/known/fieldmaskpb#FieldMask).

**Comment by dsnet** [comment] 2021-03-24 18:40
Closing this as a duplicate of #1183, which is about supporting `FieldMask` with serialization.

**Closed by dsnet** 2021-03-24 18:40 UTC
