### ISSUE TITLE
Cannot use 'ms' (type *messageState) as the type protoreflect.Message

### ISSUE THREAD

**Issue by daleangus** [golang/protobuf#1397] opened 2021-12-17 00:26 UTC
protoc --version
libprotoc 3.19.1

go version
go version go1.17.3 darwin/amd64

I compiled a proto file to output for Go

In my GoLand IDE, I see this message highlighed for `ms` in `return ms`

`Cannot use 'ms' (type *messageState) as the type protoreflect.Message Type does not implement 'protoreflect.Message' need the method: ProtoMethods() *methods have the method: ProtoMethods() *protoiface.Methods`

in the function

```
func (x *EventItemMetricsProtobuf) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
```

My app can still use the *.pg.go files without issues, so far.

**Comment by neild** [comment] 2021-12-17 06:41
Duplicate of #1393.

This is a GoLand bug:
https://youtrack.jetbrains.com/issue/GO-12060

**Closed by neild** 2021-12-17 06:41 UTC
