### ISSUE TITLE
Structpb: Consideration for supporting time or timestamp types

### ISSUE THREAD

**Issue by shan98** [golang/protobuf#1178] opened 2020-07-29 19:34 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to use structpb for timestamp types. 

**Describe the solution you'd like**
Probably just have timestamp as one of the Value_X types

**Describe alternatives you've considered**
Having a nested struct with second and nano int fields, but this means i would need to reserve field names to be treated as a special case so that i know to convert them to time fields. This isn't ideal. It also adds an extra burden on clients to conform to this format, without a proper struct to follow.

**Comment by dsnet** [comment] 2020-07-29 23:05
The `structpb` package is intended to dynamically represent arbitrary JSON. I'm not sure how you expect the package to handle timestamps.

**Comment by shan98** [comment] 2020-07-30 14:45
Oh i see. I am using it for sending update requests on a resource. We thought of a bunch of different ways to do it but we had settled on wanting to use a map for the fields you want updated. Trying to use the Any object (map<string, Any>) seemed very confusing to use with the type url, so i thought structpb might be a good alternative. 

We use generated clients on our frontend, so JSON isn't the biggest concern, although still is one.

But ya i guess if this is purely for JSON than timestamps dont make sense really.

**Comment by dsnet** [comment] 2020-07-30 16:31
> But ya i guess if this is purely for JSON than timestamps dont make sense really.

Got. I'll close this as working as intended, then.

**Closed by dsnet** 2020-07-30 16:31 UTC
Labels: waiting-for-info

**Comment by cybrcodr** [comment] 2020-07-30 18:05
Use of protobuf is generally for more structured messages.  So, for sending update requests on a resource, you may want to define the fields that make up that type of request.  And if timestamp is one of those, then define a Timestamp field for it.
