### ISSUE TITLE
generated pb.go file imports deprecated github.com/golang/protobuf/proto

### ISSUE THREAD

**Issue by sbezverk** [golang/protobuf#1124] opened 2020-05-11 15:49 UTC
After compiling proto definition, the resulting pb.go file has import statement for  `github.com/golang/protobuf/proto`. It cause staticcheck error.

```
api/attribute.pb.go:8:2: package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (SA1019)
```
I would like to know if there is a way to force the code generator to use new `google.golang.org/protobuf/proto` package in resulting pb.go import.

**Comment by dsnet** [comment] 2020-05-11 17:32
Duplicate of #1077. There are technical reasons why we need to keep generating this reference. Please update `staticcheck` past https://github.com/dominikh/go-tools/commit/7e758a3887f90d0ded5f0446112616758183866b

**Closed by dsnet** 2020-05-11 17:32 UTC
