### ISSUE TITLE
Panic: nil pointer dereference 

### ISSUE THREAD

**Issue by IIvyPy** [golang/protobuf#1319] opened 2021-05-11 07:25 UTC
hi， Here is my stack error log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x472f67]

goroutine 109 [running]:
google.golang.org/protobuf/encoding/protowire.AppendString(...)
	/go/src/github.com/coredns/coredns/vendor/google.golang.org/protobuf/encoding/protowire/wire.go:450
google.golang.org/protobuf/internal/impl.appendStringNoZeroValidateUTF8(0xc03ca7d0e0, 0x105, 0x105, 0xc00078c408, 0xc019e65a90, 0xc006784002, 0xc03ca7d0e0, 0xeb, 0x105, 0x0, ...)
	/go/src/github.com/coredns/coredns/vendor/google.golang.org/protobuf/internal/impl/codec_gen.go:5026 +0xf0
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer(0xc00023b900, 0xc03ca7d0e0, 0x0, 0x105, 0xc00078c240, 0xc017c1ac02, 0xc121c63c68, 0x959d50, 0xc00023b900, 0x10000c00078c240, ...)
	/go/src/github.com/coredns/coredns/vendor/google.golang.org/protobuf/internal/impl/encode.go:138 +0x10a
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshal(0xc00023b900, 0x1254330, 0xc0f1229910, 0xc03ca7d0e0, 0x0, 0x105, 0x2, 0x450c6c, 0x105, 0xf0c6a0, ...)
	/go/src/github.com/coredns/coredns/vendor/google.golang.org/protobuf/internal/impl/encode.go:106 +0x8d
google.golang.org/protobuf/proto.MarshalOptions.marshal(0xc0f1000001, 0x0, 0x0, 0x0, 0x1254330, 0xc0f1229910, 0xc0f1229910, 0x1254330, 0xc0f1229910, 0x10c8a80, ...)
	/go/src/github.com/coredns/coredns/vendor/google.golang.org/protobuf/proto/encode.go:166 +0x25e
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend(0x1000001, 0x0, 0x0, 0x0, 0x122b220, 0xc0f1229910, 0x0, 0x8000103, 0x0, 0xffffffffffffffff, ...)
	/go/src/github.com/coredns/coredns/vendor/google.golang.org/protobuf/proto/encode.go:125 +0x98
github.com/golang/protobuf/proto.marshalAppend(0x0, 0x0, 0x0, 0x123c3a8, 0xc00078c240, 0x406700, 0xc000132898, 0xc000434840, 0xc000434840, 0x0, ...)
	/go/src/github.com/coredns/coredns/vendor/github.com/golang/protobuf/proto/wire.go:40 +0xdc
github.com/golang/protobuf/proto.Marshal(...)
	/go/src/github.com/coredns/coredns/vendor/github.com/golang/protobuf/proto/wire.go:23
github.com/coredns/coredns/plugin/output_360.(*Output).handleDNSMessage(0xc00035a000, 0xc15ab31ce0, 0xc05c01a630, 0xc05c01a870)
	/go/src/github.com/coredns/coredns/plugin/output_360/output.go:112 +0x186
github.com/coredns/coredns/plugin/output_360.(*Output).SendFullDNSMessage(0xc00035a000, 0xc15ab31ce0, 0xc05c01a630, 0xc05c01a870)
	/go/src/github.com/coredns/coredns/plugin/output_360/output.go:61 +0x57
github.com/coredns/coredns/plugin/input_log_360.dnsRecordService(0x1)
	/go/src/github.com/coredns/coredns/plugin/input_log_360/log.go:76 +0xa5
created by github.com/coredns/coredns/plugin/input_log_360.setup
	/go/src/github.com/coredns/coredns/plugin/input_log_360/setup.go:37 +0x145
```
#### protobuf version
github.com/golang/protobuf v1.4.3

#### go version
go 1.16
#### environment
Linux 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 Linux

**Comment by dsnet** [comment] 2021-05-11 22:05
Hi, thank you for the report, but without a reproducer, it will be hard for us to investigate and determine whether this is a bug or occurring due to other side effects unrelated to protobufs.

**Comment by dsnet** [comment] 2021-05-18 02:41
Closing due to a lack of reproduction. Please re-open or file a new issue if you have a concrete reproduction case that we can run.

**Closed by dsnet** 2021-05-18 02:41 UTC
Labels: waiting-for-info

**Comment by gandio12138** [comment] 2022-05-09 03:10
请问这个问题原因是什么。我想知道如何解决，因为我遇到了同样的问题

**Comment by smonero** [comment] 2022-07-09 22:47
I have the exact same issue

**Comment by bianxintong** [comment] 2022-12-24 05:47
I think I have the same issue, turns out the thing I'm trying to marshal didn't initialize one of it's slice field. In fact "addr=0x0" alone should indicate the thing you're trying to marshal points to nil, or in my case, one of its fields.

**Comment by thanhpk** [comment] 2024-06-19 03:09
I still have the similar isssue. The problem is that it happends randomly

- os `Ubuntu 20.04.6 LTS`
- go `1.22.1`
- google.golang.org/protobuf `v1.34.1`
- proto `22.3-linux-x86_64`
- protoc-gen-go `v1.5.3`

Here is the stacktrace

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4793dc]

goroutine 5115633 [running]:
google.golang.org/protobuf/encoding/protowire.AppendString(...)
	/user/vendor/google.golang.org/protobuf/encoding/protowire/wire.go:455
google.golang.org/protobuf/internal/impl.appendStringNoZeroValidateUTF8({0xc11f155200?, 0xc05d115bd8?, 0xc08a781820?}, {0xc04533c348?}, 0xc10c073cb0?, {0x0?})
	/user/vendor/google.golang.org/protobuf/internal/impl/codec_gen.go:5113 +0x99
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer(0xc00018a298, {0xc11f155200?, 0x7881b3?, 0x165?}, {0xc01f965420?}, {0x7b?})
	/user/vendor/google.golang.org/protobuf/internal/impl/encode.go:145 +0x13f
google.golang.org/protobuf/internal/impl.appendMessageInfo({0xc11f155200, 0x23d, 0x8f0}, {0xae2885?}, 0xc01d3d6008, {0x60?})
	/user/vendor/google.golang.org/protobuf/internal/impl/codec_field.go:240 +0xa7
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer(0xc0003839a8, {0xc11f155200?, 0x7?, 0x185?}, {0xc01f9654e0?}, {0x9f?})
	/user/vendor/google.golang.org/protobuf/internal/impl/encode.go:145 +0x13f
google.golang.org/protobuf/internal/impl.appendMessageInfo({0xc11f155200, 0x239, 0x8f0}, {0x8f0?}, 0xc01d6359d0, {0x0?})
	/user/vendor/google.golang.org/protobuf/internal/impl/codec_field.go:240 +0xa7
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer(0xc000383af0, {0xc11f155200?, 0x4?, 0x282?}, {0xb?}, {0x3c?})
	/user/vendor/google.golang.org/protobuf/internal/impl/encode.go:145 +0x13f
google.golang.org/protobuf/internal/impl.appendMessageInfo({0xc11f155200, 0x13c, 0x8f0}, {0xc1aaaaa7b0?}, 0xc01d3e15e0, {0x14?})
	/user/vendor/google.golang.org/protobuf/internal/impl/codec_field.go:240 +0xa7
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer(0xc000380f60, {0xc11f155200?, 0x900?, 0x786d3aa345b8?}, {0x900?}, {0x8?})
	/user/vendor/google.golang.org/protobuf/internal/impl/encode.go:145 +0x13f
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshal(0xc0ac3ab6c0?, {{}, {0xf10d98, 0xc11a15a540}, {0xc11f155200, 0x0, 0x8f0}, 0x2})
	/user/vendor/google.golang.org/protobuf/internal/impl/encode.go:113 +0x85
google.golang.org/protobuf/proto.MarshalOptions.marshal({{}, 0xe8?, 0x58?, 0x96?}, {0x0, 0x0, 0x0}, {0xf10d98, 0xc11a15a540})
	/user/vendor/google.golang.org/protobuf/proto/encode.go:194 +0x35d
google.golang.org/protobuf/proto.Marshal({0xefe0e0, 0xc11a15a540})
	/user/vendor/google.golang.org/protobuf/proto/encode.go:110 +0x50
google.golang.org/grpc/encoding/proto.codec.Marshal({}, {0xd8e280?, 0xc11a15a540?})
	/user/vendor/google.golang.org/grpc/encoding/proto/proto.go:47 +0x52
google.golang.org/grpc.encode({0x786cec43f058?, 0x15f30c0?}, {0xd8e280?, 0xc11a15a540?})
	/user/vendor/google.golang.org/grpc/rpc_util.go:647 +0x3e
google.golang.org/grpc.(*Server).sendResponse(0xc000190e00, {0xf09198, 0xc10c073b60}, {0xf0df20, 0xc0af009680}, 0xc05d115b00, {0xd8e280, 0xc11a15a540}, {0x0, 0x0}, ...)
	/user/vendor/google.golang.org/grpc/server.go:1140 +0x90
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000190e00, {0xf09198, 0xc10c073ad0}, {0xf0df20, 0xc0af009680}, 0xc05d115b00, 0xc0004c0c90, 0x15817e8, 0x0)
	/user/vendor/google.golang.org/grpc/server.go:1426 +0xf3d
google.golang.org/grpc.(*Server).handleStream(0xc000190e00, {0xf0df20, 0xc0af009680}, 0xc05d115b00)
	/user/vendor/google.golang.org/grpc/server.go:1790 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	/user/vendor/google.golang.org/grpc/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 5111322
	/user/vendor/google.golang.org/grpc/server.go:1040 +0x125
```

**Comment by puellanivis** [comment] 2024-06-19 11:29
🤔 This is the code that is panicking, but also… I don’t see how it could possibly panic:
```
// AppendString appends v to b as a length-prefixed bytes value.
func AppendString(b []byte, v string) []byte {
	return append(AppendVarint(b, uint64(len(v))), v...)
}
```

`len(v)` cannot panic here because it’s called through `appendStringNoZeroValidateUTF8` which itself calls `len(v)` and so it should have panicked way back at that line, rather than the code here. Beyond that, we have a cast, a call to a local function (which is just an `append`), and an append. None of these should `nil` panic.

OK, I can [replicate the stack trace behavior](https://go.dev/play/p/eHLYrDClwEH), but it requires the string passed into the function to have a nil data pointer inside of it. How this is possible is pretty beyond me. The only thing I can think is memory corruption, or unsafe mutation of a message at the same time that a marshal is being attempted.

**Comment by yywing** [comment] 2024-09-09 07:04
go version is 1.22.1 .

Maybe https://github.com/golang/go/issues/67255

**Comment by tstirrat15** [comment] 2025-09-26 16:48
We're seeing the same behavior on golang 1.25 and protobuf 1.36.9. It's an intermittent failure, usually triggered out of the otel library and its proto marshalling.

**Comment by stapelberg** [comment] 2025-09-29 07:41
I’ll lock this issue, because there is no point in collecting random unrelated nil pointer panics.

Most likely, these are issues in your application code. If not, open a separate issue with a minimal example and steps to reproduce. Thanks!
