### ISSUE TITLE
String and protojson produces non-deterministic whitespaces.

### ISSUE THREAD

**Issue by bwplotka** [golang/protobuf#1269] opened 2021-01-16 22:51 UTC
Hi 👋🏽 Thanks for a great project! Have some really weird issue:

**What version of protobuf and what language are you using?**

[My go.mod](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/repro/go.mod):

```
	github.com/golang/protobuf v1.4.3
	github.com/opentracing/opentracing-go v1.1.0
	github.com/pkg/errors v0.9.1
	github.com/stretchr/testify v1.6.1
	golang.org/x/net v0.0.0-20190620200207-3b0461eec859
	golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
	google.golang.org/grpc v1.30.1
	google.golang.org/grpc/examples v0.0.0-20200723182653-9106c3fff523
	google.golang.org/protobuf v1.25.0
```
[protoc-gen-go: `require google.golang.org/protobuf v1.25.0 // cmd/protoc-gen-go`](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/repro/.bingo/protoc-gen-go.mod) (We use [bingo](https://github.com/bwplotka/bingo) for tool pinning)

Go 1.15

**What did you do?**

Okay, it's extremely weird so stay with me. (:

The repro test is here https://github.com/grpc-ecosystem/go-grpc-middleware/blob/repro/grpctesting/testpb/test_repro_test.go you can find proto as well.

Now it's tricky to reproduce, because it depends on... code line you invoke String  or protojson? Like some compiler optimization is changing things? I know it's super weird, but it looks like this:

Steps to repro (I am using Goland test invocation):

1. Run test.

```
package testpb

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/encoding/protojson"
)

func TestNonDeterministicMarshal(t *testing.T) {
	p := &PingRequest{Value: "something", ErrorCodeReturned: 4}

	// Remove this line to see the test failing (:

	// Sometimes
	// * "value:\"something\" error_code_returned:4"
	// * "value:\"something\"  error_code_returned:4"
	assert.Equal(t, "value:\"something\" error_code_returned:4", p.String())
	b, err := protojson.Marshal(p)
	require.NoError(t, err)

	// Sometimes
	// * "{\"value\":\"something\",\"errorCodeReturned\":4}
	// * "{\"value\":\"something\", \"errorCodeReturned\":4}
	assert.Equal(t, "{\"value\":\"something\",\"errorCodeReturned\":4}", string(b))
}
```

This passes for me 100%.

```
/home/bwplotka/.gvm/gos/go1.15/bin/go tool test2json -t /tmp/___TestNonDeterministicMarshal_in_github_com_grpc_ecosystem_go_grpc_middleware_v2_grpctesting_testpb -test.v -test.run ^\QTestNonDeterministicMarshal\E$
=== RUN   TestNonDeterministicMarshal
--- PASS: TestNonDeterministicMarshal (0.00s)
PASS

Process finished with exit code 0
```

2. Remove comment `	// Remove this line to see the test failing (:` and newline below:

```
package testpb

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/encoding/protojson"
)

func TestNonDeterministicMarshal(t *testing.T) {
	p := &PingRequest{Value: "something", ErrorCodeReturned: 4}

	// Sometimes
	// * "value:\"something\" error_code_returned:4"
	// * "value:\"something\"  error_code_returned:4"
	assert.Equal(t, "value:\"something\" error_code_returned:4", p.String())
	b, err := protojson.Marshal(p)
	require.NoError(t, err)

	// Sometimes
	// * "{\"value\":\"something\",\"errorCodeReturned\":4}
	// * "{\"value\":\"something\", \"errorCodeReturned\":4}
	assert.Equal(t, "{\"value\":\"something\",\"errorCodeReturned\":4}", string(b))
}
```

Now this fails for me with:

```
//home/bwplotka/.gvm/gos/go1.15/bin/go tool test2json -t /tmp/___TestNonDeterministicMarshal_in_github_com_grpc_ecosystem_go_grpc_middleware_v2_grpctesting_testpb -test.v -test.run ^\QTestNonDeterministicMarshal\E$
=== RUN   TestNonDeterministicMarshal
    test_repro_test.go:17: 
        	Error Trace:	test_repro_test.go:17
        	Error:      	Not equal: 
        	            	expected: "value:\"something\" error_code_returned:4"
        	            	actual  : "value:\"something\"  error_code_returned:4"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-value:"something" error_code_returned:4
        	            	+value:"something"  error_code_returned:4
        	Test:       	TestNonDeterministicMarshal
    test_repro_test.go:24: 
        	Error Trace:	test_repro_test.go:24
        	Error:      	Not equal: 
        	            	expected: "{\"value\":\"something\",\"errorCodeReturned\":4}"
        	            	actual  : "{\"value\":\"something\", \"errorCodeReturned\":4}"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-{"value":"something","errorCodeReturned":4}
        	            	+{"value":"something", "errorCodeReturned":4}
        	Test:       	TestNonDeterministicMarshal
--- FAIL: TestNonDeterministicMarshal (0.00s)
```

3. Put any comment back in that spot and all works again.

NOTE: This works somehow underministically, so CI, running it with other tests vs single changes behavior (essentially on what line to put comment to affect output) 

**What did you expect to see?**

No matter what and where I put comments in my code I expect the same `String` and `protojson` Output =D

**What did you see instead?**

Putting comment in right spot adds or removes whitespace between poto fields.

**Anything else we should know about your project / environment?**

Pretty standard, you can see all here: https://github.com/grpc-ecosystem/go-grpc-middleware/tree/repro 

We will not touch `repro` branch so you can take a look.

I know it might be annoying little thing, but deterministic output would be supper nice, especially for reliable unit tests (that's how I noticed this)

**Comment by dsnet** [comment] 2021-01-16 23:35
The pseudo-random output is deliberate. See https://developers.google.com/protocol-buffers/docs/reference/go/faq#hyrums_law.

If there is a legitimate need for stable output, then this is a duplicate of #1121.

**Closed by dsnet** 2021-01-16 23:35 UTC

**Comment by bwplotka** [comment] 2021-01-16 23:38
Thanks a lot, sorry for duplicate!
