### ISSUE TITLE
proto3 json_name option does not update json field names

### ISSUE THREAD

**Issue by jjeffery** [golang/protobuf#189] opened 2016-05-31 00:40 UTC
When I specify the `json_name` option, I would expect that the generated code would use the name specified in the `json` tag, but it doesn't.

For example:

``` proto
syntax = "proto3";

package exampletest;

message SomeMessage {
        string some_field  = 1 [json_name="SomeField"];
}
```

produces

``` go
type SomeMessage struct {
        SomeField string `protobuf:"bytes,1,opt,name=some_field,json=SomeField" json:"some_field,omitempty"`
}
```

So the JSON name ("SomeField") is honoured in the `protobuf` tag, but not the `json` tag.

I am aware of issue #183, where there is some discussion as to whether the json tag should be the same as the jsonpb tag in general. Maybe the existing behaviour is correct when the `json_name` is not specified.

It just seems to me that if the proto spec explicitly asks for a JSON name, it should be honoured in the `json` tag. Does anyone else agree? I'm happy to submit a PR.

**Comment by dsymonds** [comment] 2016-05-31 00:45
The `jsonpb` package is the place that matters. It's the package that implements the correct proto3 JSON formatting, and it doesn't consult the `json` field tag, so the value of the `json` field tag doesn't matter in this regard.

**Comment by jjeffery** [comment] 2016-05-31 00:58
Yes, understood about the `jsonpb` vs `json` packages. I should probably explain my reason for raising this issue.

I have some structures that make use of Go JSON encoding. I am looking to converting the code to using GRPC, with the requirement to retain backwards compatibility with the existing interface for the time being.

In my case this can be done quite easily by specifying the structures in a `.proto` file. The structures generated by `protoc` are close enough to what I currently have so that they can be used. The only exception to this is the `json` tags generated by the proto compiler.

Of course I can get around this by duplicating the structures for the purpose of specifying the JSON field names -- that's not a drama. It's just more convenient this way, and I would have thought that generating `json` tags that are different from the `json_name` option specified is a bit of a surprise.

Out of interest, if the `json` field tags don't matter in this regard, is there some other reason why they are generated at all?

**Comment by dsymonds** [comment] 2016-05-31 01:02
I think trying to jam things in via a .proto is where you've diverged from recommended practice. Either the protos are the canonical thing, or something else is, and it sounds like your situation is in the second camp. You'll probably trip over other things besides this specific issue too. I'd just go with hand-written structs and make do with a little bit of duplicated work.

The `json_name` feature is a latecomer, and proto3-specific. I don't think we want to mess with existing behaviour of the `json` struct field tags that is probably being relied upon by someone. At this point they can probably be considered "legacy".

**Comment by jjeffery** [comment] 2016-05-31 01:06
OK, so the `json` tags generated by protoc are legacy. Got it.

**Comment by omeid** [comment] 2017-01-25 13:46
@dsymonds Would you consider reviewing a pull request that adds an option to disable the legacy json tags?

**Comment by bcmills** [comment] 2017-01-25 14:38
@omeid see https://github.com/golang/protobuf/issues/256 for what I think is a better alternative.

**Comment by omeid** [comment] 2017-01-26 00:45
Thanks for pointing out that issue @bcmills, I agree that your suggestion is a much better solution and would solve quite a few other problems around json and protobuf.

**Comment by bcmills** [comment] 2017-01-26 17:17
Great!  In that case, I'll close this as a duplicate of #256.  Thanks for the input: this discussion is another good data point for whether to accept that proposal and how to prioritize it.

**Closed by bcmills** 2017-01-26 17:17 UTC
