### ISSUE TITLE
jsonpb: Can't handle 2D Array

### ISSUE THREAD

**Issue by base698** [golang/protobuf#643] opened 2018-06-24 01:13 UTC
This line of code tries to parse a JSON array into a map:

https://github.com/golang/protobuf/blob/9eb2c01ac278a5d89ce4b2be68fe4500955d8179/jsonpb/jsonpb.go#L891

JSON:
```
{"id":"test",
"topic":[["string"]],
"ints":[[1,2]]
}
```

test.proto:
```
message Link {
        string id     = 1;
        message ListOfTopics {
                repeated string items = 1;
        }

        repeated ListOfTopics topic = 2; 

        message ListOfInts {
                repeated int32 items = 1;
        }

        repeated ListOfInts ints = 3; 
}
```

**Comment by base698** [comment] 2018-06-24 01:32
Here: https://github.com/golang/protobuf/blob/9eb2c01ac278a5d89ce4b2be68fe4500955d8179/jsonpb/jsonpb.go#L989

It's iterating over the rows in the 2d array and since it thinks it's a struct when it calls back in the the JSON array is serialized into this:  map[string]json.RawMessage which fails...

**Comment by dsnet** [comment] 2018-06-24 02:21
Protobufs has no concept of a 2D array.

A valid JSON for message `Link` would look like:
```json
{
    "id": "test",
    "topic": [
        {"items":["item1a", "item1b"]}, 
        {"items":["item2a", "item2b", "item2c"]}, 
    ]
}
```
Notice that each element of `"topic"` is itself a dictionary?

**Comment by dsnet** [comment] 2018-06-26 19:29
Closing this as working as intended. Whether we support 2D arrays is beyond the scope of Go protobufs, and would have to be an issue raised up in the mainline implementation at [github.com/google/protobuf](http://github.com/google/protobuf).

**Closed by dsnet** 2018-06-26 19:29 UTC
Labels: jsonpb, question
