### ISSUE TITLE
proto: support Merge with FieldMask

### ISSUE THREAD

**Issue by pcriadoperez** [golang/protobuf#1296] opened 2021-03-19 13:58 UTC
**Is your feature request related to a problem? Please describe.**
It's complicated to merge one message with another using a field mask for update and patch operations.

**Describe the solution you'd like**
Have a function to easily merge one message with another and a field mask. Similar to what already exists in other languages.

**Java**: https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/util/FieldMaskUtil.html#merge-com.google.protobuf.FieldMask-com.google.protobuf.Message-com.google.protobuf.Message.Builder-com.google.protobuf.util.FieldMaskUtil.MergeOptions-

**Python**: https://googleapis.dev/python/protobuf/latest/google/protobuf/field_mask_pb2.html

**Comment by dsnet** [comment] 2021-05-13 06:07
Closing as duplicate of #1183, which is the higher-order issue concerned with operations applied upon FieldMask.

**Closed by dsnet** 2021-05-13 06:07 UTC
