### ISSUE TITLE
plugins are not supported : grpc

### ISSUE THREAD

**Issue by harrybin815** [golang/protobuf#1070] opened 2020-04-01 10:28 UTC
run:
```
protoc protoc/route_guide.proto --go_out=plugins=grpc:.
```
output:
```
--go_out: protoc-gen-go: plugins are not supported; use 'protoc --go-grpc_out=...' to generate gRPC
```

**Comment by neild** [comment] 2020-04-01 14:47
The `google.golang.org/protobuf/cmd/protoc-gen-go` program doesn't include gRPC support. Instead, that support will soon be provided by a `google.golang.org/grpc/cmd/protoc-gen-go-grpc` program. That program is In code review now, but not quite yet available.

The `github.com/golang/protobuf/protoc-gen-go` program supports gRPC as always, and will continue to do so. Versions `v1.4` and newer of that program support the new protobuf reflection features. (Right now, the newest release is `v1.4.0-rc.4`.)

**Comment by alexshtin** [comment] 2020-04-01 19:39
@neild, thanks for update. Could you provide ver approximate date for gRPC support in `google.golang.org/protobuf/cmd/protoc-gen-go`?

**Comment by neild** [comment] 2020-04-01 20:10
`google.golang.org/protobuf/cmd/protoc-gen-go` will never have explicit gRPC support. We've split it out into a separate program (`protoc-gen-go-grpc`), so the gRPC code generator can live in the gRPC repository and follow that repo's release cycle.

The practical effect is that when using this generator you will need to specify two flags on the `protoc` command line (or run `protoc` twice):

```sh
protoc --go_out=. --go-grpc_out=. foo.proto
```

The original `github.com/golang/protobuf/protoc-gen-go` will continue to directly support gRPC generation indefinitely, to avoid breaking existing users.

**Comment by alexshtin** [comment] 2020-04-01 22:51
Ok, this is better approach, I agree. I will rephrase my question though: could you provide very approximate date when `google.golang.org/protobuf/cmd/protoc-gen-go-grpc` is available?

**Comment by neild** [comment] 2020-04-01 23:35
Whenever https://github.com/grpc/grpc-go/pull/3453 is approved and merged; unfortunately, the timing of that isn't under my control, so I can't give even an approximate date. It's in the gRPC folks' hands right now, but current events have everyone working at reduced capacity and I don't know where this is on their priority list.

**Comment by alexshtin** [comment] 2020-04-02 01:50
Thanks @neild. I am super excited about V2. Great job!

**Comment by dsnet** [comment] 2020-04-02 05:23
I'm going to close this issue, since it seems to be a duplicate of #903

**Closed by dsnet** 2020-04-02 05:23 UTC

**Comment by kraymond37** [comment] 2020-07-16 06:42
This [doc](https://grpc.io/docs/languages/go/) needs to be updated.

**Comment by dsnet** [comment] 2020-07-16 07:30
I recommend filing an issue on https://github.com/grpc/grpc-go/issues

**Comment by quinn** [comment] 2020-09-11 21:19
It seems strange to give a warning and recommend using a plugin that does not yet exist.

**Comment by Shanduur** [comment] 2020-10-11 14:02
How to use original `github.com/golang/protobuf/protoc-gen-go`? The new way just broke all my codebase...

**Comment by AndresHMosqueda** [comment] 2021-03-09 00:52
How can I fix this issue? 

--go_out: protoc-gen-go: plugins are not supported; use 'protoc --go-grpc_out=...' to generate gRPC

![Screen Shot 2021-03-08 at 18 46 25](https://user-images.githubusercontent.com/42881305/110401551-5dcdde80-803f-11eb-9e42-5a6f88b303bc.png)

**Comment by Shanduur** [comment] 2021-03-09 04:49
@AndresHMosqueda this should work:
`protoc --proto_path=proto --go_out=plugins=grpc:. proto/*.proto`

**Comment by puellanivis** [comment] 2021-03-09 07:34
It tells you what you need to do:
```
protoc --go-grpc_out=. dummy/dummyProt/dummy.proto
```

**Comment by CrayfishGo** [comment] 2021-03-10 00:49
> `google.golang.org/protobuf/cmd/protoc-gen-go` will never have explicit gRPC support. We've split it out into a separate program (`protoc-gen-go-grpc`), so the gRPC code generator can live in the gRPC repository and follow that repo's release cycle.
> 
> The practical effect is that when using this generator you will need to specify two flags on the `protoc` command line (or run `protoc` twice):
> 
> ```shell
> protoc --go_out=. --go-grpc_out=. foo.proto
> ```
> 
> The original `github.com/golang/protobuf/protoc-gen-go` will continue to directly support gRPC generation indefinitely, to avoid breaking existing users.

This can work. Great

**Comment by tejasjadhav** [comment] 2021-07-29 10:27
How do I use custom gRPC plugins with this change? We used to rely on that to generate custom gRPC implementation and a few additional code using our own custom plugins.

Also, why was this change introduced as a minor version change when it is breaking backward compatibility?

**Comment by neild** [comment] 2021-07-29 16:58
> why was this change introduced as a minor version change

It was not.

`google.golang.org/protobuf/cmd/protoc-gen-go` has never supported gRPC code generation.

`github.com/golang/protobuf/cmd/protoc-gen-go` still contains gRPC code generation support. (However, the gRPC code generation is frozen and superseded by `google.golang.org/grpc/cmd/protoc-gen-go-grpc`, so I would recommend switching to the gRPC-owned plugin at your earliest convenience.)

**Comment by tejasjadhav** [comment] 2021-08-01 14:02
@neild reason for stating this as as a minor version change is that in `v1.3.5` we could still [specify custom plugins (ex. `plugins=grpc+my-custom-plugin`)](https://github.com/golang/protobuf/blob/v1.3.5/protoc-gen-go/generator/generator.go#L505). In `v1.4.0` that [support was removed](https://github.com/golang/protobuf/blob/v1.4.0/protoc-gen-go/main.go#L59).

This did break our internal code generation scripts as they relied on the `plugins` parameter. For now the workaround that we going ahead with is to generate the gRPC clients based on `v1.3.5` and generate the gRPC server as per the latest version.

**Comment by neild** [comment] 2021-08-02 17:53
There has never been a way to add a custom plugin to `protoc-gen-go`, however. The list of plugins is built in at compile time. You can build your own generator binary uses the `github.com/golang/protobuf/protoc-gen-go/generator` package and adds a plugin, but that is still possible with `v1.4.0`. (New code should use the [`protogen`](https://pkg.go.dev/google.golang.org/protobuf/compiler/protogen) package, however.)

The removed support you link to is in an executable (package main), not an importable package.
