### ISSUE TITLE
cannot encode data of google.proto.any  when data is empty

### ISSUE THREAD

**Issue by muln** [golang/protobuf#1407] opened 2022-01-15 06:25 UTC
error: unmarshal ExtraData.data error Any JSON doesn't have '@type'

![image](https://user-images.githubusercontent.com/8455461/149611692-87861a06-7881-48ff-a0fc-4a424495e171.png)

**Comment by cybrcodr** [comment] 2022-01-15 06:55
The code you are referencing is in unmarshaling a JSON object of Any proto -- https://github.com/golang/protobuf/blob/master/jsonpb/decode.go#L146-L160.  See https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#any.  That is working as intended.  Closing this issue unless you meant differently.

**Closed by cybrcodr** 2022-01-15 06:55 UTC

**Comment by muln** [comment] 2022-01-15 08:02
decode binary byte about a JSON object of Any proto, the result is `{}`。 want to encode this result again, but ran into the above problem

**Comment by cybrcodr** [comment] 2022-01-15 20:11
Sorry I don't understand.  Can you provide example code snippet (and input values) to demonstrate the issue?
