### ISSUE TITLE
Generating proto files in multiple directories 

### ISSUE THREAD

**Issue by kiro** [golang/protobuf#48] opened 2015-07-15 16:39 UTC
Hi, when generating go protos like

protoc --go_out=plugins=grpc:. */*.proto

it fails with error:inconsistent package names: blabla

I guess the assumptions is that it will be called only for files in the same directory. Are there plans to fix that?

**Comment by dsymonds** [comment] 2015-07-15 21:46
Dupe of #39.

**Closed by dsymonds** 2015-07-15 21:46 UTC
Labels: duplicate
