### ISSUE TITLE
How to add customized go tag for ***.pb.go?

### ISSUE THREAD

**Issue by FGYFFFF** [golang/protobuf#1455] opened 2022-06-10 07:03 UTC
I need to add some go tags to the struct in ***.pb.go recently.
And I extended "google.protobuf.FieldOptions",  as follows：
```
import "google/protobuf/descriptor.proto";

option go_package = "/api";

extend google.protobuf.FieldOptions {
  optional string query = 50101;
}
```
And I write my ***.proto, as follows:
```
import "api.proto";

message MultiTagReq {
  optional string QueryTag = 1 [(api.query)="query"];
}
```
And I developed a protoc plugin that calls `internal_gengo.GenerateFile()` to generate `***.pb.go`, but I found out that `***.pb.go` does not provide an **insertion point** for the go tag, so I can't add it to `***.pb.go` , so I can't add my custom go tag to `***.pb.go`.
Currently, I think I can add a custom go tag by parsing the syntax tree of `***.pb.go`, but I think that's too inefficient. So I would like to ask if there is any other way to support custom go tags in `***.pb.go`.

**Comment by puellanivis** [comment] 2022-06-10 11:47
This is a duplicate of #1418

**Closed** 2022-06-14 12:29 UTC
