### ISSUE TITLE
jsonpb: bring back old behaviour of handling nulls and JSONPBUnmarshaler

### ISSUE THREAD

**Issue by krzysztofdrys** [golang/protobuf#1301] opened 2021-03-22 10:27 UTC
**What version of protobuf and what language are you using?**
`go version go1.16.2 darwin/amd64`
` v1.5.1`

**What did you do?**
We are using a field with a message, which implements `jsonpb. JSONPBUnmarshaler` to implement `NullValue` like behaviour for our own messages. This is very similar to the old behaviour of `TestUnmarshalNullWithJSONPBUnmarshaler` (pre: https://github.com/golang/protobuf/commit/cc376d7145c679febdd10557ded10ff26a681fbb)

**What did you expect to see?**
When I receive `null` json value in a nested field, which implements `jsonpb. JSONPBUnmarshaler`, I expect `UnmarshalJSONPB` to be called.

I other words, I expect test `TestUnmarshalNullWithJSONPBUnmarshaler` in form pre https://github.com/golang/protobuf/commit/cc376d7145c679febdd10557ded10ff26a681fbb to pass.

**What did you see instead?**

`nil` is assigned to this field.

I am aware that some breaking changes in similar area have been announced: https://github.com/golang/protobuf/releases#v1.4-nil-values But from what I understand, these release notes are about changes in handling `nil` go structures, whereas my change is about handling `null` json elements.

I created a pull request which resolves this issue https://github.com/golang/protobuf/pull/1300

**Comment by dsnet** [comment] 2021-03-24 04:57
The `github.com/golang/protobuf` module is deprecated. We only accept changes to documentation, bugs fixes with justifiable impact, or fixes for a regression. Since this is fixing a regression, it seem appropriate to restore this functionality.

**Comment by dsnet** [comment] 2021-03-24 18:44
#1300 has been merged. Thanks for the report and fix.

**Closed by dsnet** 2021-03-24 18:44 UTC

**Comment by krzysztofdrys** [comment] 2021-03-24 20:19
Thanks @dsnet for guiding me trough the process of fixing this.

Is there any chance that this will be released soon?

**Comment by dsnet** [comment] 2021-03-29 19:32
v1.5.2 is tagged.
