### ISSUE TITLE
golang json.Unmarshal to protobuf struct []byte

### ISSUE THREAD

**Issue by Molecular-Future** [golang/protobuf#1146] opened 2020-06-12 07:55 UTC
proto file
```
syntax = "proto3";
package entity;

message Test {
  bytes info=1;
  int32 version = 4;
}
```
json string convert to pb。
protoc:libprotoc 3.12.3.
go.mod

```
go 1.12

require (
	github.com/alecthomas/log4go v0.0.0-20180109082532-d146e6b86faa
	github.com/golang/protobuf v1.4.2
	github.com/jinzhu/gorm v1.9.12
	google.golang.org/protobuf v1.23.0
)

```

```
info:=`{"info":"0x97e302078c11ca8e7d75e2eedd1091eafec353864212085406d8d7dca0e3fa4a","version":20}`
test:=entity.Test{}
err:=json.Unmarshal([]byte(info),&test)
if err != nil {
	fmt.Println("Error in JSON unmarshalling from json marshalled object:", err)
	return
}
fmt.Println(string(test.Info[:]))
```

Error in JSON unmarshalling from json marshalled object: illegal base64 data at input byte 64

**Comment by neild** [comment] 2020-06-12 16:11
> illegal base64 data at input byte 64

As the error says: The input data is invalid. Fields of `bytes` type should contain JSON, not hex (which is what you seem to have here).

**Comment by dsnet** [comment] 2020-06-12 17:38
Closing as "working as intended". Per the ["JSON Mapping"](https://developers.google.com/protocol-buffers/docs/proto3#json_mapping) specification:

> JSON value will be the data encoded as a string using standard base64 encoding with paddings. Either standard or URL-safe base64 encoding with/without paddings are accepted.

**Closed by dsnet** 2020-06-12 17:38 UTC
