### ISSUE TITLE
protojson: unmarshal does not properly support null input values

### ISSUE THREAD

**Issue by jhump** [golang/protobuf#1313] opened 2021-04-22 00:57 UTC
**What version of protobuf and what language are you using?**
v1.26.0
(v1.5.0 of APIv1 module)

**What did you do?**
I tried to unmarshal JSON into a protobuf message, with various scenarios where the input data contains `null` values.
You can see the code [here](https://gist.github.com/jhump/1c5871240252c1e950b25c24a5ddedd4).

In particular, note `TestJSONPb` and `TestProtoJSON` functions.

**What did you expect to see?**
I expected the `protojson` package to support the test data containing null values, just as the `jsonpb` package does. This is based on the following snippet from the spec for the [JSON format of protocol buffers](https://developers.google.com/protocol-buffers/docs/proto3#json):

> If a value is missing in the JSON-encoded data or if its value is `null`, it will be interpreted as the appropriate [default value](https://developers.google.com/protocol-buffers/docs/proto3#default) when parsed into a protocol buffer.

**What did you see instead?**
The `protojson` package only supports `null` values as direct field values, not if they are elements in JSON arrays or values in JSON maps. So only 4 of the 12 test cases in the example code pass. (All of them pass for the `jsonpb` package.)

I can understand there being some confusion about how to handle this case for _message_ types -- for normal fields, the default/zero value of a message type is `nil`. But an element in a repeated field that is `nil` cannot be serialized: a repeated message value can be an empty message but not `nil`.

However, for symmetry, I would expect a `null` value in a JSON array to result in an empty message type, just as the older `jsonpb` did. I say "symmetry" because this is basically what happens if I construct a Go struct literal for a protobuf type, where a repeated message field (e.g. a slice of pointers to some other Go struct) contains a `nil` pointer: it gets serialized as if it were an empty message. (See the `TestMarshal` function in the gist linked above.)

**Anything else we should know about your project / environment?**
Nope.

**Comment by dsnet** [comment] 2021-04-22 01:39
There's a internal document created by the protobuf team that's generally considered more authoritative than whats posted on the developer site. In that document, it says:

> “null” is only allowed for a whole field. It cannot be used as an element in a repeated field or as key/value for a map entry.
> ```
> // Invalid: “null” not allowed as entries in a repeated field.
> {
>   “repeatedValue”: [1, null, 2]
> }
>
> // Invalid: “null” is not allowed to be map key.
> {
>   “mapValue”: {
>     null: 0
>   }
> }
> 
> // Invalid: “null” is not allowed to be map value.
> {
>   “mapValue”: {
>     0: null
>   }
> }
> ```

It's hard for us to change the behavior here since it seems explicitly specified how we're supposed to operate. I think this would need to be an issue filed with the main protobuf project.

**Comment by cybrcodr** [comment] 2021-04-22 02:02
This is one of those intentional changes we made in V2, but seems like we missed out on mentioning this in the JSON serialization section.

V2 does not allow for a JSON null in a repeated message item or a map message value except for types google.protobuf.NullValue or google.protobuf.Value.

I wish this is documented in the Protobuf guide.  I've only found a similar issue raised for the Java implementation at https://github.com/protocolbuffers/protobuf/issues/5113.

**Comment by dsnet** [comment] 2021-04-22 19:59
Given that:
1. the "official" documentation for protobuf-to-JSON specifies that we reject `null` in lists and maps,
2. the Java implementation behaves the same way (I didn't check C++) per protocolbuffers/protobuf#5113, and
3. the former tech lead of protobufs affirmed such behavior per https://github.com/protocolbuffers/protobuf/issues/5113#issuecomment-419532565,

I'm inclined to close this as working as intended. Any changes to this behavior would have to be proposed to the main protobuf project for all language implementations to support.

**Comment by jhump** [comment] 2021-04-22 22:42
> the "official" documentation for protobuf-to-JSON specifies that we reject null in lists and maps,

What documentation are you referring to here? I could not find this anywhere on the [official doc site](https://developers.google.com/protocol-buffers). Or did you mean _Go doc_ for the `protojson` package?

**Comment by dsnet** [comment] 2021-04-22 22:44
This is an internal document written by the person who designed the protobuf to JSON mapping. I really wish it would be made open, but that's out of my hands.

**Comment by dsnet** [comment] 2021-05-06 04:34
Closing as "working as intended".

**Closed by dsnet** 2021-05-06 04:34 UTC

**Comment by zhixinwen** [comment] 2022-01-07 01:11
What if I do need null in a list. Any workaround here?

**Comment by puellanivis** [comment] 2022-01-07 19:51
> What if I do need null in a list. Any workaround here?

There is unfortunately no analogous concept of `NULL` or `nil` in protobuf semantics.

If you absolutely must be able to use a `null` value in a protobuf JSON, then you’ll need to find someway to integrate with [`google.protobuf.NullValue`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.NullValue) likely through the `google.protobuf.Value` type. Though, I think that will end up a little too generic, and would permit all values to be used, so you would have to do type checking, and for protobuf messages even a struct field mapping transfer.

It is important to recognize the limitations of protobuf’s JSON mapping. It is not intended to permit all possible JSON, it’s solely designed to describe a standard way to map protobuf semantics into JSON safely, so there is a strict subset of all possible JSON  that can be used with protobuf.
