### ISSUE TITLE
How to get a `DescriptorProto` for a message from a `FieldDescriptorProto` in golang

### ISSUE THREAD

**Issue by gcarling** [golang/protobuf#821] opened 2019-03-19 22:24 UTC
Let's say I have a message structured like this:

```
message A {
  name string = 1;
}

message B {
  a A = 1;
}
```

I have a `DescriptorProto` for `B` - let's call it `md`. So I can say something like:

```
for _, field := range md.Field {
  // IsMessage will return true, since A is a message type.
  if field.IsMessage() {
    // I want to get a Descriptor for the type A
  }
}
```

This exists in other language implementations - for example, here it is in C#: 
https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/reflection/field-descriptor#class_google_1_1_protobuf_1_1_reflection_1_1_field_descriptor_1abbfe2c68b372d42ae42f837e1644218c

There is a `MessageType` property that exists if this `FieldDescriptorProto` is referring to a message. A similar `message_type` exists in python. I cannot figure out how to do this in golang, I have looked through the source code but to no avail. Can anyone assist with this?

**Comment by dsnet** [comment] 2019-03-20 00:36
Closing as a duplicate of #364. You are essentially asking for the ability to programatically traverse the type information for a protobuf message and its dependencies. Unfortunately, such functionality is not easily available, and is intended to be the flagship of the v2 re-implementation.

The best you can do today in v1 is either:
* Look up the full name of the message in the global register and hope that it's there. See [`proto.MessageType`](https://godoc.org/github.com/golang/protobuf/proto#MessageType).
* If you have a concrete message on hand, you can type assert it to `interface{ Descriptor() ([]byte, []int) }`, which will have the GZIP-compressed file descriptor and the path to the message descriptor. However, not all messages may have that method.

**Closed by dsnet** 2019-03-20 00:36 UTC

**Comment by gcarling** [comment] 2019-03-20 00:43
Makes sense, from reading the code I had a suspicion it was not possible, at least with a simple method call. Thanks for the reply
