### ISSUE TITLE
jsonob/protojson: map with null values

### ISSUE THREAD

**Issue by Antonboom** [golang/protobuf#1258] opened 2020-12-23 09:43 UTC
Hello!

```bash
$ protoc --version
libprotoc 3.14.0
```

```bash
# go.mod
google.golang.org/protobuf v1.25.0
```

I want to get JSON like
```json
{
  "users": {
    "user-1": null,  //attention!
    "user-2": {
      "email": "user2@gmail.com",
      "id": "user-2"
    }
  }
}
```

with
```golang
import "google.golang.org/protobuf/encoding/protojson"

var json = protojson.MarshalOptions{
	Multiline:     true,
	Indent:        "  ",
	AllowPartial:  true,
	UseProtoNames: true,
}
```

---

Here are the options i tried:
```proto
message User {
  string id = 1;
  string email = 2;
}

message ResponseSimple {
  map<string, User> users = 1;
}
```

```json
{
  "users": {
    "user-1": {},
    "user-2": {
      "id": "user-2",
      "email": "user2@gmail.com"
    }
  }
}
```

Not suitable: empty object `{}` instead of `null`.

Empty object I would expect for `User{}` but not for `nil`.

---

```proto
message ResponseWithCustomNullable {
  message NullableUser {
    oneof kind {
      google.protobuf.NullValue null = 1;
      User user = 2;
    }
  }
  map<string, NullableUser> users = 1;
}
```

```json
{
  "users": {
    "user-1": {
      "null": null
    },
    "user-2": {
      "user": {
        "id": "user-2",
        "email": "user2@gmail.com"
      }
    }
  }
}
```

Not suitable: extra keys `null/user` from `oneof`.

---

```proto
message ResponseWithValue {
  map<string, google.protobuf.Value> users = 1;
}
```

```json
{
  "users": {
    "user-1": null,
    "user-2": {
      "email": "user2@gmail.com",
      "id": "user-2"
    }
  }
}
```

Suitable! But there is no convenient way to convert `proto.Message` to `structpb.Struct`.
Now we have to do this transformation through an extra JSON layer.

Detailed example [here](https://github.com/Antonboom/protojson_map_with_null_issue/blob/master/main.go).

I will be grateful for help or advice. Thanks!

**Comment by puellanivis** [comment] 2020-12-23 12:45
The [protobuf JSON mapping specification](https://developers.google.com/protocol-buffers/docs/proto3#json) does not allow `null` to appear as a JSON value for a `message`. Semantically, an empty message is equivalent to a not-appearing message. This behavior cannot be change without a change to the protobuf spec.

The protobuf JSON definition specifies that any the two different values of the `NullableUser` message must be embedded with their key name. This behavior cannot be change without a change to the protobuf spec.

By specification, the last option you present is the only way you can get a `null` value into a JSON output.

This issue appears to have nothing actionable without a change to the protobuf spec.

**Comment by Antonboom** [comment] 2020-12-23 14:13
@puellanivis, thank u for fast response!

1)
Could you highlight the text in the specification responsible for this?
```
does not allow null to appear as a JSON value for a message
```

I see
```
If a value is missing in the JSON-encoded data or if its value is null, 
it will be interpreted as the appropriate default value when parsed into a protocol buffer.
```
but nothing is said about working in the other direction (message -> json).

And it seems logical to me that the default value for the `proto3 message` is `Message{}/new(Message)`, not `nil`. Therefore, for the first we get `{}`, and for the second - `null`?

2)
I think I've seen implementations that allow you to omit additional `oneof`' keys :(

3)
Why then are there no extra fields for `google.protobuf.Value`'s `oneof`? Special case?

**Comment by puellanivis** [comment] 2020-12-23 19:15
> it will be interpreted as the appropriate default value when parsed into a protocol buffer.

The default value of a message is a message filled with all default values, that is `{}`. Thus `null` and `{}` are semantically identical. 

While at first, it might seem that the marshaling could be ambiguous in that a `nil` value could marshal into either `{}` or `null`, the solution presents itself when you think about it backwards.

Both `{"user-1":{}` and `{"user-1":null}` _MUST_ (word used as per RFC standards) both parse into `map[string]*User{"user-1":&User{}}` because the `null` value _MUST_ be parsed into the default value, and the default value of a message is an empty message of the same type, i.e. `&User{}`.

Thus, we’re stuck in that there is no way to round-trip the JSON through data structures and output, and retain the same JSON throughout. Normally, these values _SHOULD_ just be omitted, since their omission also means the empty value, but in a map, we have an entry sub-message with a non-default key, and thus that entry sub-message not the default, so it cannot be omitted.

So, we must choose one or the other. And since `{}` is shorter than `null`, it makes sense to use that instead of the longer one. And since, as noted above, all `null`s are equivalent to the default value, so which one we choose _SHOULD_ never impact the semantics of the protobuf unmarshaled from it.

To be much more explicit with an example, even if we allow `nil` to marshal into `null`, then we would have as you want `{"users":{"user-1":null}}`. But then, if we unmarshal that into a `resp := new(ResponseSimple)` then it _MUST_ produce a value deep equal with `&ResponseSimple{"users":{"user-1":&User{}}}`, and when we go to marshal this, it will produce `{"users":{"user-1":{}}}`. This means that the round-trip cannot ever possibly preserve that `nil` value.

> I think I've seen implementations that allow you to omit additional oneof' keys :(

It is omitting the additional `oneof` keys. The only key set in the two `NullableUser` examples are the one that is set: i.e. either `null` or `user`. The problem is that you are wrapping this `oneof` in a submessage, which itself must be wrapped in a sub-object, with the specific `oneof` field name being specified. i.e. `&NullableUser{Null:structpb.NewNullValue()}` must be marshalled into `{"null":null}` and `&NullableUser{User:&User{…}}` must be marshalled into `{"user":{…}}`.

> Why then are there no extra fields for google.protobuf.Value's oneof? Special case?

Yes, it is a special case. Look at the table of JSON objects and examples, and at the end of it, the third from the end is the well-known type `Value`. That row (and link to its definition) defines how `Value` is to be represented in JSON, regardless of how it is implemented under the hood. Many/most/all of the Well Known Types (WKT) have special case marshalling through JSON.

**Comment by dsnet** [comment] 2020-12-23 20:12
A high priority goal for this project is that we remain in conform with the other major protobuf implementations. That is, we explicitly avoid functionality that is unique to Go that the other implementations do not provide. For example, [the C++ API provides no option to format empty maps as `null`](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util#JsonPrintOptions).

Closing as working as intended. Any attempts to add this feature would need to first [propose this higher up at the protobuf project](https://github.com/protocolbuffers/protobuf/issues) and justify why such a feature is something that every language should provide. If the protobuf project deems this a good idea, then we will implement it.

**Closed by dsnet** 2020-12-23 20:12 UTC

**Comment by Antonboom** [comment] 2020-12-23 20:33
@puellanivis @dsnet 
Thanks for the detailed answer.
