### ISSUE TITLE
proposal: proto: compare the unmarshaled versions of Any when using Equal

### ISSUE THREAD

**Issue by F21** [golang/protobuf#455] opened 2017-11-13 00:10 UTC
I have a (heavily simplified) proto message that looks like this:

```proto
message SomeRequest {
    message type1 {
        string something = 1;
    }

    message type2 {
        map<string, string> data = 1;
    }
    repeated  google.protobuf.Any some_data = 1; // Can be either a type1 or a type2
    repeated string some_other_field = 2;
}
```

I want to use `proto.Equal()` to compare 2 `SomeRequest`s in my tests to check that they are equal.

Because map ordering is nondeterministic, every time a `type2` is marshalled into an `any.Any`, the contents of `value` would be different even though the message is the same.

While I could turn the map into a `repeated myKVtype`, but I don't need or care about the ordering of the map in my app. I just need a way to reliably compare the messages.

It would be nice if `proto.Equal()` can unmarshal any `any.Any` it encounters and perform the comparison directly on the unmarshalled protobuf message.

**Comment by dsnet** [comment] 2017-12-05 22:29
The C++ implementation does this, so comparing the unmarshaled form has precedence: https://github.com/google/protobuf/blob/92a7e778e7394386f413cec28d67a07630f784b1/src/google/protobuf/util/message_differencer.cc#L491-L502

Note that the type information is not always present for Any types and so this is not always possible. The unfortunate nature is that the encoded wire format of protobufs is not introspectable without knowing the schema and is thus not comparable.

Pull requests welcome.

**Comment by dsnet** [comment] 2018-03-08 01:39
In retrospect. I'm going to rescind my previous statement. The C++ implementation does have a operator overloaded method for `==`. Thus, it doesn't quite have an analogy for `proto.Equal`. Using `message_diff` as the justification for behavior change is probably the wrong comparison as C++'s `message_diff` functionality is closer to what the [`cmp`](https://godoc.org/github.com/google/go-cmp/cmp) package is trying to accomplish.

We should think very carefully about exactly what the semantics of `proto.Equal` is. See my comment here for a list of some edge cases: https://github.com/golang/protobuf/issues/531#issuecomment-368680893. I'm sure there are more.

**Comment by dsnet** [comment] 2018-11-05 20:31
Closing this. I've looked deeper into the behavior of `Equal` and have found more strange cases of non-orthogonal behavior. Equal is a difficult operation to define for protobufs, especially in the presence of missing type information. The current logic is strange, but I don't think we should change it either since people depend on the current behavior.

The v2 API will probably not have an Equal method, but a helper package such that you can have more powerful control over how comparisons are made using the [`cmp`](https://godoc.org/github.com/google/go-cmp/cmp) package.

**Closed by dsnet** 2018-11-05 20:31 UTC
Labels: proposal

**Comment by JimLarson** [comment] 2020-02-05 22:43
For those who can't wait for the v2 API, we worked around this by serializing to text with Any-expansion turned on and comparing the strings. Confirmed with dsnet that this works since the text serializer is deterministic.  See https://github.com/google/cel-spec/pull/104
