### ISSUE TITLE
Workflow with go modules

### ISSUE THREAD

**Issue by ericrenard** [golang/protobuf#925] opened 2019-08-09 20:31 UTC
Heya,
What is the currently recommended workflow to use protoc-gen-go in a go modules world ?

Let's say I have this configuration :
github.com/repo1/pkgA/a.proto
github.com/repo1/pkgB/b.proto

github.com/repo2/test.proto

a.proto needs to import b.proto
test.proto needs to import a.proto

Pre go modules, this was easy to solve, we had complete import path everywhere (i.e. import "github.com/repo1/pkgB/b.proto") and ran protoc from the GOPATH root.

In a go modules world, this doesn't work. If i make imports in repo1 local (i.e. import "pkgB/b.proto") and run go mod vendor then protoc -I . -I vendor  --gogo_out=paths=source_relative:., everything works fine in repo1, .pb.go are generated as expected.

But obviously, it doesn't work at all when running proto gen from repo2. I suppose it would work by adding a -I vendor/github.com/repo1 but that means a lot of manual maintenance on the import list in the makefile.

Is there a solution to this problem ? Is there a way to add a flag to protoc to "rewrite" import path "github.com/repo1" into "" at runtime ? If there were, I could revert back to complete import path and just specify in the makefile of each project that the import path for itself shall be rewritten into "".

I'm open to other ideas. I guess I could also copy the current project into its own vendor directory at the right path through a Makefile and that would work but that seems kinda gross.

**Comment by dsnet** [comment] 2019-08-09 20:42
There isn't a great answer at the moment. Closing as duplicate of #748

**Closed by dsnet** 2019-08-09 20:42 UTC

**Comment by tooolbox** [comment] 2019-10-14 22:34
@ericrenard https://github.com/golang/protobuf/issues/897 if you haven't found it.

**Comment by neild** [comment] 2019-10-15 17:01
There are several things to consider when `a.proto` imports `b.proto`:

* What does the `import` line in `a.proto` file contain?
* What Go packages are `a.proto` and `b.proto`'s generated code in?
* Where are `a.pb.go` and `b.pb.go` located?

I think your question is primarily about the first of these: What's the `...` in `import ".../b.proto"`?

If `a.proto` and `b.proto` are in different source code repositories, you have two options that I can think of.

One is to check out both repositories into well-defined locations in a common filesystem tree, and references files by their path in that tree. The `import` statement will be something like `import "github.com/project/repo/path/to/b.proto"`.

The other option is to reference files by their path within their repository, and add `-I` flags to the `protoc` command line to tell it where all the necessary repositories are. In this case, you will `import "path/to/b.proto"` and `protoc -IrepoA -IrepoB path/to/a.proto`. This is, I believe, what most non-Go projects do.

The former approach is convenient in a `GOPATH` world, because the `go` tool organizes all the repositories for you. Without the `go` tool doing that work, it's substantially less convenient, however.

Personally, I'd go with the latter approach: Don't include the repository in the path. Import `.proto` files by a name relative to the repository root (or some directory under it). Pass `-I` flags on to `protoc` for each repository. Optionally, vendor the `.proto` files depended on by a repository.

It's best, I think, not to think of this as how to work with `.proto` files in Go modules, and instead how to work with `.proto` files in multiple source repositories independent of Go or the `go` tool.
