### ISSUE TITLE
protobuf marshall ok, but unmarshall failed

### ISSUE THREAD

**Issue by zhuzhuqiang** [golang/protobuf#1402] opened 2021-12-31 10:16 UTC
I got an problem , i marshall some struct , pass the byte array to client. they used the byte array to unmarshall , but failed. i parse the byte array .  

this is wrong byte
34 0 10 6 233 128 154 231 159 165 18 10 8 128 194 238 4 16 128 192 188 1 26 0 40 1 48 1 56 1 90 0 96 0 50 2 40 1 58 0
this is right byte
34 32 10 6 233 128 154 231 159 165 18 10 8 128 194 238 4 16 128 192 188 1 26 0 40 1 48 1 56 1 90 0 96 0 50 2 40 1 58 0

i guess 32 and 0 is length of the data for 34 . 
why ? same strcut marshall different byte array.

**Comment by dsnet** [comment] 2021-12-31 17:14
Hi, without the code to reproduce this output, it will be difficult to provide any guidance on what's going wrong.

**Comment by zhuzhuqiang** [comment] 2022-01-06 10:24
just use  proto.Marshal() to generate byte[].

**Comment by puellanivis** [comment] 2022-01-06 12:52
You have not provided us with the protobuf structure that you are Marshalling, and so we cannot begin to even speculate about what is going on.

Protobuf is not self-describing, so without the proto definition, we cannot see what the intended behavior is.

**Comment by neild** [comment] 2022-01-10 17:44
Closing because there isn't much we can do without a reproduction case.

**Closed by neild** 2022-01-10 17:44 UTC
Labels: waiting-for-info
