### ISSUE TITLE
Support dumping messages with non-ASCII strings in human readable way

### ISSUE THREAD

**Issue by ashi009** [golang/protobuf#749] opened 2018-11-12 04:37 UTC
**Is your feature request related to a problem? Please describe.**

In testing/debugging we often need to dump the content of a proto message. The proto.MarshalText method encodes all non-ASCII characters to the escaped form, which is difficult to read for a human.

**Describe the solution you'd like**

Provide an additional method to dump a proto message in human readable way.

**Describe alternatives you've considered**

- Use `fmt.Printf("%#v", pb)`, but this doesn't work with pointer fields.
- Use `pretty.Print(pb)`, but it doesn't understand proto extension and XXX_ fields.
- Use `jsonpb.Marshaller.MarshalToString(pb)`, works, but this adds an additional dependency for debugging purpose, and the interface is not easy to use inline.
- modify `proto.MarshalText` to output Basic Multilingual Plane characters directly (like JSON, and it turned out that proto.UnmarshalText accepts them). However as proto's text form is not well-defined, I don't know if this will break other languages' implementations.

**Additional context**

snapshot of the logs of compact proto text:

![wechatworkscreenshot_9389bc32-614e-45af-935a-a3f2916cc541](https://user-images.githubusercontent.com/687367/48327038-8b750980-e677-11e8-8de2-1dfacf04d9e4.png)

**Comment by dsnet** [comment] 2018-11-12 07:39
Hi, I'm going to close this as a duplicate of #572. The v2 API will likely output valid UTF-8 as is without escaping by default. If not, it will at least have an option to specify doing so.

**Closed by dsnet** 2018-11-12 07:39 UTC
