### ISSUE TITLE
Using Go ProtoBuf APIv2, protoc output files still import from APIv1

### ISSUE THREAD

**Issue by sandykellagher** [golang/protobuf#1159] opened 2020-06-29 19:39 UTC
Hello,

We are aiming to migrate from Go ProtoBuf APIv1 (as at github.com/golang/protobuf) to APIv2 (as at google.golang.org/protobuf).

Running with the latest protoc-gen-go v1.25.0-devel, and protoc v3.12.3 and the simplest possible .proto file (two messages with strings and bools only), 

```
syntax = "proto3";
package requestreply;
option go_package = "privaterepo/datamodel/requestreply";

message Header {
	string permissions = 1
	string projId = 2;
}

message Status {
	bool Success = 1;
	string ErrorMessage = 2;
}

```

the generated go code still has an import that refers back to the APIv1 location

```
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: requestreply/requestreply.proto

package requestreply

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)
```
Since this module is included throughout our code, that means that our go.mod files all refer back to the APIv1 location, whereas we were hoping to ensure that all references are to the APIv2 location.

I have read in other topics that implementation of some aspects of ProtoBuf still refers back to APIv1. But I am confused in this case where the import .proto file is more or less the simplest possible.

Am I missing something?

Thanks
Sandy

**Comment by dsnet** [comment] 2020-06-29 19:41
This is a duplicate of #1077, I recommend giving that an issue for why the dependency still exists.

**Closed by dsnet** 2020-06-29 19:41 UTC
