### ISSUE TITLE
suggest generate file with protoc and protoc-gen-go version

### ISSUE THREAD

**Issue by CNSumi** [golang/protobuf#987] opened 2019-11-12 03:10 UTC
such as 

```
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: omg.proto
// protoc: libprotoc 3.6.1
// protoc-gen-go: v1.3.2
```
difference version of protoc and protoc-gen-go generated result has huge difference, sometimes hard to diff and commit

**Comment by dsnet** [comment] 2019-11-14 04:40
Duplicate of #524. Already fixed in https://golang.org/cl/186117

**Closed by dsnet** 2019-11-14 04:40 UTC
