### ISSUE TITLE
encoding/protojson: Allow for optional marshaling/unmarshaling of booleans as numeric 1/0

### ISSUE THREAD

**Issue by bignacio** [golang/protobuf#1207] opened 2020-09-20 19:40 UTC
**Is your feature request related to a problem? Please describe.**
It's not uncommon to see protocols over JSON that use numeric `1` or `0` to represent booleans. Although unfortunate, it happens. Notably what the [OpenRTB spec](https://www.iab.com/wp-content/uploads/2015/05/OpenRTB_API_Specification_Version_2_3_1.pdf) defines and the [widely used protocol buffers schema](https://developers.google.com/authorized-buyers/rtb/downloads/openrtb-proto) for it.

I'd like to submit a change to `encoding/protojson` that makes marshaling and unmarshaling optionally accept this behaviour.

**Describe the solution you'd like**
For unmarshaling JSON, extend `protojson::UnmarshalOptions` adding a new option `AcceptNumericBoolean` such that if is set, the parser will accept numeric values as boolean fields, `1` for true and `0` for false as well as `true` and `false`. Any other value is considered an error
```
type UnmarshalOptions struct {
	...
        // If AcceptNumericBoolean is set, accept numeric values as booleans, 1 for true and 0 for false.
        // Any other value is considered an error
        AcceptNumericBoolean bool
        ...
}
```

and for marshaling to JSON, extend `protojson::MarshalOptions` adding a new option `UseNumericBoolean` such that if set, for boolean fields, the number `1` is emitted instead of `true` and the number `0` instead of `false`
```
type MarshalOptions struct {
	...
        // UseNumericBoolean emits boolean fields with 1 for true and 0 for false 
        UseNumericBoolean bool
        ...
}
```

This would also affect the behaviour of `EmitUnpopulated`

**Describe alternatives you've considered**
I've considered other ways to inject encoders and decoders into `protojson` but that would be a more invasive change and perhaps negatively affect performance.

**Additional context**
I've started working on these changes on a fork and would like to make it available to all if accepted.

**Comment by puellanivis** [comment] 2020-09-21 09:18
Unfortunately, for the marshaling option, the [protobuf–JSON Mapping standard](https://developers.google.com/protocol-buffers/docs/proto3#json) itself does not describe any allowance for encoding a boolean as a numeric value. We have already discussed for other types the possibilities of a non-standard marshalling option (e.g. not quoting an `int64` if it is in the range of `int32`) and our decision has largely been: the protobuf standard does not permit us to make any non-standard marshalling choices. If this is truly something that should be supported behavior, then the specification should explicitly lay out that it is valid.

But as for the `UnmarshalOption`, I think sometimes, it is necessary to account for potentially non-standard encodings, because not every encoder can or will hold to the standards as tightly as we do.

I think a central issue here is that the OpenRTB spec that you are quoting from is actually explicitly defining integers with valid values `{ 0, 1 }` (in particular note `instl / integer; default = 0 / 1 = the ad is interstitial or full screen, 0 = not interstitial`), while the protobuf is encoding those as `bool`. The strange thing here is that defining `optional instl int = 6;` on the protobuf is compatible with `optional instl bool = 6;` in all forms except the proto­–JSON mapping.

I think this might actually be a genuine issue with the proto–JSON mapping. In the proto binary wire format, `bool` is explicitly called out as compatible with other numeric formats, with type-conversion happing as per C++ rules (i.e. 0 = false, any other value = true). It might be a good idea for the protobuf–JSON standard to explicitly standardize this compatibility as well.

**Comment by bignacio** [comment] 2020-09-21 13:00
It would certainly be great if the protobuf–JSON standard could formalize this compatibility, similar to what it does with enums (although arguably enums fall into a different category)

It is unfortunate that such cases exist, one might argue that the [OpenRTB proto schema](https://developers.google.com/authorized-buyers/rtb/downloads/openrtb-proto) doesn't really follow the spec or that in-house defined OpenRTB JSON schema vary too much.

The reality is it happens and it would be good to be able to accommodate such differences specially for those gradually moving from JSON to protocol buffers.

**Comment by neild** [comment] 2020-09-21 23:51
Any changes to the JSON mapping need to be proposed as a general-purpose change to the protobuf specification and implemented in all supported languages:
https://developers.google.com/protocol-buffers/docs/faq#can_i_add_new_features_to_protocol_buffers

The `google.golang.org/protobuf/encoding/protojson` package implements the standard protobuf JSON mapping. Supporting JSON formats outside of that mapping are out of scope for this package.

A cursory look at the Java JSON printer and parser does not appear to indicate that they support representing boolean fields as numeric values. The `parseBool` method accepts only the exact string values `"true"` and `"false"`, and I don't see any way to configure the printer to change the formatting of bools. This seems to indicate that this is not a common, if non-standard feature, either.

**Comment by puellanivis** [comment] 2020-09-25 10:12
@bignacio yes, the OpenRTB proto you linked to is equivalent under the binary wire-format. It’s only when handling it as a JSON that we see that the standardized JSON mapping results in it producing non-standard code (i.e. `true`/`false` instead of `1`/`0` as per spec.) I would argue this places the proto out of spec, or at least presents a compatibility issue with the spec. As I’ve found any time I start into investigating spec compliance of any code, there’s usually a hundred middling corner-cases that drag everything out of spec. Feasibly, because of the compatibility guarantee of the wire format, the proto buf _should_ be able to convert all their `bool` into `int`.

@neild I agree, it’s definitely not a standard feature. And the Go implementation tries really hard to stick strictly to the spec, and I definitely agree that we should never provide an option to emit 0/1 for `bool`s until/unless the protobuf spec defines it. But decoding data is an interesting question here, as it points to compatibility rather than compliance, which is generally a different ballgame, i.e. we wouldn’t want to break on any output that for instance the C++/Java/Python implementations might generate. But if none of them permit this generation, then we definitely shouldn’t support unmarshalling it.

**Comment by dsnet** [comment] 2020-09-26 22:18
This behavior would have to be first proposed at github.com/protocolbuffers/protobuf for all languages with a JSON implementation to provide consistent behavior. Without uniform agreement that this is to be handled, we can't do anything here.

**Comment by bgcint** [comment] 2020-10-02 20:38
That's fair, I completely agree that the problem is due to conflicting specs while each, individually, are internally consistent.
I'll try and come up with a proposal that can be considered in the broader context.
Thanks everyone.

**Comment by bignacio** [comment] 2020-10-02 20:39
That's fair, I completely agree that the problem is due to conflicting specs while each, individually, are internally consistent.
I'll try and come up with a proposal that can be considered in the broader context.
Thanks everyone.

**Comment by dsnet** [comment] 2020-10-06 18:21
Closing this as inactionable. Leaving this open in this repo won't get this anywhere as it needs this needs to be brought up and approved at https://github.com/protocolbuffers/protobuf. If the main protobuf project adopts this proposal, we'll implement it here.

**Closed by dsnet** 2020-10-06 18:21 UTC
