### ISSUE TITLE
Implementing field mask as a set (some map implementation), rather than an array. 

### ISSUE THREAD

**Issue by akashagrahari-mt** [golang/protobuf#854] opened 2019-05-21 07:29 UTC
It is frequently required to check whether a specific path exists in the list of field mask paths. Implementing it as a set would make it a lot easier.

**Comment by dsnet** [comment] 2019-05-21 15:52
Closing as duplicate of #398.

The underlying representation can’t be a map since it must be a faithful representation of what `field_mask.proto` specifies. That said we intend to provide functionality to make it easier to interact with field mask.

**Closed by dsnet** 2019-05-21 15:52 UTC
