### ISSUE TITLE
Invalid reference of ProtoPackageIsVersion4 in v1.25.0

### ISSUE THREAD

**Issue by gkarthiks** [golang/protobuf#1233] opened 2020-10-27 12:44 UTC
**What version of protobuf and what language are you using?**
**Language:** GoLang
**Version:**
>protoc: libprotoc 3.13.0
protoc-gen-go: protoc-gen-go v1.25.0

**What did you do?**
I followed the below steps.
```mkdir protoc-learning```

```go mod init proto-gen-hello```

```bash
cat <<EOF >hello.proto
> syntax = "proto3";
> package hello;
> option go_package = ".;hello";
> message Greet {
>     string hello = 1;
> }
> EOF
```

```bash
cat <<EOF >main.go
> package main
> import "log"
> func main() {
>	log.Print("Hello protoc")
> }
```

```bash
go get google.golang.org/protobuf@v1.25.0
```

⚠️ This above step is resulting in the following known errors though
https://github.com/golang/protobuf/issues/1033
https://github.com/golang/protobuf/issues/1224
The workaround I used is adding the module manually in the `go.mod` file. 

```
mkdir out
```

```
 protoc --proto_path . -I=. hello.proto --hello_out=./out --go_out=./out
```

As expected, the above command creates the `pb.go` file. But it creates the file with `proto "github.com/golang/protobuf/proto"` dependency. 

With this also, the file refers `proto.ProtoPackageIsVersion4` constant.

**What did you expect to see?**
I expect to get v1.25.0 dependency resolved and the pb.go file should be created with the corresponding constants/variables. Because the `proto.ProtoPackageIsVersion4` is not available in the v1.25.0

**What did you see instead?**

I see the dependency as `proto "github.com/golang/protobuf/proto"` and referred `const _ = proto.ProtoPackageIsVersion4` constant which is not available in v1.25.0 as I have added that in the `go,mod`.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

<details>
<summary>Click to see go.mod file</summary>
<pre>
module protoc-gen-hello

go 1.15

require (
	google.golang.org/protobuf v1.25.0
)
</pre>
</details>

<details>
<summary>Click to see proto file</summary>
<pre>
syntax = "proto3";
package hello;
option go_package = ".;hello";
message Greet {
    string hello = 1;
}
</pre>
</details>

<details>
<summary>Click to see pb.go file</summary>
<pre>
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: hello.proto

package hello

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Greet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hello string `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
}

func (x *Greet) Reset() {
	*x = Greet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Greet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greet) ProtoMessage() {}

func (x *Greet) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greet.ProtoReflect.Descriptor instead.
func (*Greet) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{0}
}

func (x *Greet) GetHello() string {
	if x != nil {
		return x.Hello
	}
	return ""
}

var File_hello_proto protoreflect.FileDescriptor

var file_hello_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x22, 0x1d, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hello_proto_rawDescOnce sync.Once
	file_hello_proto_rawDescData = file_hello_proto_rawDesc
)

func file_hello_proto_rawDescGZIP() []byte {
	file_hello_proto_rawDescOnce.Do(func() {
		file_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_hello_proto_rawDescData)
	})
	return file_hello_proto_rawDescData
}

var file_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hello_proto_goTypes = []interface{}{
	(*Greet)(nil), // 0: hello.Greet
}
var file_hello_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_proto_init() }
func file_hello_proto_init() {
	if File_hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Greet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hello_proto_goTypes,
		DependencyIndexes: file_hello_proto_depIdxs,
		MessageInfos:      file_hello_proto_msgTypes,
	}.Build()
	File_hello_proto = out.File
	file_hello_proto_rawDesc = nil
	file_hello_proto_goTypes = nil
	file_hello_proto_depIdxs = nil
}
</pre>
</details>

Please let me know if I am missing anything obvious.

**Comment by dsnet** [comment] 2020-10-27 17:01
the `ProtoPackageIsVersion4` has nothing to do with the `google.golang.org/protobuf`. Therefore, it's expected that you won't find it in v1.25.0 (in fact you won't find it on version of that module).

The identifier is declared in the [`github.com/golang/protobuf`](https://pkg.go.dev/github.com/golang/protobuf/proto#ProtoPackageIsVersion4) module at v1.4.0 and above.

**Comment by dsnet** [comment] 2020-10-29 00:22
Closing as working as intended.

**Closed by dsnet** 2020-10-29 00:22 UTC

**Comment by puellanivis** [comment] 2020-10-29 12:02
As a bit of additional detail here, this is was an incompatibility between the `protoc-gen-go` binary installed on your machine, and the package version that you’re depending on, which was a regular source of issues.

It is not sufficient to just have the intended dependency in `go.mod` the actual binary used for your `protoc-gen-go` has to match that dependency.

This issue has mostly been fixed for this standalone protobuf package by making the protobuf package itself more backwards-forwards compatible, and moving the lock-step-change requirement over to `protoc-gen-go-grpc`.

**Comment by gkarthiks** [comment] 2020-11-03 20:29
Thanks @puellanivis  for the explanation.
