### ISSUE TITLE
Possible redundant range check on timestamp json formatting

### ISSUE THREAD

**Issue by amits1995** [golang/protobuf#775] opened 2018-12-20 16:12 UTC
**What version of protobuf and what language are you using?**
golang/protobuf 1d3f30b

**What did you do?**
Tried to marshal a protobuf message to json.  
One of the subfields was a protobuf timestamp  
The timestamp was coming from a java service via a grpc call.  
The timestamp represented a date before 1970, hence the `Nano` field had a negative value and I got a "out of range" error

**What did you expect to see?**
No error, just a nice formatted date :)

**What did you see instead?**
```
 ns out of range [0, 1000000000)
```
I don't understand why a negative nanoseconds value is not valid.  
The [docs](https://golang.org/pkg/time/#Unix) specifically say:
```
It is valid to pass nsec outside the range [0, 999999999]
```
Can we please drop [this check](https://github.com/golang/protobuf/blob/1d3f30b51784bec5aad268e59fd3c2fc1c2fe73f/jsonpb/jsonpb.go#L237)?

**Comment by amits1995** [comment] 2018-12-20 17:13
@puellanivis thanks for the quick response  
So I guess the problem is that my Java service is able to set negative Nanos, and that java protobuf doesn't make the same validation as this library

**Comment by dsnet** [comment] 2018-12-20 17:17
@puellanivis is correct. The [`timestamp.proto` further declares](https://github.com/protocolbuffers/protobuf/blob/043b99c74aa3f1d7cc475788a2472cc0cd999fdf/src/google/protobuf/timestamp.proto#L134-L135):
> Must be from 0 to 999,999,999 inclusive.

Closing as working as intended.

**Closed by dsnet** 2018-12-20 17:17 UTC
