### ISSUE TITLE
Adding all WKT types in protoc release to ptypes?

### ISSUE THREAD

**Issue by peter-edge** [golang/protobuf#476] opened 2017-12-20 15:08 UTC
See https://github.com/gogo/protobuf/issues/362

Before we do this, is there a reason not to? Will this potentially be a compatibility issue?

**Comment by awalterschulze** [comment] 2017-12-20 15:17
As long as the generated code does not import another library I can't see or remember how.  Why two separate issues?

**Comment by peter-edge** [comment] 2017-12-20 15:25
Hey, just wanted to check with the golang/protobuf folks to double check.

**Comment by awalterschulze** [comment] 2017-12-20 15:29
Oops my bad I thought this was an issue on gogoprotobuf :)

**Comment by dsnet** [comment] 2018-03-08 02:22
Closing as duplicate of #218.

**Closed by dsnet** 2018-03-08 02:22 UTC
