### ISSUE TITLE
Incorrect Import in plugin implementation

### ISSUE THREAD

**Issue by ehsannm** [golang/protobuf#1193] opened 2020-08-30 20:04 UTC
**What version of protobuf and what language are you using?**
Version 1.25.0

**What did you do?**
The GeneratedCode creates wrong import name:

g.QualifiedGoIdent(protogen.GoIdent{GoName: "", GoImportPath: "github.com/scylladb/gocqlx/v2"})

**What did you expect to see?**
import (
gocqlx "github.com/scylladb/gocqlx/v2"
)
OR
import (
    "github.com/scylladb/gocqlx/v2"
)

**What did you see instead?**
import (
  v2 "github.com/scylladb/gocqlx/v2"
)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

**Comment by ehsannm** [comment] 2020-08-30 20:20
I used a hack to fix it temporary:

`
pgo := protogen.Options{
		ParamFunc:         nil,
		ImportRewriteFunc: func(path protogen.GoImportPath) protogen.GoImportPath {
			switch path {
			case "github.com/scylladb/gocqlx/v2/gocqlx":
				return "github.com/scylladb/gocqlx/v2"
			}
			return path
		},
	}
`

and in the code used
`
g.QualifiedGoIdent(protogen.GoIdent{GoName: "", GoImportPath: "github.com/scylladb/gocqlx/v2/gocqlx"})
`

However I think the private function `baseName` must be fixed somehow to detect that last part is for go module version

**Comment by dsnet** [comment] 2020-08-30 20:24
Can you explain why this is "incorrect"? Within a Go source file, the code can rename import paths to any chosen local package names; and "v2" is a valid Go identifier and shouldn't cause any problems so long as it is unique within the context of where it is used.

**Comment by ehsannm** [comment] 2020-08-31 05:50
When I import a package like "github.com/scylladb/gocqlx/v2" I am actually using "gocqlx" but its version 2. I don't expect to use v2.FuncName in my code. Since the package name is not 'v2' it is 'gocqlx'. 

Imaging if we are going to use multiple versioned packages in our generated code. Then the code is full of vX.Identifier which is not semantic. As I mentioned in the comments, There is ImportRewriteFunc which help us to fix this issue manually but I think it could be fixed internally.

**Comment by dsnet** [comment] 2020-08-31 06:45
I'm okay with adjusting the heuristic for how `protogen` determines the local package names, but your description still seems to suggest that this is purely for cosmetic reasons since the "the code is full of vX.Identifier". Can you confirm that the code actually _functions_ correctly even if it doesn't _look_ like what is expected?

Essentially, I'd like to make sure there's not some deeper issue I'm not quite understanding. The purpose of `protogen` is not to generate code that always follows style guidelines. It's nice if possible, but it's not a goal.

**Comment by ehsannm** [comment] 2020-08-31 07:44
Yes, it works fine just cosmetic as you mentioned :) Since Golang is very conservative when it comes to clean code and syntax.
My suggestion is that Package names are better be optional or overridable by developer in the `QualifiedGoIdent` instead of using `ImportRewriteFunc`. However I am ok with the current configuration, just was not intuitive at first.

**Comment by puellanivis** [comment] 2020-09-08 08:43
But the only time this package rename would matter is if you’re editing a file that at the top says “DO NOT EDIT.”, right?

**Comment by dsnet** [comment] 2020-09-20 06:56
Closing as duplicate of #1205

**Closed by dsnet** 2020-09-20 06:56 UTC
