### ISSUE TITLE
jsonpb serialization does not handle all default values in a oneof

### ISSUE THREAD

**Issue by svelez** [golang/protobuf#1277] opened 2021-02-16 19:23 UTC
**What version of protobuf and what language are you using?**
Version: (e.g., `v1.1.0`, `89a0c16f`, etc)
v1.4.3

**What did you do?**
If possible, provide a recipe for reproducing the error.
A complete runnable program is good with `.proto` and `.go` source code.

Modify package unit tests in following way
```diff
diff --git a/internal/testprotos/jsonpb_proto/test2.proto b/internal/testprotos/jsonpb_proto/test2.proto
index d34dc33..f1639c8 100644
--- a/internal/testprotos/jsonpb_proto/test2.proto
+++ b/internal/testprotos/jsonpb_proto/test2.proto
@@ -91,6 +91,23 @@ message MsgWithOneof {
     string Country = 3;
     string home_address = 4;
     MsgWithRequired msg_with_required = 5;
+
+    // Known Types
+    google.protobuf.Any an = 6;
+    google.protobuf.Duration dur = 7;
+    google.protobuf.Struct st = 8;
+    google.protobuf.Timestamp ts = 9;
+    google.protobuf.ListValue lv = 10;
+    google.protobuf.Value val = 11;
+    google.protobuf.DoubleValue dbl = 12;
+    google.protobuf.FloatValue flt = 13;
+    google.protobuf.Int64Value i64 = 14;
+    google.protobuf.UInt64Value u64 = 15;
+    google.protobuf.Int32Value i32 = 16;
+    google.protobuf.UInt32Value u32 = 17;
+    google.protobuf.BoolValue bool = 18;
+    google.protobuf.StringValue str = 19;
+    google.protobuf.BytesValue bytes = 20;
   }
 }
 
diff --git a/jsonpb/json_test.go b/jsonpb/json_test.go
index 0ef23f2..745923a 100644
--- a/jsonpb/json_test.go
+++ b/jsonpb/json_test.go
@@ -505,6 +505,9 @@ var marshalingTests = []struct {
 
 	{"required", marshaler, &pb2.MsgWithRequired{Str: proto.String("hello")}, `{"str":"hello"}`},
 	{"required bytes", marshaler, &pb2.MsgWithRequiredBytes{Byts: []byte{}}, `{"byts":""}`},
+
+	{"emptyAnyOneof", marshaler, &pb2.MsgWithOneof{Union: &pb2.MsgWithOneof_An{}}, `{"an": {}}`},
+	{"emptyStructValOneof", marshaler, &pb2.MsgWithOneof{Union: &pb2.MsgWithOneof_Val{}}, `{"val": {}}`},
 }
 
 func TestMarshaling(t *testing.T) {
diff --git a/proto/text_test.go b/proto/text_test.go
index 3f6edc5..eb07a0e 100644
--- a/proto/text_test.go
+++ b/proto/text_test.go
@@ -15,6 +15,7 @@ import (
 	"github.com/golang/protobuf/proto"
 	"github.com/google/go-cmp/cmp"
 
+	jpbp "github.com/golang/protobuf/internal/testprotos/jsonpb_proto"
 	pb2 "github.com/golang/protobuf/internal/testprotos/proto2_proto"
 	pb3 "github.com/golang/protobuf/internal/testprotos/proto3_proto"
 	anypb "github.com/golang/protobuf/ptypes/any"
@@ -98,6 +99,9 @@ func makeGolden() []golden {
 		},
 	}
 
+	m7 := &jpbp.MsgWithOneof{Union: &jpbp.MsgWithOneof_An{}}
+	m8 := &jpbp.MsgWithOneof{Union: &jpbp.MsgWithOneof_Val{}}
+
 	const (
 		m1Golden = `
 name: "David"
@@ -174,6 +178,11 @@ many_things: <
   >
 >
 `
+		m7Golden = `an: <
+>`
+
+		m8Golden = `val: <
+>`
 	)
 	return []golden{
 		{m1, strings.TrimSpace(m1Golden) + "\n", strings.TrimSpace(compact(m1Golden)) + " "},
@@ -182,6 +191,8 @@ many_things: <
 		{m4, strings.TrimSpace(m4Golden) + "\n", strings.TrimSpace(compact(m4Golden)) + " "},
 		{m5, strings.TrimSpace(m5Golden) + "\n", strings.TrimSpace(compact(m5Golden)) + " "},
 		{m6, strings.TrimSpace(m6Golden) + "\n", strings.TrimSpace(compact(m6Golden)) + " "},
+		{m7, strings.TrimSpace(m7Golden) + "\n", strings.TrimSpace(compact(m7Golden)) + " "},
+		{m8, strings.TrimSpace(m8Golden) + "\n", strings.TrimSpace(compact(m8Golden)) + " "},
 	}
 }
```

**What did you expect to see?**

I expected the test `jsonpb/TestMarshaling` to pass like `proto/TestMarshalGolden` does

**What did you see instead?**

```
--- FAIL: TestMarshaling (0.00s)
    .../jsonpb/json_test.go:517: emptyAnyOneof: marshaling error: proto: not found
    ../jsonpb/json_test.go:517: emptyStructValOneof: marshaling error: nil Value
FAIL
FAIL	github.com/golang/protobuf/jsonpb	0.191s
FAIL

```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

In the process of updating to 1.4.x, but blocked by this issue... causing our tests to fail, though not sure how practical the workflow is.

**Comment by svelez** [comment] 2021-02-16 19:24
Forgot to mention that standard marshalling to actual protobufs works as well.

**Comment by puellanivis** [comment] 2021-02-17 14:20
I confused, I don’t understand what behavior you’re saying is being handled wrongly.

Is it that JSON marshalling does not accept the invalid values of an empty WKT for `any` and `value`? Because both of those require specific fields to be set. Their zero values are not actually valid.

**Comment by svelez** [comment] 2021-02-17 15:26
I completely understand that the zero values are not actually useful, but where is it stated that they are not valid and a violation of the protocol?

If you take these values and pas them to the text marshaller and the protobuf marshaller, you get marshalled representations that can be passed around to handle as clients see fit.

If you pass these values to the json marshaller, you get an error. 

I believe the 3 marshal functionalities should be consistent.

**Comment by svelez** [comment] 2021-02-17 15:37
Well, there is this
> A producer of value is expected to set one of that variants, absence of any variant indicates an error.
[here](https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/well-known-types/value)

I didn't see similar language on the documentation for `Any`

Though there still is the somewhat confusing case of the "errorness" being different based on what that target serialization format is.

I opened this issue primarily to get information on whether a PR to resolve it would be accepted.

If there is no reason to establish consistency in error generation, then I can probably just remove the test cases from my test suite (though they were passing in 1.3.x)

**Comment by puellanivis** [comment] 2021-02-18 01:28
Hm, indeed, it does not appear to be explicit that the zero value of an `Any` is invalid, but it is somewhat implied by the necessity of including the `"@type"` field, which must be a valid URL.

**Comment by dsnet** [comment] 2021-02-27 01:09
The "right" behavior is more or less driven by what the C++ implementation does. If we diverge in behavior, we can switch Go to be consistent, otherwise we'll close this as "working as intended".

**Comment by cybrcodr** [comment] 2021-02-27 02:10
First off, when using the generated oneof wrapper type, the user is expected to set the field in the wrapper type to signify the value for the oneof field.  Without it (field inside wrapper type) being set, it makes for a "strange" case of whether the intent was to really set the oneof field or not.  Hence, I think the issue here is of a misused API.

Now, regardless of the wrong usage, what is the current behavior.  I've not looked into what v1.3.x (APIv1) does.  But I just tried this out on APIv2 (google.golang.org/protobuf).  APIv2 treats a nil message as an empty message where there's ambiquity or should I say not possible in proto, because proto does not have a concept of a `nil` message.

Examples:
*  proto repeated message where in Go you have slice of messages and item is nil
*  map with message value where the value is nil.

Apparently, having set a oneof wrapper without setting the field falls under the same category.

(1) Hence a oneof Any field if set with the wrapper type triggers the oneof field being set even though the Any value is nil, the result is `{"an": {}}`.

(2) As @svelez pointed out for Value, ` absence of any variant indicates an error.`.  [APIv2 will return an error](https://go.googlesource.com/protobuf/+/refs/heads/master/encoding/protojson/well_known_types.go#497) if the oneof Value wrapper does not have its field set to a Value message with one of the field set inside it, in other words it is not valid to have an empty Value message.

The oneof wrapper type is a Go concept and not comparable to other languages.

**Closed** 2021-03-15 18:29 UTC
Labels: needs-investigation

**Comment by svelez** [comment] 2021-03-15 18:33
I can accept that this has been closed as the workflow is not useful, but the explanations don't really clarify why this _only_ fails in one serialization api... to json... not to protobuf or text.

**Comment by dsnet** [comment] 2021-03-15 18:46
Specialized behavior for WKT only occurs in JSON serialization.
