### ISSUE TITLE
Mention version/commit of protoc at the top [Code generated by protoc-gen-go. DO NOT EDIT.]

### ISSUE THREAD

**Issue by emailtovamos** [golang/protobuf#1200] opened 2020-09-04 10:10 UTC
**Is your feature request related to a problem? Please describe.**
It is usually not clear which version/commit generated the code [here](https://github.com/golang/protobuf/blob/e9dc0d72c1a35f349f6d6871842199ddaaaf9edc/internal/gengogrpc/grpc.go#L32). 

**Describe the solution you'd like**
Mention of the version/commit at the top would make things clear and easier to work with.

**Comment by dsnet** [comment] 2020-09-04 17:12
Duplicate of #524, which is already done for `google.golang.org/protobuf/cmd/protoc-gen-go`. There are no intentions to add this feature to `github.com/golang/protobuf/protoc-gen-go`.

**Closed by dsnet** 2020-09-04 17:12 UTC
