### ISSUE TITLE
The extremely frustrating experience with tags

### ISSUE THREAD

**Issue by gophobic** [golang/protobuf#1166] opened 2020-07-06 09:38 UTC
I don't know, is it because the intentional mediocre design of the language or is it really the package authors have no idea what they are doing and have no plan to improve things under the pretext of not wanting to break anything despite getting paid more than 99% of developers on Earth?

how one can set tags in generated code?!!!!!!!!!!!!!!!! by default the compiler sets json snake_case tags but what if I am required to have CamelCase? what about yaml? WTF? the whole experience is infuriating to say the least.

**Comment by neild** [comment] 2020-07-06 16:09
Duplicate of #52, see in particular https://github.com/golang/protobuf/issues/52#issuecomment-641412208.

**Closed by neild** 2020-07-06 16:09 UTC

**Comment by gophobic** [comment] 2020-07-06 19:05
@neild your comment in the other issue doesn't even seem consistent with the fact that you actually already messed with tags creating snake_case json tags. This 5 year old issue is simply unsolvable because you have no intention to put the slightest effort to solve it because it's not a Google issue so simply your job won't be affected by it.

**Comment by dsnet** [comment] 2020-07-06 19:12
@gophobic, I recommend reading and abiding by the [code of code](https://golang.org/conduct).

There are a few assertions made here that are questionable:
1) assertions that we have no idea we are doing,
2) assertions about how much we are paid,
3) the assertion that @neild was the one who "messed" with the `json` tags,
4) etc...

Locking this issue as it is unfruitful.
