### ISSUE TITLE
`proto.Merge` != `proto.Marshal`, `proto.Unmarshal`

### ISSUE THREAD

**Issue by DazWilkin** [golang/protobuf#1163] opened 2020-06-30 19:49 UTC
This **isn't** a blocking issue for me but results from my developing familiarity with the golang protobuf SDK and a solution I'm toying with. In this solution, the clients succeeds by marshaling the `dynamicpb.Message` onto the wire and shipping this to the server; I **don't** need to be able to convert the `dynamicpb.Message` into `ComplexRequest`.

I am curious as to why this doesn't work.

If this appears curious to you too, I'm motivated to help pursue it.

If not, please feel free to just close it.

**What version of protobuf and what language are you using?**

```console
go version
go version go1.14 linux/amd64

protoc --version
libprotoc 3.12.3
```

go.mod:

```
module complex

go 1.14

require (
	github.com/golang/protobuf v1.4.2
	google.golang.org/grpc v1.30.0
	google.golang.org/protobuf v1.25.0
)
```

**What did you do?**

```protobuf
syntax = "proto3";

package examples;

option go_package = "complex/protos";

service ComplexService {
    rpc add(ComplexRequest) returns (ComplexResponse);
    rpc sub(ComplexRequest) returns (ComplexResponse);
    rpc mul(ComplexRequest) returns (ComplexResponse);
    rpc div(ComplexRequest) returns (ComplexResponse);
}

message ComplexRequest {
    Complex a = 1;
    Complex b = 2;
}

message ComplexResponse {
    Complex result = 1;
    string error = 2;
}

message Complex {
    float real = 1;
    float imag = 2;
}
```

and:

```bash
protoc \
--proto_path=./protos \
--descriptor_set_out=./protos/descriptor.pb \
--go_out=plugins=grpc,module=[[PROJECT]]:. \
protos/complex.proto
```

and (with apologies for the big slab of code):

```golang
package main

import (
	"context"
	"flag"
	"io/ioutil"
	"log"

	pb "complex/protos"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/dynamicpb"
)

var (
	descriptorFile = flag.String("descriptor_file", "", "Descriptor filename")
)

func main() {

	flag.Parse()
	// Open the descriptor
	log.Println(*descriptorFile)

	fds := &descriptorpb.FileDescriptorSet{}
	{
		b, _ := ioutil.ReadFile(*descriptorFile)
		proto.Unmarshal(b, fds)
	}

	files, _ := protodesc.NewFiles(fds)
	d, _ := files.FindDescriptorByName(protoreflect.FullName("examples.ComplexService"))
	s, ok := d.(protoreflect.ServiceDescriptor)
	if !ok {
		log.Fatal("Unable to assert into ServiceDescriptor")
	}

	md := s.Methods().ByName(protoreflect.Name("add"))

	// Create dynamic message from service's input method
	i := md.Input()
	src := dynamicpb.NewMessage(i) // == examples.ComplexRequest

	{
		fd := i.Fields().ByName(protoreflect.Name("a"))
		if fd.Kind() != protoreflect.MessageKind {
			log.Fatal("Expect `a` to be a Message of type Complex")
		}
		a := fd.Message()
		m := dynamicpb.NewMessage(a)
		{
			fd := a.Fields().ByName(protoreflect.Name("real"))
			m.Set(fd, protoreflect.ValueOfFloat32(39))
		}

		{
			fd := a.Fields().ByName(protoreflect.Name("imag"))
			m.Set(fd, protoreflect.ValueOfFloat32(3))
		}
		// m := pb.Complex{Real: 39, Imag: 3}
		x := m.ProtoReflect()
		v := protoreflect.ValueOfMessage(x)
		src.Set(fd, v)
	}
	{
		fd := i.Fields().ByName(protoreflect.Name("b"))
		m := pb.Complex{Real: 39, Imag: 3}
		x := m.ProtoReflect()
		v := protoreflect.ValueOfMessage(x)
		src.Set(fd, v)
	}

	dst := &pb.ComplexRequest{}
```

This:

```golang

	proto.Merge(dst, src)
```

panics:

```console
panic: descriptor mismatch

goroutine 1 [running]:
google.golang.org/protobuf/proto.Merge(0xc16140, 0xc000035e80, 0xc16c60, 0xc000035e00)
	/home/dazwilkin/go/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/merge.go:34 +0x470
main.main()
```

Here: https://github.com/protocolbuffers/protobuf-go/blob/3f7a61f89bb6813f89d981d1870ed68da0b3c3f1/proto/merge.go#L34

The `Fullname()` values match but elsewhere the `Descriptor()` values disagree.

But, the described equivalent (albeit without `proto.UnmarshalOptions{Merge:true}`):

https://github.com/protocolbuffers/protobuf-go/blob/v1.25.0/proto/merge.go#L25

```golang
	{
		b, err := proto.Marshal(src)
		if err != nil {
			log.Fatal(err)
		}

		if err := proto.Unmarshal(b, dst); err != nil {
			log.Fatal(err)
		}
	}
```

Succeeds:

```console
2020/06/30 12:26:53 result:{real:1512 imag:234}
```

**What did you expect to see?**

Success to be 'equivalent' `Marshal` (of `dynamicpb`) followed by `Unmarshal` (into `examples.ComplexRequest`).

**What did you see instead?**

`Merge` panics.

**Anything else we should know about your project / environment?**

The `src` and `dst` structs are rather deep and so it's not immediately obvious where the discrepancy arises (perhaps a good next step for me?)

If I output the objects, they appear (!?) to match:

```golang
log.Printf("[dst] %+v", dst.ProtoReflect().Descriptor())
log.Printf("[src] %+v", src.ProtoReflect().Descriptor())
```

yields:

```console
2020/06/30 12:34:11 [dst] MessageDescriptor{
	Syntax:   proto3
	FullName: examples.ComplexRequest
	Fields: [{
		Name:        a
		Number:      1
		Cardinality: optional
		Kind:        message
		HasJSONName: true
		JSONName:    "a"
		HasPresence: true
		Message:     examples.Complex
	}, {
		Name:        b
		Number:      2
		Cardinality: optional
		Kind:        message
		HasJSONName: true
		JSONName:    "b"
		HasPresence: true
		Message:     examples.Complex
	}]
}
2020/06/30 12:34:11 [src] MessageDescriptor{
	Syntax:   proto3
	FullName: examples.ComplexRequest
	Fields: [{
		Name:        a
		Number:      1
		Cardinality: optional
		Kind:        message
		HasJSONName: true
		JSONName:    "a"
		HasPresence: true
		Message:     examples.Complex
	}, {
		Name:        b
		Number:      2
		Cardinality: optional
		Kind:        message
		HasJSONName: true
		JSONName:    "b"
		HasPresence: true
		Message:     examples.Complex
	}]
}
```

I wonder whether part of my issue is that `ComplexRequest` contains a nested Message[Descriptor|Type] of `Complex`?

**Comment by dsnet** [comment] 2020-06-30 20:18
Determining whether two descriptors are "identical" is challenging. The logic in `proto.Merge` simply checks for equality on the descriptor using the `==` operator (i.e., they must be the _exact_ same descriptor). Expanding this to handle looser definitions leads to a nest of potential issues since we now need to define what "equal" descriptors mean:
* Do we simply check the full name? what if they match, but the rest of the descriptor doesn't? This is still a type error.
* Do we walk through the descriptor contents and verify that it matches? Do we only check information at a shallow level within the current descriptor? Do we also descend recursively into referenced sub-types? How are cycles in the type-graph handled?
* What information do we need to be equal? What about field attributes that don't affect its memory representation like whether a repeated field is packed? What about options?
* If we do recurse through everything, how do we prevent O(n^2) behavior recursing through the entire type descriptor at every level of the message value? Do we now add a type-cache of descriptors that we know to be equal?

Answering these is hard and any answer is likely to have significant performance implications, weird correctness edge-cases, or both.

It's probably easier (and faster) to just marshal the source message and unmarshal the bytes into the destination message.

**Comment by DazWilkin** [comment] 2020-06-30 20:25
You're awesome.

Thanks very much for taking the time (again) to help me understand this.

**Comment by DazWilkin** [comment] 2020-06-30 20:34
Before you replied, I tried [github.com/go-test/deep](https://github.com/go-test/deep)

Somewhat (!?) interestingly, (in this case) `dstD.Base.L0.ParentFile.L1.[Enums|Messages|Extensions|Services]` are all `nil`

Whereas `srcD.Base.L0.ParentFile.L1.[Enums|Messages|Extensions|Services]` are all `[]`

Recursively.

```console
2020/06/30 13:27:59 Base.L0.ParentFile.L1.Enums.List: <nil slice> != []
2020/06/30 13:27:59 Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Enums.List: <nil slice> != []
2020/06/30 13:27:59 Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Enums.List: <nil slice> != []
2020/06/30 13:27:59 Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Enums.List: <nil slice> != []
2020/06/30 13:27:59 Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Enums.List: <nil slice> != []
2020/06/30 13:27:59 Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Enums.List: <nil slice> != []
2020/06/30 13:27:59 Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Enums.List: <nil slice> != []
2020/06/30 13:27:59 Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Enums.List: <nil slice> != []
2020/06/30 13:27:59 Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Enums.List: <nil slice> != []
2020/06/30 13:27:59 Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Messages.List.slice[0].Base.L0.ParentFile.L1.Enums.List: <nil slice> != []
```

**Comment by dsnet** [comment] 2020-06-30 21:15
I dont find that surprising given that its just an implementation detail on the `internal/filedesc` types.

**Comment by DazWilkin** [comment] 2020-07-01 17:44
There may be a deeper reason for this and I defer (respectively) to your experience.

What puzzles me is that -- I suspect -- initialization differs (some structs are `[]` and some are `nil`) but should not.

In my (toy) proto:

```proto
syntax = "proto3";

package examples;

option go_package = "complex/protos";

service ComplexService {
    rpc add(ComplexRequest) returns (ComplexResponse);
    rpc sub(ComplexRequest) returns (ComplexResponse);
    rpc mul(ComplexRequest) returns (ComplexResponse);
    rpc div(ComplexRequest) returns (ComplexResponse);
}

message ComplexRequest {
    Complex a = 1;
    Complex b = 2;
}

message ComplexResponse {
    Complex result = 1;
    string error = 2;
}

message Complex {
    float real = 1;
    float imag = 2;
}
```

There are:

|Type|Number|`srcD`|`dstD`|Diff|
|-----|:----:|---|---|----|
|Enums|0|`[]` (length:**0**)|`nil`|⟵|
|Messages|3|`[]` (length:3)|`[]` (length:3)||
|Extensions|0|`[]` (length:**0**)|`nil`|⟵|
|Services|1|`[]` (length:1)|`[]` (length:1)||

Taking just a small slither of the structures:

|Name|Type|
|----|----|
|`srcD`|`dynamicpb.NewMessage(...).ProtoReflect().Descriptor()`|
|`dstD`|`examples.ComplexRequest{}.ProtoReflect().Descriptor()`|

`srcD` appears to always initialize fields to `[]` whereas a regular `struct{}` does not initialize fields (`nil`).

This breaks the equality test that is a precursor of `proto.Merge`

#### Propose:

`internal.filedesc` should not `make([]X, 0, ...)`

**Comment by dsnet** [comment] 2020-07-01 18:00
As stated earlier, the difference between a `nil` slice and an empty, but non-nil slice is an implementation detail of `internal/protodesc`.

The [`Merge` logic uses the `==` operator](https://github.com/protocolbuffers/protobuf-go/blob/master/proto/merge.go#L30) of descriptors. The descriptor types are pointers to internal types. The `==` operator in Go does not descend into pointers.

**Comment by dsnet** [comment] 2020-07-06 16:19
Closing this as infeasible and/or working as intended:
1. It's "infeasible" due to the technical complexities described in https://github.com/golang/protobuf/issues/1163#issuecomment-652020747. The current logic of `Merge` is not particularly complicated, being [around 100 LOC](https://github.com/protocolbuffers/protobuf-go/blob/1f5b6fe64530cac2061a3d315b7e44966b1a200b/proto/merge.go). Supporting this feature would grow that complexity by an order of magnitude.
2. There's a reasonable workaround by simply marshaling the message and unmarshaling it again.

**Closed by dsnet** 2020-07-06 16:19 UTC
