### ISSUE TITLE
proto: nil pointer panic with unknown fields

### ISSUE THREAD

**Issue by yanxyc** [golang/protobuf#1187] opened 2020-08-14 04:05 UTC
**What version of protobuf and what language are you using?**
protobuf-go v1.23.0

**What did you do?**
https://github.com/protocolbuffers/protobuf-go/blob/v1.23.0/internal/impl/encode.go
![image](https://user-images.githubusercontent.com/14138676/90212572-3f479200-de26-11ea-9e16-a238825f91d6.png)
p.Apply(mi.unknownOffset).Bytes() might return a nil pointer，append() will appear panic
panic: runtime error: invalid memory address or nil pointer dereference
![image](https://user-images.githubusercontent.com/14138676/90216877-50969b80-de32-11ea-8961-a4164cdb66a1.png)

**What did you expect to see?**
need add nil pointer check

**Anything else we should know about your project / environment?**
go version go1.13.5 darwin/amd64
runtime: Linux ali-jump 2.6.32-696.10.1.el6.x86_64 #1 SMP Tue Aug 22 18:51:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dsnet** [comment] 2020-08-14 17:01
Do you have a reproduction for this? The line you are referencing is not the problem since it assumes that `p` itself is already a non-nil pointer. Thus, a nil pointer must have slipped in from elsewhere.

**Comment by yanxyc** [comment] 2020-08-15 07:15
What does Reproduction mean？
The problem is not necessarily present, But once it happens, it lasts for a while.
Presumably when GRPC calls the Marshal(), because goroutine that has been started at the time of the request timeout did not end immediately, and this goroutine was modifying this protobuff object?

**Comment by yanxyc** [comment] 2020-08-15 07:16
> Do you have a reproduction for this? The line you are referencing is not the problem since it assumes that `p` itself is already a non-nil pointer. Thus, a nil pointer must have slipped in from elsewhere. Without a reproduction, it will be difficult to diagnose this.

What does Reproduction mean？
The problem is not necessarily present, But once it happens, it lasts for a while.
Presumably when GRPC calls the Marshal(), because goroutine that has been started at the time of the request timeout did not end immediately, and this goroutine was modifying this protobuff object?

**Comment by dsnet** [comment] 2020-08-15 17:14
> goroutine that has been started at the time of the request timeout did not end immediately, and this goroutine was modifying this protobuff object?

If another Go routine in modifying the same message while you are marshaling it, then that is fundamentally a race condition and expected to fail, cause memory corruption, or other strange side effects.

**Comment by puellanivis** [comment] 2020-08-16 11:19
> The problem is not necessarily present,…

Indeed, this suggests a race condition. If you are spinning off a separate goroutine for a request, then it is your responsibly to ensure that the main-goroutine of your gRPC call does not return until all contingient goroutines have completed. (Through a `sync.Wait` or some other mechanism.)

**Comment by yanxyc** [comment] 2020-08-16 13:10
> >  the main-goroutine of your gRPC call does not return until all contingient goroutines have completed

You're right!  I'll have to change it. Thanks~

**Comment by dsnet** [comment] 2020-08-16 17:55
Marking as resolved since this is an issue in the application code.

**Closed by dsnet** 2020-08-16 17:55 UTC
Labels: waiting-for-info
