### ISSUE TITLE
proto.Equal potentially differs between 1.3.5/1.4.0

### ISSUE THREAD

**Issue by bufdev** [golang/protobuf#1120] opened 2020-05-09 17:57 UTC
The issue in summary:

If you have a dynamically-created `FileDescriptorSet` with a value that uses an extension, and use `proto.Marshal` or `proto.Equal` without registering the extension using `protoregistry.GlobalTypes.RegisterExtension`, the extension value will not be marshalled or considered for `Equal`.

For JSON or text, you can attach dynamic resolvers via `MarshalOptions`, but this is not possible with wire, so the only way to handle this issue is to use `protoregistry.GlobalTypes`.

Some art on this:

https://github.com/bufbuild/buf/blob/proto-v2/internal/buf/bufbuild/builder_test.go#L49
https://github.com/bufbuild/buf/blob/proto-v2/internal/buf/bufbuild/builder_test.go#L150
https://github.com/bufbuild/buf/blob/proto-v2/internal/pkg/util/utilproto/utilproto.go#L43

If the `init()` function is commented out, this test fails as `proto.Equal` and `Marshal.Wire` comparison as extension 50007 with value 42 is not considered to be present.

**Comment by bufdev** [comment] 2020-05-09 18:05
A note: the `proto.Equal` behavior is the same in 1.3.5 as 1.4.0/v2, but the `proto.Marshal` behavior is different - if I do not have the extension registered with `RegisterExtension` in 1.3.5, `proto.Marshal` still correctly marshals the extension value, while in 1.4.0/v2, it does not (hence https://github.com/bufbuild/buf/issues/52).

**Comment by bufdev** [comment] 2020-05-10 04:02
Update: this was not a golang/protobuf issue, this is my mistake! I had a (hopefully momentary) brain lapse here!

**Comment by jhump** [comment] 2020-05-11 12:51
There actually may be an issue in here. But part of it depends on what is the expected behavior of `proto.Equal` when one of the messages has unrecognized fields and the other does not.

I could have sworn the v1.3 and earlier versions did what you'd expect: the messages were not equal if they had different unrecognized bytes. But I could be wrong and perhaps it's not even expected that they examine (since they'd have to compare based on byte values, which may be incorrect per proto semantics -- since, for example, two equal messages can be represented by unequal byte sequences).

But v1.4 definitely ignores unrecognized fields. That's why the `protoparse` tests pass with protobuf v1.4, even though it was producing descriptors that lacked the expected unrecognized bytes for custom options.

**Comment by bufdev** [comment] 2020-05-11 20:25
Updated issue to reflect the only actual potential issue here

**Comment by dsnet** [comment] 2020-05-11 23:31
(FYI: The referenced source code in the original post are dead links)

I haven't dug into the issue yet, but I suspect the issue is the switch from lazy extension handling (in v1.3.x and before) to eager extension handling (in v1.4.x and after) where extensions are handled eagerly at `proto.Unmarshal` time, rather than being deferred to latter during at first `proto.GetExtension` call. The switch to eager extension handling was 1) for compliance, since it's what all the other language implementations do, and 2) for correctness, since lazy handling was implicated as the source of a number of bugs. (Looking at the release notes, it seems we forgot to mention this since it was one the first changes we made when developing v1.4.x)

In v1.3.x, the unknown fields were primarily populated by `proto.Unmarshal`. The switch to eager extension handling should have had a transparent effect on `proto.Equal`. In v1.3.x, `proto.Equal` would automatically try to unmarshal the extensions from the unknown fields, while in v1.4.x, `proto.Equal` would assume that they have already be eagerly handled. As far as I can tell, the only way this behavior change can be observed between v1.3.x and v1.4.x is if unknown fields were injected into message outside of normal means. Is that what's happening in these tests?

**Comment by bufdev** [comment] 2020-05-11 23:59
Sorry about the dead links! I merged the branch, shouldn't have linked to it

**Comment by jhump** [comment] 2020-05-12 02:24
> As far as I can tell, the only way this behavior change can be observed between v1.3.x and v1.4.x is if unknown fields were injected into message outside of normal means. Is that what's happening in these tests?

Yep, that's what is happening. My `protoparse` package hasn't been updated to APIv2. And APIv1 doesn't have a resolver, for helping unmarshal operations identify extensions. So when it parses custom options into a descriptor proto, the only way it can store the data is to inject it directly to the unrecognized fields. Since it's _not_ using a resolver, trying to use unmarshal (instead of directly storing into unrecognized fields) would be of no help, and they'd still end up as unrecognized fields.

**Comment by dsnet** [comment] 2020-05-12 03:37
> Since it's not using a resolver, trying to use unmarshal (instead of directly storing into unrecognized fields) would be of no help, and they'd still end up as unrecognized fields.

Is there a reason not to just `UnmarshalMerge` the raw bytes into the target message? If there is any observable behavior difference between v1.3.x and v1.4.x, it means that the extension must be registered in order for the v1.3.x implementation of `proto.Equal` to automatically introspect upon the unknown extensions. And if the extension is registered, then `UnmarshalMerge` would be able to convert the raw bytes into a structured extension so that `proto.Equal` on v1.4.x functions as you would expect.

**Comment by jhump** [comment] 2020-05-12 11:29
> And if the extension is registered ...

I don't think I actually want this code path taken. We're parsing source, so if the source definition varies from any registered version, we need to prefer what's in the source for this to be correct. 

Also, I would imagine it's exceedingly rare for them to ever be registered in this context. So they still end up as unrecognized fields. The only meaningful difference I can think of between what I'm doing and unmarshaling is that, in v1.3.x, they end up as unparsed blobs in an extension map when unmarshaling (since the tags are identified as in an extension range).

**Comment by dsnet** [comment] 2020-05-12 18:26
I'm inclined to say that the new `proto.Equal` behavior is working as intended. In order for this behavior to be observable, it requires injecting unknown fields through unsupported means. To be fair, the `github.com/golang/protobuf` API didn't exactly give users any other way, but the `google.golang.org/protobuf` is aiming to provide consistent behavior and feature sets. It's unfortunate that a regression here is observable, but the new behavior is much simpler and removes the potential for a number of other classes of bugs.

**Comment by dsnet** [comment] 2020-05-17 19:29
Closing as "working as intended".

**Closed by dsnet** 2020-05-17 19:29 UTC

**Comment by jhump** [comment] 2020-06-04 16:05
> it requires injecting unknown fields through unsupported means

Is this true though? Wouldn't this also be observed when using the `SetUnknown(RawFields)` method on `protoreflect.Message`? Isn't that supported?

If this can be observed using that supported mechanism, then I think this is an inadvertent incompatibility. Here's the step in v1.3.5 that I think is now missing: https://github.com/golang/protobuf/blob/84668698ea25b64748563aa20726db66a6b8d299/proto/equal.go#L140

Or is the issue that the compatibility layer for messages generated w/ pre-1.4 protoc-gen-go doesn't support the unknown-field related reflection methods?

**Comment by dsnet** [comment] 2020-06-04 19:27
> Wouldn't this also be observed when using the SetUnknown(RawFields) method on protoreflect.Message? 

It would have been impossible for someone to use the `SetUnknown` API on v1.3.x and below since the `SetUnknown` API requires `google.golang.org/protobuf` module, which imposes a minimum version constraint on v1.4.x and higher.

**Comment by jhump** [comment] 2020-06-04 19:44
Okay. What about unmarshaling two messages whose only differences are in unrecognized fields? That would have been supported pre-1.4 and would now be handled differently/incompatibly, right?

**Comment by dsnet** [comment] 2020-06-04 20:11
>That would have been supported pre-1.4 and would now be handled differently/incompatibly, right?

There was a slight behavior change here.

In <1.4, the functional behavior was to [perform `bytes.Equal` on `XXX_unrecognized`.](https://github.com/golang/protobuf/blob/84668698ea25b64748563aa20726db66a6b8d299/proto/equal.go#L133-L140)
In >=1.4, the functional behavior is to [obtain the unknown fields from both messages](https://github.com/protocolbuffers/protobuf-go/blob/69839c78c3baff8f1fb37f37b24127ecae185e03/proto/equal.go#L70) and do a [set comparison on the unknown fields](https://github.com/protocolbuffers/protobuf-go/blob/69839c78c3baff8f1fb37f37b24127ecae185e03/proto/equal.go#L131-L154).

The difference is small. Essentially >=1.4 may report a few more cases as equal than <1.4 would have. However, I don't believe this behavior change is related to the behavior change that this issue is originally about.

**Comment by jhump** [comment] 2020-06-04 20:44
Okay. I was trying to understand why I observed what I observed, where it appeared that v1.4 was ignoring unrecognized fields. But I think I see now. The switch to v1.4 also implicitly included a switch to generated structs for `descriptor.proto` messages that did _not_ have an `XXX_unrecognized` field. And it was a `FieldOptions` message where I was seeing the behavior.

Thanks for humoring my questions!
