### ISSUE TITLE
Add Tags to protobuf/reflect

### ISSUE THREAD

**Issue by joesonw** [golang/protobuf#1282] opened 2021-02-25 04:48 UTC
**Is your feature request related to a problem? Please describe.**
Allow attach tags to `protoobuf/reflect` and have them being injected into final `*.pb.go` can easily allow inject custom tags.

**Describe the solution you'd like**
 * [ ] add tags to FieldDescriptor
 * [ ] populate tags in generated `.pb.go` in [protoprotocolbuffers/protobuf-go](https://github.com/protocolbuffers/protobuf-go) (specifically [here](https://github.com/protocolbuffers/protobuf-go/blob/master/cmd/protoc-gen-go/internal_gengo/main.go#L363))

This allows custom plugins to modify FieldDescriptor tags and wrap `protoc-gen-go`'s `GenerateFile` thus enables injecting custom tags.

**Describe alternatives you've considered**
All existing methods of injecting tags end up replacing generated go files.

**Additional context**
#52 it has being long requested.

**Comment by dsnet** [comment] 2021-02-26 01:06
Closing as duplicate of #52. There is no need to keep duplicate issues around.

**Closed by dsnet** 2021-02-26 01:06 UTC
