### ISSUE TITLE
proto.Merge supports overriding by default value for wrapped type

### ISSUE THREAD

**Issue by penglei** [golang/protobuf#1127] opened 2020-05-13 09:46 UTC
proto3 can't distinguish between the absence of a primitive typed field and its default value.  
The merge operation doesn't override the value by primitive default value in wrapped type. 
I think there would be less confusion if merge operation added this feature. 

I made a [change](https://github.com/penglei/protobuf/commit/cb43e120de0c1810716fc3ea5b1c34b153a151ff) here.

**Comment by dsnet** [comment] 2020-05-13 16:57
Thanks for the report, but this behavior cannot change because the semantics of how merge operates is not up to the Go implementation to decide.

Roughly speaking, merge(dst, src) is functionally equivalent to a unmarshal(marshal(src), dst) and the semantics today is derived from how the wire format merges scalars in proto3.

If you need true presence in proto3, I recommend keeping a watchful eye for [`protoc` v3.12](https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0-rc1) (which adds experimental support for [proto3 optional](https://github.com/protocolbuffers/protobuf/blob/v3.12.0-rc1/docs/field_presence.md)) and for an eventual `protoc` v3.13 (which plans to add stable support for proto3 optional).

Closing this as working as intended.

**Closed by dsnet** 2020-05-13 16:57 UTC
