### ISSUE TITLE
protoc-gen-go: problem with import cycle not allowed

### ISSUE THREAD

**Issue by krivenok** [golang/protobuf#349] opened 2017-05-15 14:38 UTC
Hello,
I have 3 simple proto files, one providing a common type and the other two consuming it.
```
syntax = "proto3";
package base;
option go_package = "basepb";

enum Base {
    B1 = 0;
    B2 = 1;
    B3 = 2;
 }
```

```
syntax = "proto3";
package a;
option go_package = "apb";

import "base.proto";

message A {
    base.Base a = 1;
}
```
```
syntax = "proto3";
package b;
option go_package = "bpb";

import "base.proto";

message B {
    base.Base b = 1;
}
```

I generate go code as follows from GOPATH directory:
```
$ protoc --go_out=src/basepb base.proto 
$ protoc --go_out=src/apb a.proto 
$ protoc --go_out=src/bpb b.proto 
```

Then I try to import those generated packages into simple go program:
```
package main

import "apb"
import "bpb"

func main() {
        return
}
```
And I get the following errors during compilation:
```
$ go build test.go 
import cycle not allowed
package main
        imports apb
        imports .
        imports .
import cycle not allowed
package main
        imports bpb
        imports .
        imports .
/home/c4dev/GOPATH/src/apb/a.pb.go:19:8: local import "." in non-local package
/home/c4dev/GOPATH/src/bpb/b.pb.go:19:8: local import "." in non-local package
$
```

I tried different things and searched through the google trying to find the correct way to achieve what I need, but didn't manage to find the solution.

I see this in generated code:
```
14 package apb
15 
16 import proto "github.com/golang/protobuf/proto"
17 import fmt "fmt"
18 import math "math"
19 import base "."
```
which doesn't look correct.

The ultimate goal is to be able to avoid code duplication and use common types in different proto files. Am I missing something obvious in my examples? If so, can someone please suggest correct way?

Thanks in advance!

**Comment by dsnet** [comment] 2018-08-18 06:52
This seems to be a duplicate of #646. It's not exactly clear what's causing it, but I suspect that imports from the same directory as the source confuses `protoc-gen-go` in such a way that it does not realize that remote type is not in the same package.

However, sufficiently complex projects generally don't run into this problem. It's kind of frustration though for simple projects trying to test out some feature of Go protobufs.

**Closed by dsnet** 2018-08-18 06:52 UTC
Labels: needs-investigation
