### ISSUE TITLE
please use "google.golang.org/protobuf/proto" instead of "github.com/golang/protobuf/proto" in pb.go

### ISSUE THREAD

**Issue by chengdanhao** [golang/protobuf#1150] opened 2020-06-18 03:54 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

golanglint-ci report a warning

SA1019: Package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (staticcheck)
	"github.com/golang/protobuf/proto"

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dsnet** [comment] 2020-06-21 07:37
Duplicate of #1077. Per the discussion in that thread, staticcheck has been modified to specially ignore this warning in generated `.pb.go` files. Please update your version of staticcheck.

**Closed by dsnet** 2020-06-21 07:37 UTC

**Comment by dlmufei** [comment] 2020-11-04 15:39
http://www.gosearch.tech/sa1019-package-github-com-golang-protobuf-proto-is-deprecated/
