### ISSUE TITLE
The serialization performance of Pb is worse than that of JSON

### ISSUE THREAD

**Issue by StarCsu** [golang/protobuf#1338] opened 2021-07-08 12:56 UTC
**What version of protobuf and what language are you using?**
github.com/golang/protobuf v1.5.2 golang 1.16
**What did you do?**
Today I test the serialization and deserialization performance of Pb and JSON，I found a problem，when proto is large,PB performance is worse than JSON,pb serialization size is  200 bytes，and json size is 603 bytes.
![image](https://user-images.githubusercontent.com/26735787/124924273-df556d80-e02d-11eb-8660-2763ec33ebda.png)

PB allocs is so many ,There should be something that can be optimized here。
Here are two analysis results：
![image](https://user-images.githubusercontent.com/26735787/124925169-c00b1000-e02e-11eb-91d6-693eb36c069b.png)
![image](https://user-images.githubusercontent.com/26735787/124925258-d618d080-e02e-11eb-9eaf-bfe94d0676ff.png)

**Anything else we should know about your project / environment?**
macOS

**Comment by puellanivis** [comment] 2021-07-08 13:02
There are a great number of factors that can influence the performance of benchmarks, and without any of that, it’s difficult to assess exactly what is causing the results you’re showing. Could you produce some sort of minimal-ish example that we could compare ourselves?

**Comment by StarCsu** [comment] 2021-07-08 14:01
> There are a great number of factors that can influence the performance of benchmarks, and without any of that, it’s difficult to assess exactly what is causing the results you’re showing. Could you produce some sort of minimal-ish example that we could compare ourselves?

I can't disclose the company's proto content, but tomorrow I can write a new test proto and send it to you.Do you only need my test code?

**Comment by puellanivis** [comment] 2021-07-08 14:03
Yes, some sort of representative code so we can see the outline of what you’re doing, and some benchmarks along with so we can see consistent results to what you present.

**Comment by StarCsu** [comment] 2021-07-08 14:25
> There are a great number of factors that can influence the performance of benchmarks, and without any of that, it’s difficult to assess exactly what is causing the results you’re showing. Could you produce some sort of minimal-ish example that we could compare ourselves?

I'm not in the company now. I write a similar test case；Our proto defines a structure slice, and I set the slice length to 200

`package client
import(
	"github.com/golang/protobuf/proto"
)

var testStruct =struct{field []string}{field: make([]string,200)}
func pbMarshal(){
	proto.Marshal(&testStruct)
}`


`package client

import "testing"

func BenchmarkPBMarshal(b *testing.B){
	for i:=0;i<b.N;i++ {
		pbMarshal()
	}
}`

**Comment by dsnet** [comment] 2021-07-09 06:45
This is comparing the use of `encoding/json` (which is a practice we discourage) compared to the binary serialization accessed through `github.com/golang/protobuf/proto`. The former relies on Go reflection, while the latter uses unsafe. The latter is always going to be faster than the former and the former will always be using pure Go reflection for safety reasons.

Also, this module is not responsible for the implementation of `encoding/json`.

**Comment by StarCsu** [comment] 2021-07-09 07:56
> This is comparing the use of `encoding/json` (which is a practice we discourage) compared to the binary serialization accessed through `github.com/golang/protobuf/proto`. The former relies on Go reflection, while the latter uses unsafe. The latter is always going to be faster than the former and the former will always be using pure Go reflection for safety reasons.
> 
> Also, this module is not responsible for the implementation of `encoding/json`.

Ha ha ha, did you read the wrong content? I posted JSON faster than Pb, which is incomprehensible

**Comment by dsnet** [comment] 2021-07-09 08:03
My apologies. It's easy to switch up which is which.

Can you use `google.golang.org/protobuf/proto` instead of `github.com/golang/protobuf/proto`?

Your perf profile is unhelpful. I should note that messages not generated by `protoc-gen-go` will have performance detriments since the logic goes through compatibility logic to preserve correctness at the expense of performance.

**Comment by dsnet** [comment] 2021-07-09 08:07
It almost seems certain that this is either operating on extremely old `protoc-gen-go` messages or messages not generated by `protoc-gen-go` since a bulk of time is spent in `sizePointerSlow` which won't happen for new messages. It goes through this logic when the sizecache field is not available. In that situation, the performance may be quadratic.

**Comment by StarCsu** [comment] 2021-07-09 08:35
> My apologies. It's easy to switch up which is which.
> 
> Can you use `google.golang.org/protobuf/proto` instead of `github.com/golang/protobuf/proto`?
> 
> Your perf profile is unhelpful. I should note that messages not generated by `protoc-gen-go` will have performance detriments since the logic goes through compatibility logic to preserve correctness at the expense of performance.

i can't use google.golang.org/protobuf/proto to serialize. Our proto code doesn't implement this method.

![image](https://user-images.githubusercontent.com/26735787/125048551-a15e5500-e0d2-11eb-9387-a27d68434efd.png)

Here is part of our protocol code：
![image](https://user-images.githubusercontent.com/26735787/125049318-70325480-e0d3-11eb-8104-81bafe842465.png)

**Comment by dsnet** [comment] 2021-07-09 08:36
Can you at least take a screenshot of one of the generated messages? So far, it's clear that these are really old message. When was the last time these .pb.go files have been updated?

**Comment by StarCsu** [comment] 2021-07-09 08:42
> It almost seems certain that this is either operating on extremely old `protoc-gen-go` messages or messages not generated by `protoc-gen-go` since a bulk of time is spent in `sizePointerSlow` which won't happen for new messages. It goes through this logic when the sizecache field is not available. In that situation, the performance may be quadratic.

The two I tested were generated last year. I updated my protoc-gen-go, and then generated and tested again.

**Comment by StarCsu** [comment] 2021-07-09 08:46
> Can you at least take a screenshot of one of the generated messages? So far, it's clear that these are really old message. When was the last time these .pb.go files have been updated?
Is the following version older?
![image](https://user-images.githubusercontent.com/26735787/125050609-b0de9d80-e0d4-11eb-9a75-83bf993bd9cd.png)
![image](https://user-images.githubusercontent.com/26735787/125050942-09159f80-e0d5-11eb-9554-cdb2626b26a6.png)

**Comment by dsnet** [comment] 2021-07-09 08:46
> The two I tested were generated last year. I

They must have been regenerated with and old version of `protoc-gen-go`. It must be v1.3 or older.

**Comment by StarCsu** [comment] 2021-07-09 08:47
> > The two I tested were generated last year. I
> 
> They must have been regenerated with and old version of `protoc-gen-go`. It must be v1.3 or older.

ok,I try it

**Comment by dsnet** [comment] 2021-07-09 08:49
I recommend regenerating these messages with protoc-gen-go@v1.4.0 or latter and report back what the performance numbers are. Also, it's not enough to regenerate just the top-level messages, but all messages that are transitively reachable. The existence of any messages that lack the sizecache field may be the cause of the what appears to be quadratic time computing the message size.

**Comment by dsnet** [comment] 2021-07-09 08:50
Also, this is probably a duplicate of #1149.

**Comment by StarCsu** [comment] 2021-07-09 10:13
> I recommend regenerating these messages with protoc-gen-go@v1.4.0 or latter and report back what the performance numbers are. Also, it's not enough to regenerate just the top-level messages, but all messages that are transitively reachable. The existence of any messages that lack the sizecache field may be the cause of the what appears to be quadratic time computing the message size.

I try it again,Pb is better than JSON in serialization, but worse than JSON in deserialization.
![image](https://user-images.githubusercontent.com/26735787/125062603-28b2c500-e0e1-11eb-81a0-d406912e5088.png)
![image](https://user-images.githubusercontent.com/26735787/125062654-38320e00-e0e1-11eb-85ca-ee29fa027e78.png)

**Comment by StarCsu** [comment] 2021-07-09 10:20
> I recommend regenerating these messages with protoc-gen-go@v1.4.0 or latter and report back what the performance numbers are. Also, it's not enough to regenerate just the top-level messages, but all messages that are transitively reachable. The existence of any messages that lack the sizecache field may be the cause of the what appears to be quadratic time computing the message size.

It is superior in small structure.Thank you for the tip
![image](https://user-images.githubusercontent.com/26735787/125063548-30269e00-e0e2-11eb-8643-82bd7e6bdb30.png)

**Closed** 2021-07-11 16:25 UTC
