### ISSUE TITLE
protoc-gen-go parse field name error while map type;

### ISSUE THREAD

**Issue by CloudGuan** [golang/protobuf#1254] opened 2020-12-15 12:23 UTC
**What version of protobuf and what language are you using?**
Version: (`v3.10.0`)

**What did you do?**
I try to use protoc command to generate golang file with the following command:
protoc -I=E:\ProgramProject\rpc-repo\example\ --go_out=./ E:\ProgramProject\rpc-repo\example\example.service.proto

I generate field name _2 for map type, It works well for cplusplus but reports errors for golang
example message

**What did you expect to see?**
generate golang source file with no errors.
message ServiceDynamic_method3_args {
    int32 _1 = 1;
    map<int64,string> _2 = 2;
    repeated string _3 = 3;
    uint64 _4 = 4;
}

**What did you see instead?**
invalid FileDescriptorProto "example.service.proto": proto: descriptor "example.MyService_method18_args" has an invalid nested name: "16Entry"
--go_out: protoc-gen-go: Plugin failed with status code 1

**Anything else we should know about your project / environment?**

**Comment by dsnet** [comment] 2020-12-15 18:45
Without the input .proto file, we can't really investigate this.

**Comment by CloudGuan** [comment] 2020-12-16 01:36
well, I update my example proto file. 
[example.service.proto.txt](https://github.com/golang/protobuf/files/5699739/example.service.proto.txt)

**Comment by puellanivis** [comment] 2020-12-16 08:23
It is not possible to export types or variables that start with an underscore in Go. (TL;DR: `unicode.IsUpper('_') == false` so it is not exported.)

As a result, there is no way to include an initial underscore in the necessary type names for maps, where the field is named starting with an underscore. As a result, we are mangling the field name `_1` to be `X1`, and so on. However, when we are building the type based on the field, we not mangling it from `_3` to `X3Entry` but instead trying to just remove the underscore, and producing `3Entry`, which is not a valid identifier, because it starts with the letter 3.

It seems like the problems can be avoided by naming all of your fields without an initial underscore. These leading underscores could potentially cause problems with other languages as well, I’m not sure.

**Comment by cybrcodr** [comment] 2020-12-16 20:18
As @puellanivis mentioned, the proto definition contains invalid field names.  See https://developers.google.com/protocol-buffers/docs/reference/proto2-spec#identifiers for more details.

Closing as working as intended.

**Closed by cybrcodr** 2020-12-16 20:18 UTC
Labels: waiting-for-info

**Comment by puellanivis** [comment] 2020-12-17 14:11
@CloudGuan You might want to file a bug against protoc itself, as the language specification linked says that an identifier is not allowed to start with an underscore, and maybe they could error/warn about this issue earlier rather than later.
