### ISSUE TITLE
Using Go modules with vendor-provided Protobuf .proto imports?

### ISSUE THREAD

**Issue by buf1024** [golang/protobuf#897] opened 2019-07-10 07:47 UTC
In my proto file:
```
syntax = "proto3";

package pb;

import "github.com/abc/abc/api.proto";

```

Without Go modules, we could do this:

```
protoc -I. I$GOPATH/src --go_out=. proto/*.proto
```

But Go modules **github.com/abc/abc** is versioned, for example **github.com/abc/abc@1.0.1** , so the above command failed, because path not exists。

Here, my questions is how do I import vendor-provided protobuf(without copy to the **GOPATH**)?

Thanks a lot!

**Comment by millergarym** [comment] 2019-07-10 13:36
`go list` can probably solve your issue
```
$ go list -m -f "{{.Dir}}" github.com/abc/abc
github.com/abc/abc@1.0.1
```
This might do
```
protoc -I. I`go list -m -f "{{.Dir}}" github.com/abc/abc` --go_out=. proto/*.proto
```

**Comment by buf1024** [comment] 2019-07-11 01:48
@millergarym thanks a lot.
But in this case, my proto file should change to this:
```
syntax = "proto3";

package pb;

import "api.proto";          // this will be confuse weather api.proto belongs to the project or the vendor!

```
not my original one:
```
syntax = "proto3";

package pb;

import "github.com/abc/abc/api.proto";

```

**Comment by dsnet** [comment] 2019-07-11 17:04
Making this a duplicate of #748.

**Closed by dsnet** 2019-07-11 17:04 UTC

**Comment by buf1024** [comment] 2019-07-12 06:20
thanks @dsnet !

#748 seems not relate to this. and tried **mod_root**, not work!
