### ISSUE TITLE
Support batch generation with import

### ISSUE THREAD

**Issue by alx696** [golang/protobuf#790] opened 2019-01-18 08:00 UTC
**Is your feature request related to a problem? Please describe.**
son.proto import father.proto from different go_package but same dir. Cant execute protoc:
```
x@x-ThinkPad-T460:~/go/src/lilu.red/proto$ protoc --go_out=plugins=grpc:$GOPATH/src *.proto
2019/01/18 15:32:06 protoc-gen-go: error:inconsistent package import paths: "lilu.red/proto/father", "lilu.red/proto/son"
--go_out: protoc-gen-go: Plugin failed with status code 1.
```
Must protoc one by one manual:
```
x@x-ThinkPad-T460:~/go/src/lilu.red/proto$ protoc --go_out=plugins=grpc:$GOPATH/src father.proto
x@x-ThinkPad-T460:~/go/src/lilu.red/proto$ protoc --go_out=plugins=grpc:$GOPATH/src son.proto
```
If lots of proto, not good any more. I can protoc son.proto first, no error alert. Imply no required check, why alert `error:inconsistent package import paths`?

**Describe the solution you'd like**
Batch generation with one protoc:
```
$ protoc --go_out=plugins=grpc:$GOPATH/src *.proto
```

**Describe alternatives you've considered**
Automatically generated one by one.

**Additional context**
father.proto
```
syntax = "proto3";

package auto.grpc.father;
option go_package = "lilu.red/proto/father";

message Info {
  string name = 1;
}
```

son.proto
```
syntax = "proto3";

package auto.grpc.son;
option go_package = "lilu.red/proto/son";

import "father.proto";

service SonService {
  rpc Insert (Info) returns (Info) {
  }
}

message Info {
  string id = 1; //auto set
  string name = 2;
  father.Info father = 3;
}
```

**Comment by lpflpf** [comment] 2019-03-11 11:15
I had the same question, have you solved it?

**Comment by alx696** [comment] 2019-03-11 12:51
@lpflpf No...

**Comment by dsnet** [comment] 2019-07-10 20:48
Duplicate of #39

**Closed by dsnet** 2019-07-10 20:48 UTC
