### ISSUE TITLE
jsonpb: forward and backward compatible enums

### ISSUE THREAD

**Issue by jeb2239** [golang/protobuf#636] opened 2018-06-13 20:03 UTC
if an invalid enum string is encountered in a received json object, the serialization of the whole object becomes default for every field after the offending enum, even when the rest of the fields are perfectly valid. Is there a reason for this behaviour ? Unmarshall has no field to disable this behavior.

**Comment by dsnet** [comment] 2018-06-22 17:45
I'm not sure I understand your statement, can you provide an example?

**Comment by jeb2239** [comment] 2018-06-22 19:05
So if I have an enum in protobuf that has UNKNOWN=0, NY=1, NJ=2 , and I get a value for that enum I wasn't expecting call it CT=3, the json deserialization of the whole struct fails.

**Comment by dsnet** [comment] 2018-06-22 21:23
> I get a value for that enum I wasn't expecting

You mean you are trying to unmarshal a message with `"CT"` in the JSON, but `CT` is not defined in the proto file? Then deserialization failure is expected. There is no mapping from the unknown name `CT` to some integer value.

**Comment by jeb2239** [comment] 2018-06-22 21:39
Shouldn't it be UNKNOWN instead of giving up on the rest of the structure?

**Comment by dsnet** [comment] 2018-06-22 21:43
Why? You only happened to name the first enum "UNKNOWN" such that it seems to make sense as the default for unknown enums. What you named enum 0 as "BURGERS"?

**Comment by jeb2239** [comment] 2018-06-22 21:50
Ok but in the binary implementation if I get 3 won't it just default to 0

**Comment by jeb2239** [comment] 2018-06-22 21:52
Also the whole rest of the structure is set to their default values after you return an error.

**Comment by dsnet** [comment] 2018-06-22 21:53
In the binary representation, if you get a 3, you will store 3 as the enum value, even though is 3 is a not a declared enum value.

In JSON, this behavior should also occur if the JSON input had a numeric value instead of a string.

**Comment by jeb2239** [comment] 2018-06-22 21:55
Ok so why is a string different? And why does encountering an invalid string mean the rest of the members in the structure need to be set to their defaults just because one enum is invalid?

**Comment by dsnet** [comment] 2018-06-22 21:57
> Ok so why is a string different? 

The underlying kind for an enum is an `int32`, there is no place to store the unknown enum value in string form.

> rest of the members in the structure need to be set to their defaults

That's not happening. A parsing error is a fail-fast operation, leaving the struct (likely) in it's zeroed state, which happens to be the default values for most fields.

**Comment by dsnet** [comment] 2018-06-26 19:31
Closing this as working as intended. Whether we support a form of "unknown fields by name" is beyond the scope of Go protobufs, and would have to be an issue raised up in the mainline implementation at [github.com/google/protobuf](http://github.com/google/protobuf) since we follow their specifications.

**Closed by dsnet** 2018-06-26 19:31 UTC
Labels: jsonpb, question
