### ISSUE TITLE
jsonpb will omits enum which value is 0 in MarshalToString 

### ISSUE THREAD

**Issue by stevenwangnarvar** [golang/protobuf#918] opened 2019-08-01 23:38 UTC
**What version of protobuf and what language are you using?**
libprotoc 3.7.1

**What did you do?**
consider below probo message contain enum type
```
    enum FruitsType {
        APPLE = 0;
        BANANA = 1;
        ORANGE = 2;
    }
```
if inside the pb message, the FruitsType is 0, when I try MarshalToString, that field will be omits, but if that FruitsType is not 0, I can get the field in json payload.

**What did you expect to see?**
I want get the enum value no matter it is the default value 0 or others.

**What did you see instead?**
I can't get enum json field is the pb message set 0 to that enum field.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
I can find in jsonpb.go, if the field is int and value is 0, it will skip the below code for handle enum.
<img width="654" alt="Screen Shot 2019-08-02 at 11 36 04 AM" src="https://user-images.githubusercontent.com/49885838/62333964-cd055780-b519-11e9-9876-aecef082752d.png">

**Anything else we should know about your project / environment?**
No.

**Comment by dsnet** [comment] 2019-08-01 23:44
I apologize. This is indeed a duplicate of #836. `APPLE` is the zero value for the `FruitsType` enum. The proto<->JSON specification dictates the marshaling behavior, which we abide by. If you want to explicitly marshal the zero value, then specify the `EmitDefaults` option.

**Closed by dsnet** 2019-08-01 23:44 UTC

**Comment by stevenwangnarvar** [comment] 2019-08-01 23:52
@dsnet, thanks for clarifying, there is one concern. As `EmitDefaults` is a global flag, which I only want to emit enum. The second thing is I think Marshaler has a property `EnumsAsInts`, I think set `EnumsAsInts` to true, omits may make sense. But if `EnumsAsInts` is false, which means I treat this field like a string, so in any situation, I want to get this value from marshaling.

**Comment by dsnet** [comment] 2019-08-01 23:59
Unfortunately, what you're trying to do is not something that our marshaler is capable of emitting. The `jsonpb` package is intended to the be faithful implementation of the proto<->JSON specification, for which the C++ implementation is considered the canonical "reference" implementation.

The [C++ implementation only has small set of options](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util#JsonPrintOptions) and we (the Go implementors of protobuf) have no intention of adding features that are beyond what C++ provides. The `EmitDefaults` option in Go is analogous to the `always_print_primitive_fields` option in C++. The other options that Go currently has are a historical mistake.

**Comment by stevenwangnarvar** [comment] 2019-08-02 00:05
Thanks @dsnet for your explanation.
