### ISSUE TITLE
New fields in pb.go after regenerating with upgraded version of protoc-gen-go and protoc compiler

### ISSUE THREAD

**Issue by phoenix16644** [golang/protobuf#1171] opened 2020-07-15 05:38 UTC
I am upgrading all the libraries(go, protoc, grpc) we use. Once I updated the protoc compiler , protoc-gen-go and regenerated the protos. Some of the structs in the pb.go file have new meta fields/variables added- state, sizeCache,unknownFields. These did not exist in the old pb file.

type x struct {                                                       
    state         protoimpl.MessageState                                            
    sizeCache     protoimpl.SizeCache                                               
    unknownFields protoimpl.UnknownFields                                           
                                                                                    
    a int64  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
    b []byte `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
    c string `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
}     
So addition of these fields results in compilation error, when creating this struct with the existing code. Are these fields something that needs to be taken care of by the code? or am i missing something while upgrading ?

**Comment by dsnet** [comment] 2020-07-15 05:42
> Some of the structs in the pb.go file have new meta fields/variables added- state, sizeCache,unknownFields. These did not exist in the old pb file.

The `sizeCache`, `unknownFields`, etc fields are new, but they replace the previous `XXX_sizecache`, `XXX_unrecognized`, etc fields. The [compatibility document specifies that we can add/remove `XXX` and unexported fields as necessary](https://github.com/golang/protobuf/tree/v1.3.5#compatibility).

> So addition of these fields results in compilation error

Can you explain how?

**Comment by phoenix16644** [comment] 2020-07-15 05:52
Code like this :
reply = PkgEx.x{a, []b{}, c}  

Results in these errors: 

foo.go: implicit assignment of unexported field 'state' in PkgEx.x literal
foo.go: cannot use a (type int64) as type impl.MessageState in field value
foo.go: implicit assignment of unexported field 'sizeCache' in PkgEx.x literal
foo.go: cannot use []byte literal (type []byte) as type int32 in field value
foo.go: implicit assignment of unexported field 'unknownFields' in PkgEx.x literal
foo.go: cannot use c (type string) as type []byte in field value
foo.go: too few values in PkgEx.x literal
foo.go: implicit assignment of unexported field 'state' in PkgEx.x literal
foo.go: cannot use a (type int64) as type impl.MessageState in field value
foo.go: implicit assignment of unexported field 'sizeCache' in PkgEx.x literal

**Comment by dsnet** [comment] 2020-07-15 05:59
Code like that hasn't worked since the [v1.1.0 release](https://github.com/golang/protobuf/releases/tag/v1.1.0) of `protoc-gen-go` from 2 years ago.

In general, it's not safe to rely on unkeyed struct literals for any type that is not directly within your control. This isn't specific to protobufs, but a general compatibility assumption within the Go ecosystem itself. For example, the [Go standard library calls this out](https://golang.org/doc/go1compat#expectations):
> Struct literals. For the addition of features in later point releases, it may be necessary to add fields to exported structs in the API. **Code that uses unkeyed struct literals (such as pkg.T{3, "x"}) to create values of these types would fail to compile after such a change**. However, code that uses keyed literals (pkg.T{A: 3, B: "x"}) will continue to compile after such a change. **We will update such data structures in a way that allows keyed struct literals to remain compatible, although unkeyed literals may fail to compile**. (There are also more intricate cases involving nested data structures or interfaces, but they have the same resolution.) We therefore recommend that composite literals whose type is defined in a separate package should use the keyed notation.

**Comment by dsnet** [comment] 2020-07-15 22:23
Closing as this is working as intended.

**Closed by dsnet** 2020-07-15 22:23 UTC
Labels: waiting-for-info
